### ISSUE TITLE
Event GUILD_MEMBER_UPDATE does not return the updated role

### ISSUE THREAD

**Issue by shnytzl** [teamreflex/DiscordPHP#104]
```
$ws->on(Event::GUILD_MEMBER_UPDATE,function($guildmember,$discord){
echo 'Guild member update recognized.'PHP_EOL;
}
```

recognizes the event, but the roles of the guildmember are not updated, only restarting the bot works to get the new roles of the members.
Looks like public function updateDiscordInstance($data, $discord) does not work properly.

**Comment by uniquoooo** [comment]
Fixed in Version 4.
