### ISSUE TITLE
Stopping / Pausing Audio playback once it's started

### ISSUE THREAD

**Issue by karbowiak** [teamreflex/DiscordPHP#114]
Is it possible to somehow stop/pause the playback, once it has begun?

**Comment by uniquoooo** [comment]
`VoiceClient->pause()` will pause the current playing sound, `VoiceClient->unpause()` will unpause it. You can use `VoiceClient->stop()` to completely stop it.

**Comment by karbowiak** [comment]
You are amazing! <3

Only issue i'm having now is getting ffmpeg to handle a live audio stream, but i'll catch you on Discord about that at some point :)
