### ISSUE TITLE
DCA doesn't exit when stream is stopped

### ISSUE THREAD

**Issue by karbowiak** [teamreflex/DiscordPHP#115]
So when a stream is stopped and then closed afterwards, dca-linux is just left in the background..

**Comment by uniquoooo** [comment]
Could you try the new version I pushed to `develop`? DCA doesn't stay open when I check on that version.

**Comment by karbowiak** [comment]
That did it ! A thousand thanks, no longer shall i wake up to >1k threads belonging to orphaned dca-linux threads :D
