### ISSUE TITLE
VoiceClient instantly disconnects on connect.

### ISSUE THREAD

**Issue by ThatOneCheetah** [teamreflex/DiscordPHP#121]
Tested on Debian Jessie ARMHF-32 and Windows 10 Home N 64 Bit.

Both using the provided test code.

**Comment by Lytearro** [comment]
When you're getting disconnected, are you getting any errors in console, ie "Your version of DCA is outdated", etc..? Could you please provide example code you are specifically using?

**Comment by ThatOneCheetah** [comment]
The example code I am using is [the one on this github (voice.php)](https://github.com/teamreflex/DiscordPHP/blob/master/examples/voice.php).

It doesn't throw any errors, it hangs at connecting to the voice channel, while does connect, but then instantly disconnects and becomes stuck in an infinite loop somewhere as something is halting the program.

**Comment by Lytearro** [comment]
That's because the loop is put in that way..  Remove the highlighted lines
https://github.com/teamreflex/DiscordPHP/blob/master/examples/voice.php#L74-L84

**Comment by ThatOneCheetah** [comment]
I have tried all possible things already, including a barebones implementation, I'm just not getting it to work.

**Comment by ThatOneCheetah** [comment]
![It seems to be an authentication issue?](http://i.imgur.com/ysnjDhR.png)

**Comment by 4RV1D** [comment]
I have the exact same problem, and i don't see the line "_Joined voice channel_" echo anywhere so i assume it's something that goes wrong with the joinVoiceChannel.

**Comment by Lytearro** [comment]
https://github.com/teamreflex/DiscordPHP/blob/master/examples/voice.php#L86 on this like between the `)` and `;`, you can add a `->otherwise(function($e) { echo "ERR: ".$e->getMessage(); } );`
Since the joinVoiceChannel is async, it might now display the error if there is one, so putting the otherwise will show you the error if there is one.
