### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by shibdib** [teamreflex/DiscordPHP#129]
PHP Fatal error:  Uncaught exception 'Discord\Exceptions\DiscordRequestFailedException' with message 'Error code 500: This usually means something went wrong with Discord. INTERNAL SERVER ERROR - {"code": 0, "message": "MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error."} - users/@me' in /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Helpers/Guzzle.php:206
 Stack trace:
 #0 /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Helpers/Guzzle.php(134): Discord\Helpers\Guzzle::handleError(500, 'INTERNAL SERVER...', Object(GuzzleHttp\Psr7\Stream), 'users/@me')
 #1 /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Helpers/Guzzle.php(66): Discord\Helpers\Guzzle::runRequest('get', 'users/@me', NULL, false, Array)
#2 /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Discord.php(71): Discord\Helpers\Guzzle::__callStatic('get', Array)
 #3 /home/Dramiel/vendor/team- in /home/Dramiel/vendor/team-reflex/discord-php/src/Discord/Helpers/Guzzle.php on line 206

Have no clue what caused it

**Comment by uniquoooo** [comment]
Error with the Discord servers, can't do anything about it. Should work if you retry it.
