### ISSUE TITLE
Detecting bot name

### ISSUE THREAD

**Issue by Zyles** [teamreflex/DiscordPHP#133]
Is there a way to detect the bots name in a message? Especially when using @Botname

Right now I use this:

```
if (stripos($message->content, 'Botname') !== false) {
		    echo 'Someone said my name!' . PHP_EOL;
		}
```

But it won't fire if you use @.

The message content looks something like this:

```
<@203453453453454353> hello
```

So I assume I can parse this clientid, but is there a more elegant way?

**Comment by uniquoooo** [comment]
You can listen for mentions in Version 3 with:

```php
$discord->on('mention', function ($message, $discord) {
    // do stuff
});
```

**Comment by Zyles** [comment]
Thanks got it working. Got confused since it was not in the Event class.
