### ISSUE TITLE
Closing a connection

### ISSUE THREAD

**Issue by unbolt** [teamreflex/DiscordPHP#134]
How do you close a connection? By default WebSocket/Ratchet usage it should be 

`$ws->close();`

However that is returning the following:

`Call to undefined method Discord\WebSockets\WebSocket::close()`

This is my code:

```
        $discord = new Discord('BOT ID');
        $ws      = new WebSocket($discord);
        $ws->on('ready', function ($discord) use ($ws) {
            $guild = $discord->guilds->get('id', 'SERVER ID');
            $channel = $guild->channels->get('id', 'CHAN ID');
            $channel->sendMessage('This is a test of the emergency broadcast system...');
            $ws->close();
        });

        $ws->run();
```

How would you close a connection? Is it possible to do this without the WebSocket using DiscordPHP using basic RESTful commands?

**Comment by lluiscab** [comment]
If you just want to send a message, don't use the websocket, just move the code that you have to get the guild and channel outside of the webSocket

`

**Comment by unbolt** [comment]
Ah, yes that works. So weird, I would swear I tried that... Though I did do some messing with permissions.

Cheers :)
