### ISSUE TITLE
Any easy way to detect author's voice channel

### ISSUE THREAD

**Issue by bertZ** [teamreflex/DiscordPHP#135]
Hi, I'm developing a bot and I want to use some audio commands. I managed to make it work for a specific voice channel... Is there any easy way to get the voice channel that the person using the command is in so my bot can join and play the audio?

**Comment by Lytearro** [comment]
```php
$channel = $message->full_channel->guild->channels->getAll('type', 'voice');
for($i=0;$i<count($channel);$i++){
	if(isset($channel[$i]->members[$message->author->id])){ $channel = $channel[$i]; $found = true; break; }
}```

This is what I use, $found doesn't even need to be declared, you can check for if channel->count() < 2.

**Comment by bertZ** [comment]
Wow, thank you very much. You helped a lot!
