### ISSUE TITLE
VoiceClient not playing file

### ISSUE THREAD

**Issue by bertZ** [teamreflex/DiscordPHP#136]
My voiceClient isn't working when I try to run $voiceClient->playFile($filePath) and isn't showing any errors... The audio file path is correct (verified it using other functions), the bot connects to the voice channel and everything before and after calling playFile() executes normally (except the then() method).

```
$ws->on('ready', function () use ($ws, $channel) {
	$ws->joinVoiceChannel($channel)->then(function (VoiceClient $vc) use ($channel) {
		echo 'Joined '.$channel->name.' voice channel'.PHP_EOL; // Runs fine

		$vc->setFrameSize(40)->then(function () use ($vc) {
			$vc->playFile('./audio/test.mp3')->then(function () {
                		echo 'Playing test on '.$channel->name.' voice channel.\r\n'; // Not being executed
           		 });
		});
	});
});
```

I'm using a mp3 file.
In which cases playFile() wouldn't work?

Edit: Added code.

**Comment by Lytearro** [comment]
try appending a `-otherwise(function($e){ echo "ERR: ".$e->getMessage(); })` to the end of the playFile section and see if the triggers some sort of error.

**Comment by bertZ** [comment]
Oh, got an Outdated DCA error... I thought it supported mp3 files, seems like I'll need to convert it do dca

**Comment by bertZ** [comment]
DCA updated and now everything works fine.
Thank you.

**Comment by GerritHoekstra** [comment]
@bertZ I got the same message. I tried to update DCA and build it with `go build`. But then I still receive the same message:
`You are using an outdated version of DCA. Please make sure you have the latest version from https://github.com/bwmarrin/dca`

Could you tell me how you've updated DCA?

**Comment by bertZ** [comment]
@GerritHoekstra I just followed the installing guide provided by Uniquoooo at https://github.com/bwmarrin/dca/blob/master/cmd/dca/README.md and it worked fine.

I did it on Windows 10 Bash (Bash on Ubuntu on Windows as some call it).
