### ISSUE TITLE
Can't connect, 'websocket closed op:1000'

### ISSUE THREAD

**Issue by nesttle** [teamreflex/DiscordPHP#137]
**System info:**
- Windows x64,
- PHP 5.6 (xampp stack),
- DiscordPHP 4.0.0 dev-develop (via composer)

**example2.php** (XXXXXXXXXX = My BOT token)

> include __DIR__.'/vendor/autoload.php';
> use Discord\Discord;
> $discord = new Discord([
> 	'token' => 'XXXXXXXXXX',
> ]);
> $discord->on('ready', function ($discord) {
> 	echo "Bot is ready!".PHP_EOL;
> 	// Listen for messages.
> 	$discord->on('message', function ($message, $discord) {
> 		echo "{$message->author->username}: {$message->content}",PHP_EOL;
> 	});
> });
> $discord->run();

**CMD**

> C:\xampp\htdocs\discordbot>php example2.php
> [2016-07-28 23:02:18] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
> [2016-07-28 23:02:18] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
> [2016-07-28 23:02:19] DiscordPHP.INFO: websocket connection has been created [] []
> [2016-07-28 23:03:14] DiscordPHP.INFO: received hello [] []
> [2016-07-28 23:03:14] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"XXXXXXXXXX","properties":{"$os":"WINNT","$browser":"DiscordPHP/v4.0.0-develop DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0-develop)","$device":"DiscordPHP/v4.0.0-develop DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0-develop)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://github.com/teamreflex/DiscordPHP"},"compress":true}}} []
> [2016-07-28 23:03:14] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
**> [2016-07-28 23:03:14] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []**
> [2016-07-28 23:03:14] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
> [2016-07-28 23:03:14] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
> [2016-07-28 23:03:15] DiscordPHP.INFO: websocket connection has been created [] []
> [2016-07-28 23:04:10] DiscordPHP.INFO: received hello [] []
> [2016-07-28 23:04:10] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"XXXXXXXXXX","properties":{"$os":"WINNT","$browser":"DiscordPHP/v4.0.0-develop DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0-develop)","$device":"DiscordPHP/v4.0.0-develop DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0-develop)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://github.com/teamreflex/DiscordPHP"},"compress":true}}} []
> [2016-07-28 23:04:10] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
**> [2016-07-28 23:04:10] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []**
> [2016-07-28 23:04:10] DiscordPHP.INFO: starting reconnect {"reconnect_count":2} []
> [2016-07-28 23:04:10] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
> [2016-07-28 23:04:11] DiscordPHP.INFO: websocket connection has been created [] []
> [2016-07-28 23:05:06] DiscordPHP.INFO: received hello [] []

Was working fine with `dev-master`, same token :(

**Comment by uniquoooo** [comment]
I'll look into it, 1000 usually means it was cleanly closed so not sure what is happening.

**Comment by nesttle** [comment]
Idle 30 seconds after:
`[2016-07-28 23:03:15] DiscordPHP.INFO: websocket connection has been created [] []`

Then, outputs:

> [2016-07-29 00:02:21] DiscordPHP.INFO: received hello [] []
> [2016-07-29 00:02:21] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"XXXXXXXXXX","properties":{"$os":"WINNT","$browser":"DiscordPHP/v4.0.0 DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0)","$device":"DiscordPHP/v4.0.0 DiscordBot (https://github.com/teamreflex/DiscordPHP, v4.0.0)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://github.com/teamreflex/DiscordPHP"},"compress":true}}} []
> [2016-07-29 00:02:21] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
> [2016-07-29 00:02:21] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []
> [2016-07-29 00:02:21] DiscordPHP.INFO: starting reconnect {"reconnect_count":6} []
> [2016-07-29 00:02:21] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []

**Comment by nesttle** [comment]
Working fine in c9.io with PHP7.0

Maybe PHP 5.6 not fully compatible?

Sorry for any inconvenience,
thanks

**Comment by uniquoooo** [comment]
Might be, let me look into it, I haven't tested on 5.6.

**Comment by uniquoooo** [comment]
I've tested it on 5.6 and it works fine for me, could it be your internet or computer that you are running it on? Reopen if you still have issues.

**Comment by snijplank** [comment]
Im having this same issues, correlated or not? please readvice:

[2021-01-09T02:12:09.129865+00:00] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []
[2021-01-09T02:12:09.130627+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2021-01-09T02:12:11.131029+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
