### ISSUE TITLE
addPeriodicTimer() blocks the execution of my code

### ISSUE THREAD

**Issue by nesttle** [teamreflex/DiscordPHP#138]
Hi folks!

I have a code like this:

> 			if ($message->content == 'startrare') {
> 				$loop->run($timer);
> 			} 

When if = true, loop runs and my code stops executing. Acts like a traditional php while/foreach...

Loop code looks like this:

> $loop = React\EventLoop\Factory::create();
> $i = 0;
> $timer = $loop->addPeriodicTimer(5, function() use (&$myvar0, $loop, &$myvar1, &$myvar2, &$myvar3) {
> echo 'OK';
> ...

I receive 'OK' each 5 seconds, but other code after (or before) loop not working until loop stops :/

 http://pastebin.com/5Gq0ujMu

**Comment by nesttle** [comment]
When I run the loop (startloop message on channel), loop runs correctly but DiscordPHP stops listening for any other command!

**Comment by nesttle** [comment]
I'm rewriting the code, will pass a custom Loop with DiscordPHP: `'loop' => $mycustomloop`
the problem now is, I can't retrieve any `$variable` value inside my `$mycustomloop`
https://github.com/reactphp/event-loop/issues/54#issuecomment-236435544

**Comment by uniquoooo** [comment]
Are you still having this issue?
