### ISSUE TITLE
updating message no longer possible in v4

### ISSUE THREAD

**Issue by lsascha** [teamreflex/DiscordPHP#139]
in the older version i did the following to update the text of an existing message:

```
$message->content = 'my updated text';
$message->save();
```

unfortunately in v4 the save() method does no longer exist, and only setting the content attribute does not send it back to discord.

How is it intended now in v4?

**Comment by uniquoooo** [comment]
Read the wiki here, will let you know what you need to change: https://discordphp.readme.io/docs/converting-from-version-3x#updating-and-deleting-parts
