### ISSUE TITLE
(Windows 8.1 x64) PHP Warning:  pack(): ...

### ISSUE THREAD

**Issue by lefranj** [teamreflex/DiscordPHP#143]
`PHP Warning:  pack(): 64-bit format codes are not available for 32-bit versions of PHP `
When trying to start playing audio in voice channel...
Using PHP 5.6 x64

**Comment by lluiscab** [comment]
Same for me, php is not on 64bits on windows

**Comment by uniquoooo** [comment]
Any PHP version below 7.x on Windows does not support 64-bit integers no matter the architecture, nothing I can do sorry.
