### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ScreamZ** [teamreflex/DiscordPHP#146]
Hello,

the lib seems to be nice but can you please put some examples about how to do basic things,
it's really hard to start using the lib...

At least can you give us a sandbox instance that demonstrate what can be done (changing perm, add role, send message....)

Thank you

**Comment by lethak** [comment]
I agree the doc is rudimentary, but with a good IDE we can manage to discover most stuff quickly.

@ScreamZ I am currently writing a symfony2 bundle to do just that.

**Comment by namaless** [comment]
@lethak why sf2 and not sf3? Btw is true I have used this before and working fine, the only problem come when you not use phpstorm or any other one good ide 👍

**Comment by lethak** [comment]
The bundle is not going to be public atm, but is compatible/tested on sf 2.8, I have not migrated over 3.x yet.

**Comment by 1vadios** [comment]
Hey just wanted to know how when can we expect that it is going public?

**Comment by ScreamZ** [comment]
Hey buddy, i just paused this, but i'll try to release this at least in a light version, meaning that you'll fetch array instead of PHP objects filled.

**Comment by davidcole1340** [comment]
Currently trying to patch all the issues with the library. Documentation is available albeit quite weak.
