### ISSUE TITLE
$message->reply() to user with Nick

### ISSUE THREAD

**Issue by CrYoZs** [teamreflex/DiscordPHP#149]
Hi!

May be found a typo?

[here](https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/User/Member.php#L298)

```
public function __toString()
    {
        if ($this->nick) {
            return "<@!{$this->user->id}";
        }
        return "<@{$this->user->id}>";
    }
```
`return "<@!{$this->user->id}";`
Is this right? It seem at the end of string should be symbol `>`

**Comment by uniquoooo** [comment]
Thanks!
