### ISSUE TITLE
Opening another socket or listening to inbound external calls outside Discord

### ISSUE THREAD

**Issue by Zyles** [teamreflex/DiscordPHP#150]
Is it possible to do something like this:

https://blog.wyrihaximus.net/2015/03/reactphp-sockets/

My scenario:

I want a REST API or a communication possibility with the bot outside of Discord. So I can send a command from an external server to the bot either using a socket or through HTTP.

Because I assume you cannot send a message with an external headless server client through Discord itself to the bot.

But since DiscordPHP has abstracted ReactPHP I'm not sure how to open another socket connection and listen to connections and read the payload coming through.

Any tips?

**Comment by Omegatcu** [comment]
I think you have to open the socket from inside discord and then check it if a change comes through.

My solution to that Problem is pretty dirty but I have a loop that checks a mysql Database every couple of minutes - if i want to send a command to the bot i put it in the mysql DB and the Bot can then do what I want.

**Comment by Zyles** [comment]
@Omegatcu I use a message queue for that. But I wan't to open another socket and point Nginx to it.

**Comment by GameCharmer** [comment]
@Zyles would you happen to have an example of how you're using a message queue with this?  I've been trying to get this to read from a queue and post messages in the chat for a while, but I've only managed to get it to post once.  It'll loop just fine, but can only post in the channel once and then stops sending...

**Comment by Zyles** [comment]
@GameCharmer Depends what your framework looks like. I have mine in classes.

```
        // How often to sleep between checks (seconds)
        $interval = 60;

        $this->discord->loop->addPeriodicTimer($interval, function () use (Discord $discord) {
            	// Check MQ for messages
            	$this->checkMessages();
        });
```

**Comment by GameCharmer** [comment]
@Zyles You're a saint! Thank you!

**Comment by davidcole1340** [comment]
Check out ReactPHP HTTP server. Will interact with the event loop. Closing due to age.
