### ISSUE TITLE
$discord->factory() hangs indefinitely

### ISSUE THREAD

**Issue by GeertHauwaerts** [teamreflex/DiscordPHP#153]
I am trying to update the game presence of my bot, whenever I call `$discord->factory()` the bot hangs indefinitely.

The problem exists on version 4.0.1 (latest release) and the development version.

```
<?php

use Discord\Discord;

require __DIR__ . '/vendor/autoload.php';

$discord = new Discord(['token' => 'my-key']);

$discord->on('ready', function ($discord) {
  $game = $discord->factory(Game::class, [
    'name' => 'with kittens',
  ]);

  var_dump($game); // doesn't dump, hangs indefinitely on factory() call, no errors or warnings.
});

$discord->run();
```

PS: If this is a pebkac, I humbly apologize in advance.

**Comment by uniquoooo** [comment]
I'm not sure what is stopping errors from outputting, but you need to import the `Game` class. Add `use Discord\Parts\User\Game;` at the top of your file and it should work.
