### ISSUE TITLE
is_private set to true for channel messages.

### ISSUE THREAD

**Issue by second-hand-earth** [teamreflex/DiscordPHP#155]
Channel messages are flagged as if they are direct messages.
is_private is set to 1
type is set to 1

Test code:
expected behavior: bot will die on a direct message.
actual behavor: bot will die on any channel message

```
<?php
/*!
 * \file
 * \brief is_private test code.
 * \date 2016-09-13
 * \version 0.1
 */

include __DIR__.'/vendor/autoload.php';

$discord = new \Discord\Discord([
    'token' => TOKEN_HERE,
]);

$discord->on('ready', function ($discord) {

    echo "Bot is ready.", PHP_EOL;

    // Listen for events here
    $discord->on('message', function ($message) {
# Accept private messages only
        if ($message->channel->is_private === TRUE) {
                echo "Recieved a private message from {$message->author->username}: {$message->content}", PHP_EOL;
                print_r($message);
                print_r($message->channel);
                print_r($message->channel->recipients);

                die();
        }
    });
});


$discord->run();
```

**Comment by second-hand-earth** [comment]
ran it again without the === TRUE, same result.

**Comment by second-hand-earth** [comment]
A valid work-around is to cycle through the guilds/channels to see if there's a matching channel id as the incoming message.

```
                global $discord;
                $guildRepository = $discord->guilds;
                $gi = $guildRepository->getIterator();
                while ($gi->valid()) {
                        $go = $gi->current();
                        $channelRepository = $go->channels;
                        $ci = $channelRepository->getIterator();
                        while ($ci->valid()) {
                                print_r($ci->current());
                                if ($ci->current()['id'] == $message->channel->id) {
                                        die('This is a message from a channel.');
                                }
                                $ci->next();
                        }
                        $gi->next();
                }
```

**Comment by second-hand-earth** [comment]
Some more weirdness. I'm running the code in two different environments, one has this issue, the other doesn't.

No problems: PHP 5.6.24-0+deb8u1 on Debian.
Problems: PHP 7 (whatever current version) on Ubuntu.

**Comment by donkkill13** [comment]
I have found the issue, it lies inside of a function in Discord\Parts\Channel\Message.php, that function is `public function getChannelAttribute()
    {
        foreach ($this->discord->guilds as $guild) {
            if ($guild->channels->has($this->channel_id)) {
                return $guild->channels->get('id', $this->channel_id);
            }
        }

        if ($this->cache->has("pm_channels.{$this->channel_id}")) {
            return $this->cache->get("pm_channels.{$this->channel_id}");
        }

        return $this->factory->create(Channel::class, [
            'id'   => $this->channel_id,
            'type' => Channel::TYPE_DM,
        ], true);
    }`

Inside the function, the if statement:

`if ($guild->channels->has($this->channel_id)) {
                return $guild->channels->get('id', $this->channel_id);
            }`

always results in false for some reason, so changing it to:

`if (!empty($guild->channels->get('id', $this->channel_id)) {
                return $guild->channels->get('id', $this->channel_id);
            }`

fixed the issue entirely, allowing $message->channel->is_private to finally have false inside of it, along with the entire channel elements inside of it and the guild. No more workarounds-ish.

**Comment by davidcole1340** [comment]
Running the following code on the develop branch works for me:

```php
$discord->on('ready', function ($discord) {
    echo 'Ready';

    $discord->on('message', function ($message) {
        if ($message->channel->is_private == true) {
            echo "Received a private message from {$message->author->username}: {$message->content}", PHP_EOL;
        }
    });
});
```

Closing due to age.
