### ISSUE TITLE
No way to delete messages in a direct message channel.

### ISSUE THREAD

**Issue by second-hand-earth** [teamreflex/DiscordPHP#156]
The channel only has a function to do a bulk delete, however it is not supported by the Discord API:

As per:
https://discordapp.com/developers/docs/resources/channel

Bulk Delete Messages
POST/channels/{channel.id}/messages/bulk_delete
Delete multiple messages in a single request. This endpoint can only be used on guild channels and requires the 'MANAGE_MESSAGES' permission. Returns a 204 empty response on success. Fires multiple Message Delete Gateway events.

The current workaround is to .... either write a delete function within channel or call $http->delete directly

**Comment by uniquoooo** [comment]
```php
$channel->messages->delete($message);
```
Have you tried this?

**Comment by second-hand-earth** [comment]
I have tried it now. Did not do anything. Does it return a promise? I'd like to look into it further.

**Comment by uniquoooo** [comment]
Yes it returns a promise.

**Comment by second-hand-earth** [comment]
it works. Thanks and Sorry for creating a ticket.
