### ISSUE TITLE
Bot not executing then() after joining a channel

### ISSUE THREAD

**Issue by Gruutak** [teamreflex/DiscordPHP#158]
Hi, I'm trying to run the following code:

```
$discord->joinVoiceChannel($authorChannel)->then(function (VoiceClient $vc) use ($file) {
    echo "test";
    var_dump($vc);    
})->otherwise(function($e){ echo "ERR: ".$e->getMessage(); });
```

The bot joins the channel just fine, but doesn't run then() or otherwise() after that...
Everything after that code works just fine, so it's not hanging.

I tried var_dumping the promised returned from the joinVoiceChannel and got the following:

```
object(React\Promise\Promise)#1180 (6) {
  ["canceller":"React\Promise\Promise":private]=>
  NULL
  ["result":"React\Promise\Promise":private]=>
  NULL
  ["handlers":"React\Promise\Promise":private]=>
  array(0) {
  }
  ["progressHandlers":"React\Promise\Promise":private]=>
  array(0) {
  }
  ["requiredCancelRequests":"React\Promise\Promise":private]=>
  int(0)
  ["cancelRequests":"React\Promise\Promise":private]=>
  int(0)
}
```

It was working when DiscordPHP v4 was released... I stopped experimenting with it for some time and now (after some composer updates) I tried using it again and noticed it wasn't working like it was before.

I tried using both Ubuntu 16.04 and Windows 10 Bash.
All requirements are installed.

**Comment by uniquoooo** [comment]
Is there anything logged in console? There should be a logger created for the voice channel.

**Comment by uniquoooo** [comment]
Can you try the latest version of DiscordPHP on `develop`.

**Comment by Gruutak** [comment]
Updating to develop version fixed the issue. Thanks.
