### ISSUE TITLE
always show 2 elements in array???

### ISSUE THREAD

**Issue by heroes1412** [teamreflex/DiscordPHP#159]
i write some code to add 1 element to array when received a new message. but, i dont know reason my array seem not to add new element?.

check my images...

![capture](https://cloud.githubusercontent.com/assets/4547508/19123045/5fb5b6a0-8b57-11e6-8a57-7445d3740a0a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4547508/19123046/5fbb0420-8b57-11e6-80ee-bd84ba4e729a.PNG)

**Comment by uniquoooo** [comment]
Move the `$cacheArr` definition to below the `echo` statement. You are redefining it every time you receive a message.

**Comment by heroes1412** [comment]
Hi,
 Moved the $cacheArr definition to below the echo statement, but dont work @@.

here my script:
http://pastebin.com/p2iBuf32

**Comment by uniquoooo** [comment]
On line 15 change the statement to:
```
$discord->on('message', function ($message, $discord) use (&$cacheArr) {
```

**Comment by heroes1412** [comment]
thanks, it works.
