### ISSUE TITLE
Mocking system

### ISSUE THREAD

**Issue by paroxp** [teamreflex/DiscordPHP#164]
Maybe could be done as part of: [#163](https://github.com/teamreflex/DiscordPHP/issues/163)

It would be nice, to have ability to mock your entire library...

Let's say, if the `DISCORD_TOKEN_ID` is set to `TEST`:`MOCK`:`?`, the library would allow for the same set of functions, however not connected to anywhere.

It would help, in testing inside as well as outside of this package.

Thanks.

**Comment by davidcole1340** [comment]
Will look into this once the library is working.
