### ISSUE TITLE
User->sendMessage() not working?

### ISSUE THREAD

**Issue by patroniton** [teamreflex/DiscordPHP#166]
Using the following code:

``` php
    $discord->on('message', function ($message, $discord) {
                $member = $message->channel->guild->members->first();
                $member->user->sendMessage('asdf');
    });
```

The user never receives the message from the bot. I can send messages to the channel and reply to messages just fine, but sending messages via the `sendMessage` function seems to not work.

**Comment by uniquoooo** [comment]
Can you try:
```
$member->user->sendMessage('asdf')->then(function ($m) {
    echo "Done\r\n";
}, function ($e) {
    echo $e->getMessage(), PHP_EOL;
});
```

**Comment by patroniton** [comment]
Using that snippet gets an error in the console: `An error occured in the response`

**Comment by uniquoooo** [comment]
I'll look at it when I get home, thanks.

**Comment by rsCuBe** [comment]
I had the same problem

**Comment by jkniest** [comment]
Any progress @uniquoooo ?

Greetz,
Jordan

**Comment by uniquoooo** [comment]
@jkniest Sorry for the late response, should be working on the latest develop branch.
