### ISSUE TITLE
Send message without event

### ISSUE THREAD

**Issue by judahnator** [teamreflex/DiscordPHP#167]
I can send messages just fine as a response to the 'message' event, but cannot seem to send a message outside of that.

I have tried two different things.

The first is this:
```php
$discord = new Discord\Discord([
  'token' => env('BOT_TOKEN')
]);

$discord->factory(Discord\Parts\Channel\Channel::class, [
  'id' => 'CHANNEL_ID'
])->sendMessage('test'))
```
If I dump the return value of the ->sendMessage function it returns a promise object that looks like this:
```php
React\Promise\Promise {#872
  -canceller: null
  -result: null
  -handlers: []
  -progressHandlers: []
  -requiredCancelRequests: 0
  -cancelRequests: 0
}
```

This wouldn't be a problem, if the other method mentioned in issue #132 didnt also seem broken.
Here is the code I tried:
```php
$discord = new Discord\Discord([
  'token' => env('BOT_TOKEN')
]);

$guild = $discord->guilds->get('id', 'GUILD_ID'); // <-- breaks here
$channel = $guild->channels->get('id', 'CHANNEL_ID');

$channel->sendMessage('my message here');
```

When debugging it would appear that $discord->guilds returns null, so calling "->get()" on it results in a fatal error.

Im a bit confused because these operations seem to work a bit later down inside of the "->on('message')" event.

Any ideas? I can't seem to find anything in the docs to say i'm doing it wrong.

**Comment by Tekner** [comment]
It has to be inside of an event, but it doesn't have to be inside of the message event. Add that code inside of $discord->on('ready', ...) and it should work. Everything has to run from a discord event in order for it to function correctly as far as I am able to discern.

**Comment by judahnator** [comment]
@Tekner thanks for the input!

Here is what I have right now:
```php
$discord = new Discord([
    'token' => env('BOT_TOKEN'),
]);

$discord->on('ready', function ($discord) {
    // Break from loop and send messages if needed
    $discord->on('heartbeat', function () use ($discord) {

        $guild = $discord->guilds->get('id', 'GUILD_ID');
        $DiscordChannel = $guild->channels->get('id', 'CHANNEL_ID');
        $DiscordChannel->sendMessage('message');

        echo "heartbeat called at: " . time() . PHP_EOL;
    });

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        $Message = BotController::logMessage($User, $message);
        BotController::reply($message);
    });
});

$discord->run();
```
This is the result I get:
```php
  [InvalidArgumentException]               
  Illegal operator and value combination.  
```

I have some scripts that run in the background that provide input for the bot, but i dont like the idea of needing to wait for a message to be received to be able to send messages out. The heartbeat function looks like it will do just what I need, but i cant seem to send messages from within it.

Does anything here stand out as incorrect?

**Comment by Tekner** [comment]
I'm not familiar with the heartbeat event, but there's a much better and flexible way to execute periodic code in the context of discordphp. Simply utilize the ReactPHP loop that's included in the API like so: `$discord->loop->addPeriodicTimer($tick, $func);`
$tick is the period in seconds and $func can be a closure, variable reference, or string function name that accepts no arguments. You can use `global` within the function if you want to access $discord.

Compressed code example:
```php
$PERIOD = 10; //seconds

//I made a wrapper function so I don't need to reference $discord->loop everywhere,
//but it's obviously not necessary.
function AddLoop($tick, $func) { global $discord; $discord->loop->addPeriodicTimer($tick, $func); }
function DoStuff() {
    global $discord;
    $guild = $discord->guilds->get('id', 'GUILD_ID');
    $channel = $guild->channels->get('id', 'CHANNEL_ID');
    $channel->sendMessage("$PERIOD seconds have passed!");
}

//You could also define DoStuff() as a closure instead of defining it beforehand and referencing it
//as a string. Alternatively, you could set a variable equal to a predefined closure and use that
//variable instead of a string here. The choice is yours in how you reference the function.
AddLoop($PERIOD, 'DoStuff');
```

**Comment by judahnator** [comment]
That set me on the right track. Here is my finished code:
```php
$discord->loop->addPeriodicTimer(10,function () use ($discord) {
  // handle asynchronous feedback outside of event
});

$discord->on('ready', function ($discord) {
  // the rest of the application
});
```
Many thanks!

**Comment by SaschaP1802** [comment]
New Information? all this not Work
