### ISSUE TITLE
getMessageHistory is not working

### ISSUE THREAD

**Issue by lordraz0r** [teamreflex/DiscordPHP#170]
Here is my code.

`$last_message_id = $message->channel->last_message_id;
                    $test = $message->channel->getMessageHistory([
                        'limit' => 50,
                        before' => $message,
                    ])->then(function ($message) {
                        echo "Messages {$message->content}\r\n";
                    })->otherwise(function ($reason) {
                        echo "Error:" . $reason;
                    });
                }`

When executed this error is al that appears

exception 'Exception' with message 'Chunk length header longer then 1024 bytes' in C:\xampp\htdocs\Stormrage\vendor\react\http-client\src\ChunkedStreamDecoder.php:93

I have tried everything and yet nothing seems to work. I thought it was my code at first but another dev suggested I open a ticket here.

**Comment by uniquoooo** [comment]
@lordraz0r Can you update to the latest `develop` branch, this is a known issue.

**Comment by lordraz0r** [comment]
I have done that and that fixed it thanks a lot.
