### ISSUE TITLE
Fatal error: Call to a member function getBody() on null in \var\www\DiscordPHP\vendor\team-reflex\discord-php\src\Discord\Http\Http.php on line 173

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [teamreflex/DiscordPHP#175]
Hi im getting the following error when sendMessage is called to quickly after the previous command:

`Fatal error: Call to a member function getBody() on null in \var\www\DiscordPHP\vendor\team-reflex\discord-php\src\Discord\Http\Http.php on line 173`

It might be that my internet is just slow. But eitherway then it shouldnt give back a error and end the script.

**Comment by uniquoooo** [comment]
Strange, I can't reproduce this error. How many times has this happened?

**Comment by ILLuMiNaTe7** [comment]
100% reproducible when sending to many messages at the same time. It seems to be a problem in Guzzle.

And no the message is not posted in the chat. It simply ends the script displays the error above

**Comment by baileyherbert** [comment]
Have this issue as well, same circumstance. Just spam a bunch of messages rapidly and the platform totally breaks.

**Comment by davidcole1340** [comment]
Line 173 occurs in the blocking request block. I am closing this issue due to age and the fact that I can't reproduce. The send message function doesn't use `HttpDriver::blocking`.
