### ISSUE TITLE
Using custom cache adapter cause a fatal error

### ISSUE THREAD

**Issue by Xety** [teamreflex/DiscordPHP#176]
I'm triyng to use a custom cachePool and i get always the same error :
```php
PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/Sites/DiscordPHP-Bot/vendor/cache/filesystem-adapter/FilesystemCachePool.php:127
```
I have tried with :
* [Apcu](https://github.com/php-cache/apcu-adapter)
* [Memcached](https://github.com/php-cache/memcached-adapter)
* [Redis](https://github.com/php-cache/redis-adapter)
* [Filesystem](https://github.com/php-cache/filesystem-adapter)

And i get the same error as mentionned before for all those adapters.

PHP 7.0.12

**Comment by uniquoooo** [comment]
Thanks, I'll look into it.

**Comment by dyanakiev** [comment]
I use memcached like this:

```php
$cache = new Memcached();
$cache->addServer('127.0.0.1', 11211);`
...
$myCacheKey = 'sdfsdf';
$row = $cache->get($myCacheKey);

if (!$row) {
$row = '..';
$cache->set($myCacheKey, $row, 150);
 }
return/echo $row;
```
Works perfect!

**Comment by Xety** [comment]
@dyanakiev Yeah but i mean, when i use it as a default `cachePool` option in the Discord class. Not in my personnal application.

**Comment by davidcole1340** [comment]
Custom caches will likely be removed. Please just use the default for now.
