### ISSUE TITLE
updatePresence not working

### ISSUE THREAD

**Issue by gsfordham** [teamreflex/DiscordPHP#178]
Does anyone know why the updatePresence() function doesn't work?
I even tried literally copying and pasting what's on the site
```php
$game = $discord->factory(Game::class, [
    'name' => 'i am playing a game!',
]);

$discord->updatePresence($game);
```
Did the function change in any of the new updates?
or is there a specific place you're supposed to put it in?
I was putting it in $discord->on('ready'

**Comment by uniquoooo** [comment]
Works for me, make sure you import the `Game` class with `use Discord\Parts\User\Game;` at the top of your file.

**Comment by gsfordham** [comment]
Thanks, that was what the problem was!
Perfect! This might even solve some of the other issues I was having. I wasn't important libraries like that.
