### ISSUE TITLE
sendMessage to user not working

### ISSUE THREAD

**Issue by gsfordham** [teamreflex/DiscordPHP#179]
I've been trying to get this to send to users, but $message->author->sendMessage() doesn't work; $message->author->user->sendMessage(); $message->author->user->User::sendMessage(); $message->author->User::sendMessage().
```php
case preg_match("/[\$][\.]msg/", $incomingMsg) == true:
					$message->author->sendMessage("Hi");
```
I tried including a number of libraries, as per a previous issue I had, but I don't know if I'm missing one, or if there's a different way I'm supposed to be calling this altogether.

These are the libraries I've included:
```php
use Discord\Discord;
use Discord\Parts\User\Game;
use Discord\Parts\Channel\Message;
use Discord\Parts\User\User;
use Discord\Cache\Cache;
use Discord\Parts\Channel\Channel;
use Discord\Parts\Part;
use React\Promise\Deferred;
```

Thanks, I really appreciate any help

**Comment by uniquoooo** [comment]
Are you sure those `case` statements work? Pretty sure that's not how you use a `switch` statement.

**Comment by gsfordham** [comment]
Yeah, that case is located within a switch, but there's so many cases, I just pulled the rest out of my post.
Right now, it just sends a message to the channel it was commented from saying the feature isn't implemented yet.

The case itself does function, in other words, but by calling anything like $message->author->sendMessage(), the case crashes on that run through, and anything in the case after that statement does not occur.

**Comment by Brugle** [comment]
Why don't you use:
$message->reply("Hi");

**Comment by gsfordham** [comment]
I want to be able to send some kind of private messages using the bot. I don't want it to be limited to the channel it's in. Like other bots can personally greet new people when someone joins.

Although that's not what this does, this is just one of the things I want it to do. It does actually reply if you send it a private message, but I want it to be able to get a DM channel with any user without having to require the users to do extra work

**Comment by lethak** [comment]
I used to have this, but seems like its not working anymore

```
	/**
	 * @param User|Member $author
	 * @param string $replyText
	 * @return $this
	 */
	public function sendPrivateText($author, $replyText)
	{
		if($author instanceof User)
			$author->sendMessage($replyText);
		if($author instanceof Member)
			$author->user->sendMessage($replyText);

		return $this;
	}
```

**Comment by davidcole1340** [comment]
As above you can't send a message to a `Member` object. You must reference the user attribute of the member, and then you can send a PM.
