### ISSUE TITLE
Is it possible to sendMessage once and after that keep listing?

### ISSUE THREAD

**Issue by android4682** [teamreflex/DiscordPHP#180]
Is there a way to send one message and after handling that one keep listing?

I've been googling, checking other tutorials (which there are almost none) for 8 hours. So time to ask :P

This is what I have right now

```
<?php

include __DIR__.'/../bin/vendor/autoload.php';

use Discord\Discord;

$discord = new Discord([
    'token' => 'bot-token',
]);

$discord->on('ready', function ($discord) {
    $discord->on('message', function ($message, $discord) {

   	$guild = $discord->guilds->get('id', GUILD_ID);
       	$DiscordChannel = $guild->channels->get('id', CHANNEL_ID);
       	$DiscordChannel->sendMessage('message')->then(function ($message) {
        	echo "Message send".PHP_EOL;
       	});

    });

});

$discord->run();

?>
```

With this codes it sends 5 messages instead of one and I don't want to use die(); or exit(); since I want it to keep listing and send a message when someone else does.
Also there is like 0 documentation or explanation on how to use DiscordPHP but there is a good Issue system though :P

**Comment by Xety** [comment]
@android4682 You need to do a condition and test if the `author->id` is the bot :
```php
$discord->on('message', function ($message, $discord) {
    if ($discord->id === $message->author->id) {
        return;
    }

    //...
}
```

**Comment by android4682** [comment]
@Xety Thank you, that worked.
Sad that there isn't a good documentation or wiki. But great community though :)
