### ISSUE TITLE
Play mp3 from url

### ISSUE THREAD

**Issue by feronetick** [teamreflex/DiscordPHP#181]
I'm trying to play mp3 file from url. But i hear only noise. If i download file from this url and try play it with VoiceClient->playFile method then it's work. Can i play this file from stream? Sorry for my broken english.

```
$this->discord->getVoiceClient($channel->guild_id)->then(
    function (VoiceClient $client) use ($bot, $channel, $url, $message) {
				
        $client->setVolume(30);

        $resource = fopen($url, 'r');

        $client->playRawStream($resource)->then(function () use ($bot, $channel, $message) {
            //...
        }, function (\Exception $e) use ($bot, $channel, $message) {
            //...
        });;
});
```

**Comment by duwayy** [comment]
Check if fopen is allowed in your php config

**Comment by Shadowfied** [comment]
Is this actually supposed to work?

**Comment by eDroiid** [comment]
i tried using ```fopen``` too.. and ```playRawStream``` it made a hiss/scratching noise.

**Comment by davidcole1340** [comment]
`VoiceClient::playRawStream()` takes a stream of PCM16 _RAW_ music data. To play an MP3 from a stream you will neeed to convert it first into PCM16 with something such as FFMPEG.
