### ISSUE TITLE
While using bot = false

### ISSUE THREAD

**Issue by DuckyOfAwesome** [teamreflex/DiscordPHP#184]
PHP Notice:  Trying to get property of non-object in /folder/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php on line 29
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /folder/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php:29
Stack trace:
#0 /folder/vendor/team-reflex/discord-php/src/Discord/Discord.php(672): Discord\WebSockets\Events\PresenceUpdate->handle(Object(React\Promise\Deferred), Object(stdClass))
#1 /folder/vendor/team-reflex/discord-php/src/Discord/Discord.php(563): Discord\Discord->handleDispatch(Object(stdClass))
#2 [internal function]: Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#3 /folder/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#4 /folder/vendor/ratchet/pawl/src/WebSocket.php(71): Ratchet\Client\WebSocket->emit('message', Array)
#5 /folder/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(98): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message))
#6 /folder/vendor/ratchet/rfc6455/src/Messagi in /folder/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php on line 29

**Comment by AlphawolfWMP** [comment]
I've experienced the same error tonight. Any news on this?

**Comment by davidcole1340** [comment]
User accounts are not allowed by Discord. This feature will be removed and not maintained, sorry.
