### ISSUE TITLE
is possible to change limit message?

### ISSUE THREAD

**Issue by kack-kun** [teamreflex/DiscordPHP#188]
example:
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");
$message->channel->sendMessage("hey");

But only send 5

**Comment by uniquoooo** [comment]
```php
$sendMessage = function () use (&$sendMessage, $message) {
    $message->channel->sendMessage('hey')->then($sendMessage);
};
$sendMessage();
```
