### ISSUE TITLE
update member [status] and [game] fail

### ISSUE THREAD

**Issue by deoxis9001** [teamreflex/DiscordPHP#193]
Hello,
When I use "update presence" I have no worries.
But when I use
```
            $server = $this_data->discord->guilds->get('id', "idServer");
            $member = $server->members->get('id', "138325157025415169");
```
The variables are not updated.
```
$membre
   [status] => dnd
    [game] => Discord\Parts\User\Game Object
        (
            [name] => test
            [url] =>
            [type] => 0
        )

    [nick] => deoxis
```

presence update
  ```
  [status] => online
    [game] => Discord\Parts\User\Game Object
        (
            [name] => testa
            [url] =>
            [type] => 0
        )

    [nick] => deoxis
```
$member->game and $member->status no updated :/

**Comment by uniquoooo** [comment]
Use this to update presence: http://teamreflex.github.io/DiscordPHP/Discord/Discord.html#method_updatePresence

**Comment by deoxis9001** [comment]
I do not want to change it but just read it,
With the event "update presence" "status" and "game" are updated but when I read them from the guild it does not update

**Comment by deoxis9001** [comment]
I do not want to change it but just read it,
With the event "update presence" "status" and "game" are updated but when I read them from the guild it does not update

**Comment by deoxis9001** [comment]
hello
I still have the problem, how can I solve it ??

**Comment by Jaytks** [comment]
@deoxis9001 are you trying see what the bot's current game / presence is?

**Comment by davidcole1340** [comment]
Will need to look into this some more. I am assuming the problem is when the presense is changed and not updated in the guild?

**Comment by davidcole1340** [comment]
Fixed earlier today in the `develop` branch. Still need to do some testing when updating the bot presence.
