### ISSUE TITLE
$message->author->bot always returns NULL

### ISSUE THREAD

**Issue by BenjaVR** [teamreflex/DiscordPHP#197]
If I want to check wheter an author of a message is a bot or not, the boolean always returns NULL.

I use following piece of code:
```php
$discord->on('ready', function ($discord) {
    print('ready');
    echo "Bot is ready!", PHP_EOL;

    $discord->on('message', function ($message, $discord) {
        var_dump($message->author->bot);
        $message->channel->sendMessage('test');
    });
});
```
Is this a bug, or am I doing something wrong?

**Comment by BenjaVR** [comment]
I had to do
```php
$message->author->user->bot
```
to get 'true' if it is a bot. Real accounts still return NULL on this, don't know if this is by purpose.

**Comment by sciencefyll** [comment]
This differs if its private messaging as you won't have an user key in author.
