### ISSUE TITLE
How to get id voice channel?

### ISSUE THREAD

**Issue by aquaminer** [teamreflex/DiscordPHP#198]
How to get id voice channel?

**Comment by duwayy** [comment]
```
$guild   = $discord->guilds->first();
$channel = $guild->channels->get('name', 'YOUR CHANNEL NAME');
```

**Comment by opkiler22789** [comment]
@duwayy PHP Fatal error:  Call to a member function first() on null in /root/discordbot/main.php on line 48

**Comment by duwayy** [comment]
I'm running this code without errors
```
//at this point discord instance is already created
$discord->on('ready', function () use ($discord, $channel) {

		$guild   = $discord->guilds->first();
		$channel = $guild->channels->get('name', 'Music Channel');
```

**Comment by opkiler22789** [comment]
@duwayy PHP Catchable fatal error:  Argument 1 passed to Discord\Discord::joinVoiceChannel() must be an instance of Discord\Parts\Channel\Channel, null given, called in /root/discordbot/main.php on line 58 and defined in /root/discordbot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 1032

58:  $discord->joinVoiceChannel($channel)->then(function (VoiceClient $vc) use ($channel) {

$сhannel corresponds to what you wrote earlier

**Comment by duwayy** [comment]
You have a problem with your bot, it does not connect to vocal channel. Test this code to be sure a channel is retrieved before attempting to pass $channel

```
$discord->on('ready', function () use ($discord, $channel) {
	
		$guild   = $discord->guilds->first();
		$channel = $guild->channels->get('name', 'YOURCHANNELNAME');
		$discord->joinVoiceChannel($channel)->then(function (VoiceClient $vc) {
    echo "Joined voice channel.\r\n";

}, function ($e) {
    echo "There was an error joining the voice channel: {$e->getMessage()}\r\n"; 
});
```

**Comment by davidcole1340** [comment]
Closing due to age.
