### ISSUE TITLE
registerCommand aliases not working

### ISSUE THREAD

**Issue by Shadowfied** [teamreflex/DiscordPHP#199]
So I tried following the docs which say:
`$discord->registerCommand('hi', ['hey', 'hello', 'wussup'], ['aliases' => ['hey', 'hello', 'wassup']]);`

which wont work and throws
`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Discord\Parts\User\Client' does not have a method 'addCommandAlias' in /files/Bot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 1340`

Are the docs outdated, or am I doing something wrong, or missing something?
Thanks

**Comment by uniquoooo** [comment]
The issue has been fixed on the `develop` branch, can you do `composer require team-reflex/discord-php dev-develop` and see if it works.

**Comment by Shadowfied** [comment]
@uniquoooo I changed to the develop branch, but now I can't seem to use DiscordCommandClient.

`use Discord\DiscordCommandClient;

$discord = new DiscordCommandClient([
    'token' => '***',
]);`

right?

**Comment by baskettcase** [comment]
Yeah aliases not working on main branch. I tried moving to develop, but got the same error as above so quickly switched back.

**Comment by baskettcase** [comment]
Any fixes for this?

**Comment by baskettcase** [comment]
So yeah I just went in and fixed this the line that @Shadowfied was talking about in the warning "addCommandAlias" I changed to "registerAlias" and now everything works just fine. This is line 157 in DiscordCommandClient.php
