### ISSUE TITLE
$message->author sometimes NULL

### ISSUE THREAD

**Issue by coolmodi** [teamreflex/DiscordPHP#201]
Stragely it only happens on one of the 2 servers the bot is running on, the one with the problem has nearly 400(+hidden ones) online users, the other only a handful (a testserver). 

Could narrow it down to a problem with hidden users.
Tested it like that: Created a new discord acc, joined both servers, set myself to hidden, started bot and then wrote in both servers. Small testserver had proper author object, big server had just null. If I'm online from the start it works on both!

I worked around it for now by always checking is_object($message->author) first, but that's not a good solution. As it works on one but not the other I don't know if this is a Discord bug, or if it's DiscordPHP. Is that maybe what the largeGuild stuff in the code is for? Couldn't find any documentation for that.

Edit: Even with checks for object the bot sometimes shuts down without error if such a NULL person writes in chat :/

**Comment by coolmodi** [comment]
So I added the 'loadAllMembers' => true option to startup which seems to have fixed the problem, without it would often run into a segmentation fault!

Is this intended or should there be a way to load memebers on demand?

**Comment by uniquoooo** [comment]
This is the only fix, you have to load members for large guilds (>100 members I think).

**Comment by coolmodi** [comment]
This problem was fixed that way, but I may have found another similar one. Anyways, this can be closed.
