### ISSUE TITLE
$message->channel->is_private always returning true (guild, name, etc.., as a result, returns null)

### ISSUE THREAD

**Issue by donkkill13** [teamreflex/DiscordPHP#204]
I am currently using `PHP 7.0.13-0` on `Ubuntu 16.04 LTS`.

I found the problem and it's inside of `\Parts\Channel\Message.php`, the function
```
public function getChannelAttribute()
{
	foreach ($this->discord->guilds as $guild) {
		if ($guild->channels->has($this->channel_id)) {
			return $guild->channels->get('id', $this->channel_id);
		}
	}
	if ($this->cache->has("pm_channels.{$this->channel_id}")) {
		return $this->cache->get("pm_channels.{$this->channel_id}");
	}
	return $this->factory->create(Channel::class, [
		'id'   => $this->channel_id,
		'type' => Channel::TYPE_DM,
	], true);
}
```

in the if statement inside of the foreach, the function being called `->has($this->channel_id)` is returning false for some reason, so to fix it I just replaced it with `!empty($guild->channels->get('id', $this->channel_id))` as a temporary solution.

![image](https://cloud.githubusercontent.com/assets/25333083/22444109/928e8016-e70f-11e6-8737-2be17d93d554.png)
![image](https://cloud.githubusercontent.com/assets/25333083/22444114/9738b3d4-e70f-11e6-85e2-92172dee9bb8.png)

**Comment by davidcole1340** [comment]
I have no problems when using the develop branch. Closing due to age.
