### ISSUE TITLE
Voice channel members not refreshing when they move channels.

### ISSUE THREAD

**Issue by donkkill13** [teamreflex/DiscordPHP#206]
Here's an example:

![image](https://cloud.githubusercontent.com/assets/25333083/22578712/ca669484-e998-11e6-95ca-8e1be37b76f1.png)

The code I use to get the voice channel that the message author is in is:
```
$voicechannels = $this->message->channel->guild->channels->getAll('type', 2);
foreach ($voicechannels as $channel)
{
	if (!empty($channel->members->get('user_id', $this->message->author->id)))
	{
		//return $channel;
		print_r($channel->members);
	}
}
```

I commented out the return to see that I was, in fact, being inside two different channels.

**Comment by davidcole1340** [comment]
Fixed earlier today on the `develop` branch. Closing due to age.
