### ISSUE TITLE
Can't Connect (websocket closed op: 0)

### ISSUE THREAD

**Issue by DanielGrimm** [teamreflex/DiscordPHP#208]
Hello,

I've tried running my run.php using two computers and two connections now yet I still receive the same error:

`discordPHP.WARNING: websocket closed {"op":0,"reason":"websocket error"} []`

This is the gateway it's trying to connect to:

```wss://gateway.discord.gg/?v=6&endconding=json```

The one PC I used is running windows 7 and the other PC is windows 10.
I am using PHP 7.

This is what the "run.php" looks like:

```
<?php

include __DIR__.'/vendor/autoload.php';

$discord = new \Discord\Discord([
    'token' => '******************',
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready.", PHP_EOL;

    // Listen for events here
    $discord->on('message', function ($message) {
        echo "Recieved a message from {$message->author->username}: {$message->content}", PHP_EOL;
    });
});

$discord->run();
```

Any help would be appreciated.

Kind regards,
Daniel

**Comment by ScrummerLP** [comment]
@DanielGrimm Hay there, I've got the same error and after a bit of searching and asking the community it seems like a problem of a library that discord-php uses (https://github.com/reactphp/dns/issues/44). It's only concerns Windows 10 users and its exactly the error you got. So you might check out the issue I've linked and wait until this DNS thing got fixed. You can also try to run your script on an external machine like a server or in a docker container.

**Comment by DanielGrimm** [comment]
@ScrummerLP Thank you for letting me know. I'm going to to try and run the script on a external linux server and see if that helps. Also, I changed the buffer size to null and that seemed to fix it on the Win7 PC.

**Comment by halesyy** [comment]
I'm using Windows 7 and I just got the error as well. Running my bot from local CLI

**Comment by jhmckimm** [comment]
@halesyy Here's how to change the buffer size: https://github.com/reactphp/dns/issues/44#issuecomment-279296234

**Comment by lethak** [comment]
Same for https://github.com/teamreflex/DiscordPHP/issues/151
It seems to be fixed here https://github.com/reactphp/dns/releases/tag/v0.4.6

**Comment by scrummerlp** [comment]
Thx good to know!
When I get the time I might integrate it into this library... ^^

**Comment by davidcole1340** [comment]
AFAIK this has been fixed with reactphp/dns. I still need to update to the fixed version in the code.
