### ISSUE TITLE
Voice Recieving

### ISSUE THREAD

**Issue by uniquoooo** [teamreflex/DiscordPHP#21]
Need to start on receiving voice. Ideally convert to PCM16 with DCA. (i need u @bwmarrin)

**Comment by bwmarrin** [comment]
hahah. hmn, okay.. let me think how I would do this.

Receiving is going to be more difficult.  You need a separate opus decoder for each person/bot that is talking.  So if you've got 12 people in a channel chatting away, you need 10 decoders running and for opus to work right (as I understand) they need to remain active the entire time each person/bot is in the channel - or at least speaking..

**Comment by uniquoooo** [comment]
@bwmarrin Would we be able to just use FFmpeg with libopus?

**Comment by bwmarrin** [comment]
No, I don't think it would support the raw opus data that you receive from Discord.

**Comment by uniquoooo** [comment]
Kinda-implemented, able to receive Opus. Waiting on DCA rewrite for decoding.
