### ISSUE TITLE
$member->addRole() segmentation fault on bigger server

### ISSUE THREAD

**Issue by coolmodi** [teamreflex/DiscordPHP#213]
Hi, I have another problem with similar background.

This time it's about adding a role to a user for mute, and it works fine on test discord (5 users) but causes a segmentation fault (and never applies the role) on the server with ~2000 members.

```	
	$member = $guild->members[272799285xxxxxxxxxx];
	$role = $guild->roles->get("name", "Muted");
	$member->addRole($role);
	print_r($member);
        $guild->members->save($member);
```
This will print member with the added role and then crash with segmentation fault on big server. Crash also happens without saving and print_r(). It already is caused by addRole()!

PHP version: 7.0.15

**Comment by coolmodi** [comment]
It may be important that it may not instantly crash, sometimes it even takes as much as 10-20 seconds, but it will always sonner or later crash after addRole(). Issuing ->save() afterwards will make it crash instantly most of the time though!

**Comment by coolmodi** [comment]
The crash is caused by missing permissions! (Bot role was set below Muted role by admin...)
On small server it just does nothing in that case, on big it self destructs :)

This should maybe be fixed ;)

**Comment by donkkill13** [comment]
Next time for an error, just do `$guild->members->save($member)->then(function () {//success}, function ($e) {print_r($e->getMessage());});` for the error/issue, also I know sometimes that print_r() will cause a segmentation fault when used on a member/guild (I found that out when I had a command that would just print_r() a guild, then it would do a segmentation fault a couple seconds afterwards, then I removed the print_r() and it didn't fault)

Segmentation faults are weird though, I never figured out why it would happen lol

**Comment by davidcole1340** [comment]
Interesting. Should not cause a segfault. I don't have a big enough server to test on unfourtunately. Are you handling errors through promises? Closing due to age.
