### ISSUE TITLE
$message->channel->sendMessage gets 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by tucow** [teamreflex/DiscordPHP#218]
Hey guys,

I've been playing around with DiscordPHP, getting the Bot onto a server, setting the current game etc.. but I can't get the bot to send any message.. I did read a lot but it seems to be smth nobody encountered before :/

Here's some sample code:
```php
<?php

include __DIR__.'/vendor/autoload.php';
use Discord\Discord;
use Discord\Cache\Cache;
use Discord\Parts\Channel\Channel;
use Discord\Parts\Channel\Message;
use Discord\Parts\Part;
use Discord\Parts\User\Game;
use Discord\Parts\User\User;
use React\Promise\Deferred;

$discord = new Discord([
  'token' => 'Bot xxxxxxxxxxxxx',
]);

$game = $discord->factory(Game::class, [
    'name' => 'Alexa',
]);

$discord->on('ready', function ($discord) use ($game) {
        echo "Bot is ready.", PHP_EOL;

        $discord->updatePresence($game);

        $discord->on('heartbeat', function () use ($discord) {
            echo "heartbeat called at: " . time() . PHP_EOL;
        });

        $discord->on('message', function ($message) use ($discord) {
            $guild_id = $message->channel->guild_id;
            $channel_id = $message->channel_id;
            $guild = $discord->guilds->get('id', $guild_id);
            $channel = $guild->channels->get('id', $channel_id);

            $channel->sendMessage('we async now')->then(function ($message) {
                echo "The message was sent!", PHP_EOL;
            })->otherwise(function ($e) {
                echo "There was an error sending the message: {$e->getMessage()}", PHP_EOL;
                echo $e->getTraceAsString() . PHP_EOL;
            });

            echo "Recieved a message from {$message->author->username}: {$message->content}", PHP_EOL;
        });
});

$discord->run();
```

Sadly the above produces the same erro as $message->channel->sendMessage('test') does..

This is the response:
```Bot is ready.
Recieved a message from tucow: test
There was an error sending the message: Error code 401: There was an error processing the request. UNAUTHORIZED - {"code": 0, "message": "401: Unauthorized"} - channels/xxxxxxxxxxxxxxxx/messages
```

So the bot does receive messages and tries to send but I have no clue how I should handle the 401, looks like the auth header is missing? Any idea how to fix this? 

I'm using PHP 5.6.30-0+deb8u1

**Comment by benharri** [comment]
Does your bots presence get updated? I wasn't able to get `$discord->factory()` to return a Game object...

Might be worth trying it without updating the presence. I haven't had any problems if I don't set that.

**Comment by tucow** [comment]
@benharri yes, it does get updated, it actually was a first try :D

I just can't figure out why the heckmy sendMessage get a 401..

**Comment by donkkill13** [comment]
$discord = new Discord([
  'token' => 'Bot xxxxxxxxxxxxx',
]);

should be

$discord = new Discord([
  'token' => 'xxxxxxxxxxxxx',
]);

for user tokens you would do

$discord = new Discord([
  'token' => 'xxxxxxxxxxxxx',
  'bot' => false
]);

**Comment by tucow** [comment]
@donkkill13 damn.. thanks 🙄 I did put it infront because at first it didn't connect, but then with the Bot infront of the token it did also this is according to the Discords Api but anyhow now it works, thanks a lot!

**Comment by donkkill13** [comment]
np :D
