### ISSUE TITLE
Crash with user account (not bot user)

### ISSUE THREAD

**Issue by Whaxion** [teamreflex/DiscordPHP#220]
My bot crash after a certain time (not instantly but I don't know when exactly and I know that's not when I made an action line chat command)

I have this error:
```Fatal error: Call to a member function get() on null in /home/minesylv/discordPHP/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php on line 29```

Could you resolve it ?
Thanks ! :)

PS:
This is my code
```php
<?php

include __DIR__.'/vendor/autoload.php';

use Discord\Discord;
use Discord\Parts\User\Game;

$discord = new Discord([ 'token' => 'my_token', 'bot' => false ]);

$discord->on('ready', function($discord){
	global $discord;
	echo "Bot is ready.", PHP_EOL;
	$discord->on('message', function($msg) {
		//Some actions
	});
});

$discord->run();
```

**Comment by donkkill13** [comment]
I fixed it in my PR request

**Comment by uniquoooo** [comment]
As @donkkill13 said, use his version for the time being. I still need to review it however, that is why I haven't merged it.

Be aware, Discord does not allow self bots so you may be banned.
