### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by jaspervdm** [teamreflex/DiscordPHP#221]
Hello,

In my project I am using v4.0.3, and am trying to add an `Embed` to a message. As a test, I have the following code:
```PHP
$discord->on("message", function (Message $message, Discord $discord) {
  $this->logger->debug("Received message");
  $embed = $discord->factory(Embed::class, [
    "title" => "SomeTitle",
    "description" => "SomeDescription",
    "footer" => null,
    "image" => null,
    "thumbnail" => null,
  ], false);

  $message->channel->sendMessage("", false, $embed)->then(function () {
    $this->logger->info("Embed sent");
  }, function (Exception $e) {
    $this->logger->warning("Embed failed to send: ".$e->getMessage());
  });
});
```

The "Received message" shows up in my log, but neither the `onFulfilled` nor the `onRejected` get triggered. The embed also never shows up on Discord. I was wondering, am I doing something wrong the creation of the `Embed` object? I tried different variations, such as leaving out the `footer`, `image`, `thumbnail`, but that just gives me a bunch of warnings that those fields are not set.

Thanks for your help.

**Comment by benharri** [comment]
Try it on the develop branch

**Comment by jaspervdm** [comment]
Thanks, it works on that branch!

**Comment by duwayy** [comment]
er, it does not work for me in develop branch... no error, no warning, creating embed seems to crash the process and everyting after gets ignored, then rest of the script is read correctly
