### ISSUE TITLE
Guild->members->get('id', ID) returns incorrect member with correct User-part

### ISSUE THREAD

**Issue by Inkromind** [teamreflex/DiscordPHP#222]
I have created a simple bot using the commandClient. Whenever I try to get a member, it returns a Member-part where the data belongs to a different member but the user-part is correct.

Example script:

```
use Discord\DiscordCommandClient;
use Discord\Parts\Channel\Message;

class SimpleBot {

	private $commandClient;

	public function __construct() {
		$this->commandClient = new DiscordCommandClient([
			'token'  => DISCORD_BOT_TOKEN,
			"prefix" => "!",
			"discordOptions" => [
				"loadAllMembers" => true,
			]
		]);

		$this->commandClient->registerCommand("test", function(Message $message) {
			$author = $message->author;
			$authorPart = $message->channel->guild->members->get("id", $author->id);
			$message->reply("Your roles: " . substr(print_r($authorPart->roles, true), 0, 1900));
			$message->reply("Your nick: " . $authorPart->nick);
			$message->reply("Your user: " . print_r($authorPart->user, true));
		});

		$this->commandClient->run();
	}

}
```

When I execute !test, this is the result:

> @TheCainer, Your nick: OtherUser
> @TheCainer, Your user: Discord\Parts\User\User Object
> (
>     [id] => 23261234193207840
>     [username] => TheCainer
>     [avatar] => https://cdn.discordapp.com/avatars/232612341919907840/40667dac340eadaa79dddf51135fcaf.jpg?size=1024
>     [discriminator] => 2345
>     [bot] => 
> )
> 
> @TheCainer, Your roles: Discord\Helpers\Collection Object
> (
>     ROLES BELONGING TO OTHERUSER
> )

OtherUser seems to be the last user to have come online.

Using Guild->members->fetch(ID) does seem to return the correct user.

**Comment by valzargaming** [comment]
It doesn't look like this was ever fixed before this was project was abandoned.

**Comment by davidcole1340** [comment]
Just pushed an update to develop branch. `$message->author` is an instance of a Member object unless it is a private channel. You should then be able to access roles. Seems to be working fine with me. Closing due to age.
