### ISSUE TITLE
Member object null on GUILD_MEMBER_ADD

### ISSUE THREAD

**Issue by andersfylling** [teamreflex/DiscordPHP#224]
On a larger guild the $member object that comes as a argument on GUILD_MEMBER_ADD events, is null.

This does work on smaller guilds.
"loadAllMembers" is set to true.

**Comment by donkkill13** [comment]
Most likely they came online after calling the chunking, which the chunking will not grab the offline members I believe.

I should change my fork so that it'd store the members if they don't exist on a presence update..
