### ISSUE TITLE
Fatal error when using $discord->updatePresence();

### ISSUE THREAD

**Issue by pazuzu156** [teamreflex/DiscordPHP#225]
An error occurs when using the updatePresence() function to change the bot's presence:

```
Fatal error: Uncaught Error: Call to a member function send() on null in C:\Users\kklei\Desktop\phpbot\vendor\team-reflex\discord-php\src\Discord\Discord.php:942
Stack trace:
#0 C:\Users\kklei\Desktop\phpbot\vendor\team-reflex\discord-php\src\Discord\Discord.php(986): Discord\Discord->send(Array)
#1 C:\Users\kklei\Desktop\phpbot\index.php(20): Discord\Discord->updatePresence(Array)
#2 {main}
  thrown in C:\Users\kklei\Desktop\phpbot\vendor\team-reflex\discord-php\src\Discord\Discord.php on line 942
```

Following the stack trace, the issue is on line `942` in `Discord.php` pointing to `$this->ws->send($json);`

When this is called using `updatePresence()` it fails with this message, because the instance of `$this->ws` is null, and has not been instantiated upon this call.

**Comment by duwayy** [comment]
Looks like a not-yet-initialized $discord
Do you use $discord->on('ready', function ($discord) {
before doing updatePresence ?

**Comment by pazuzu156** [comment]
Huh, yeah that did it.
