### ISSUE TITLE
Call to a member function cancel() on null

### ISSUE THREAD

**Issue by TheMeq** [teamreflex/DiscordPHP#226]
Hi getting this error message a lot in my error_log, not sure what it means tho, but it's causing my bot to crash and auto-restart. 

`[31-Mar-2017 08:07:25 UTC] PHP Fatal error:  Uncaught Error: Call to a member function cancel() on null in C:\Users\root\Desktop\Toshihiro\vendor\team-reflex\discord-php\src\Discord\Discord.php:738
Stack trace:
#0 C:\Users\root\Desktop\Toshihiro\vendor\team-reflex\discord-php\src\Discord\Discord.php(564): Discord\Discord->handleHeartbeatAck(Object(stdClass))
#1 [internal function]: Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#2 C:\Users\root\Desktop\Toshihiro\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#3 C:\Users\root\Desktop\Toshihiro\vendor\ratchet\pawl\src\WebSocket.php(71): Ratchet\Client\WebSocket->emit('message', Array)
#4 C:\Users\root\Desktop\Toshihiro\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(104): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message))
#5 C:\Users\root\Desktop\Toshihiro\vendor\ratchet\rfc6455\src\Messaging\MessageBuffer.php(60): Ratchet\RFC6455\Messagin in C:\Users\root\Desktop\Toshihiro\vendor\team-reflex\discord-php\src\Discord\Discord.php on line 738
`

**Comment by davidcole1340** [comment]
Should be fixed on develop branch with the update of react event loop.
