### ISSUE TITLE
found a bug/typo in code

### ISSUE THREAD

**Issue by Keul125** [teamreflex/DiscordPHP#228]
in /src/Discord/Parts/Channel/Channel.php line 349 :

` isset($options['around'], $options['around']) `
should be
` isset($options['around'], $options['after'])`

**Comment by bkuhl** [comment]
Can you submit a pull request?

**Comment by Keul125** [comment]
Done :)

**Comment by davidcole1340** [comment]
Fixed in latest commit, thank you :)
