### ISSUE TITLE
Implement xsalsa20_poly1305 for voice

### ISSUE THREAD

**Issue by uniquoooo** [teamreflex/DiscordPHP#23]
Need to look into implementing `xsalsa20_poly1305` for encrypted voice. Currently using plain (no encryption).

Will require:
- libsodium
- libsodium-php

All are easy to install, shouldn't cause too much hassle.

**Comment by uniquoooo** [comment]
https://github.com/bwmarrin/discordgo/issues/133 ty skippy

**Comment by bwmarrin** [comment]
https://github.com/bwmarrin/discordgo/commit/85e06e3e8384c0b20960de2cdf3af54299db307a

There.  That's the commit with all the changes I had to make.  The issue has been updated too to point to each change per step.
