### ISSUE TITLE
Cannot get volume to work

### ISSUE THREAD

**Issue by mattigins** [teamreflex/DiscordPHP#230]
Is the below code supposed to work? All it says in the docs is that the client cannot be set to speaking, which is why it sets speaking to false before changing the volume..

This kind of works but it only sets the volume when i play another file.

> $vc->setSpeaking(false);
$vc->setVolume($volume);
$vc->setSpeaking(true);
$message->channel->sendMessage('Volume set to '.$volume.'%');

**Comment by davidcole1340** [comment]
The volume cannot be changed when the song is already playing as it is set when the opus encoding has started. Possibly this is your issue? Otherwise, you are not catching errors from the promises which could have more information. Closing due to age.
