### ISSUE TITLE
Cannot get sendMessage to work in an addPeriodicTimer

### ISSUE THREAD

**Issue by zacxi** [teamreflex/DiscordPHP#231]
I am trying to make a socket work. I have used addPeriodicTimer. The socket is working, but I am not able to send a message. Here is my code: https://pastebin.com/4WzHgp0W The line 63 works. I am calling exactly the same function at line 111 and nothing outputs. No errors show up either.
Thanks

**Comment by pazuzu156** [comment]
What are the sockets for? And why the use of the global keyword everywhere?

**Comment by zacxi** [comment]
Sockets are for an application I use. I am novice at PHP. Sorry if global keywords are redundant.

**Comment by davidcole1340** [comment]
Code is no longer on pastebin so I can't see. I have tested sending a message in a timer and it works fine. Closing due to age.
