### ISSUE TITLE
Sending a message via a function

### ISSUE THREAD

**Issue by zzyzzyzzx** [teamreflex/DiscordPHP#232]
So i am trying to send a message from within a function:

function HsendMsg($chan,$msg){
    $guild=$discord->guilds->get("id","305178054312067082");
    $channel = $guild->channels->get("id",$chan);

    $channel->sendMessage($msg)->then(function ($message) {
        echo "The message was sent!", PHP_EOL;
    })->otherwise(function ($e) {
        echo "There was an error sending the message: {$e->getMessage()}", PHP_EOL;
        echo $e->getTraceAsString() . PHP_EOL;
    });
}

cant seem to get it working always gives me an error

here is the full code:
https://pastebin.com/1k9nJiin

edit: for some reason code tags is not working

**Comment by benharri** [comment]
Looks like your `$discord` object isn't available inside your function.
You could add `global $discord;` at the top of the function to get it working, but that's considered bad style.

**Comment by zzyzzyzzx** [comment]
even with that i get:

PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/Tao/DCBOT/Discord.php:32
Stack trace:
#0 /var/www/Tao/DCBOT/Discord.php(42): HsendMsg('305178054312067...', 'its alive!')
#1 {main}
  thrown in /var/www/Tao/DCBOT/Discord.php on line 32

**Comment by benharri** [comment]
```
function HsendMsg($discord, $chan, $msg){
    $discord->guilds->get('id','{my guild id}')->channels->get('id', $chan)->sendMessage($msg)->then(function ($message) {
        echo "The message was sent!", PHP_EOL;
    })->otherwise(function ($e) {
        echo "There was an error sending the message: {$e->getMessage()}", PHP_EOL;
        echo $e->getTraceAsString() . PHP_EOL;
    });
}
HsendMsg($discord, $channel, $msg);
```
try this

**Comment by zzyzzyzzx** [comment]
still getting the null error, any idea about that?

**Comment by zzyzzyzzx** [comment]
#225 -- used this to fix null issue

thanks for the help :)
