### ISSUE TITLE
Calling bot files from another file

### ISSUE THREAD

**Issue by zzyzzyzzx** [teamreflex/DiscordPHP#233]
This one is a bit more complex than my last question

basically i have my discord bot file -> Discord.php

I also have a worker.php file this is for a message queue. basically im trying to use this queue to update discord, but it does not seem to be working

this is worker.php:
https://pastebin.com/VUi2n1UU

again this is my discord.php (has a bit of changes)
https://pastebin.com/1k9nJiin

I even tried to do a require/include for a separate include that i use to use for the discord.php

im out of ideas, i can get the webpage for my updates to update my worker to update my CLI worker, but i cant seem to get it to send to discord now

edit this is what my 3rd page looks like, but i have not been using it:

`function HsendMsg($chan, $msg){
    $discord = new DiscordCommandClient([
        'token' => 'xxx',
        "prefix" => "^",
    ]);

    $discord->on('ready',function($discord) use ($chan,$msg) {
        echo "startup ready fired!";
        $discord->loop->addPeriodictimer(1,function() use ($chan,$msg,$discord) {
            echo "startup loop fired!";
            $discord->guilds->get('id', '305178054312067082')->channels->get('id', $chan)->sendMessage($msg)->then(function ($msg) {
                echo "The message was sent!", PHP_EOL;
            })->otherwise(function ($e) {
                echo "There was an error sending the message:";
            });
        });

    });
}`

**Comment by davidcole1340** [comment]
I'm not sure what this is asking sorry. Closing due to age.
