### ISSUE TITLE
'Discord\Parts\Channel\Embed missing

### ISSUE THREAD

**Issue by Keul125** [teamreflex/DiscordPHP#235]
PHP Fatal error:  Class 'Discord\Parts\Channel\Embed' not found in MYPERSONALFOLDER/vendor/team-reflex/discord-php/src/Discord/Factory/Factory.php on line 73

Wot this error while using $channel->getMessageHistory($opts); on a channel that contained a pastebin link with embed preview.

**Comment by benharri** [comment]
`Discord\Parts\Embed\Embed`

**Comment by davidcole1340** [comment]
Has been fixed on the develop branch.
