### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by parapauk** [teamreflex/DiscordPHP#238]
Hi,

I have set it up as per the instructions and registered a bot with discord. I put the bot's auth token into the bot.php file as per the documentation, but when it runs I get the following:

`PHP Fatal error:  Uncaught exception 'Discord\Exceptions\DiscordRequestFailedException' with message 'Erorr code 401: There was an error processing the request. UNAUTHORIZED - {"code": 0, "message": "401: Unauthorized"} - users/@me' in /root/vendor/team-reflex/discord-php/src/Discord/Helpers/Guzzle.php:212`

Can anyone advise please?

**Comment by benharri** [comment]
Looks like your token is invalid or you have it registered wrong. Double check it and make sure it doesn't include "Bot " at the beginning

**Comment by parapauk** [comment]
Hi,

this is the code within my bot file:

<?php

include __DIR__.'/vendor/autoload.php';

$discord = new \Discord\Discord([
    'token' => 'MzA5NDQwNjc2ODc2MjU1MjMz.C-zIhQ._pdgWDDO4eOyzj5lIVjT2_lnLwg',
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready.", PHP_EOL;

    // Listen for events here
    $discord->on('message', function ($message) {
        echo "Recieved a message from {$message->author->username}: {$message->content}", PHP_EOL;
    });
});

$discord->run();

**Comment by pazuzu156** [comment]
Why are you sharing your bot token?

**Comment by parapauk** [comment]
Thanks, pazuzu for the assistance! Oh, wait. 
It's an old key.

**Comment by pazuzu156** [comment]
It's a serous question. You shouldn't share tokens.

**Comment by parapauk** [comment]
Sorry which part of my very serious answer didnt you get?

**Comment by shibdib** [comment]
Tokens in this case don't mean jack, simple to delete it or refresh it once he gets his answer. Provide some help to the actual issue or don't comment at all
