### ISSUE TITLE
Is DiscordPHP still active ?

### ISSUE THREAD

**Issue by duwayy** [teamreflex/DiscordPHP#241]
Hello
I see that most of issues remains unanswered..
Some weeks ago somebody asked for adding reactions features, which I think is quite important, but he did not get any answer, even not a "no"..

So, are there still people keeping this git up to date ?

Anyways, thanks to them for giving their free time developing this PHP wrapper ! I woud love had helped, but I don't have enough knowledge for now..

**Comment by Batch-Monger** [comment]
I think that this is dead

**Comment by Daijobou** [comment]
Is here a alternative?

**Comment by scrummerlp** [comment]
Have a look here: https://github.com/teamreflex/DiscordPHP/blob/master/README.md

This issue can be closed.

**Comment by SpeedyCraftah** [comment]
Ded

**Comment by SpeedyCraftah** [comment]
Owner too nub to make working lib

**Comment by garrettw** [comment]
Please stop posting useless comments.

**Comment by valzargaming** [comment]
DiscordPHP is dead, but you should look into carchive/Yasmin which is basically a bug-fixed version of DiscordPHP and has React built-in for times, so it has some level of async capabilities. You do have to be familiar with React's promises and timers, but this is a really easy concept. There are working examples of this available on valzargaming/Yasmin

**Comment by oliverschloebe** [comment]
Try [rocketmates/discord-php](https://github.com/rocketmates/discord-php) which I try to keep up-to-date.

**Comment by davidcole1340** [comment]
Library is dead at the moment. I am trying to get it up to a useable level but no promises.
