### ISSUE TITLE
 Undefined index: nick

### ISSUE THREAD

**Issue by falconlv** [teamreflex/DiscordPHP#242]
`PHP Notice:  Undefined index: nick in /***/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php on line 52
Stack trace:
  1. {main}() /***/run_bot.php:0
  2. Discord\Discord->run() /***/run_bot.php:277
  3. React\EventLoop\StreamSelectLoop->run() /***/vendor/team-reflex/discord-php/src/Discord/Discord.php:1229
  4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /***/vendor/react/event-loop/src/StreamSelectLoop.php:205
  5. call_user_func:{/***/vendor/react/event-loop/src/StreamSelectLoop.php:236}() /***/vendor/react/event-loop/src/StreamSelectLoop.php:236
  6. React\Stream\Stream->handleData() /***/vendor/react/event-loop/src/StreamSelectLoop.php:236
  7. Evenement\EventEmitter->emit() /***/vendor/react/stream/src/Stream.php:173
  8. call_user_func_array:{/***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
  9. Ratchet\RFC6455\Messaging\MessageBuffer->onData() /***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
 10. Ratchet\RFC6455\Messaging\MessageBuffer->processData() /***/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:60
 11. Ratchet\Client\WebSocket->Ratchet\Client\{closure}() /***/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:104
 12. Ratchet\Client\WebSocket->emit() /***/vendor/ratchet/pawl/src/WebSocket.php:71
 13. call_user_func_array:{/***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64}() /***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
 14. Discord\Discord->handleWsMessage() /***/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:64
 15. Discord\Discord->handleDispatch() /***/vendor/team-reflex/discord-php/src/Discord/Discord.php:564
 16. Discord\WebSockets\Events\PresenceUpdate->handle() /***/vendor/team-reflex/discord-php/src/Discord/Discord.php:673``

**Comment by AlphawolfWMP** [comment]
As a workaround I'm using

    'disabledEvents' => [
	    'PRESENCE_UPDATE'
    ]

which "solves" the issue for me.

**Comment by falconlv** [comment]
AlphawolfWMP, that helped.
Now another new issue came up:

[23-May-2017 20:32:18 UTC] PHP Fatal error:  Uncaught Error: Call to a member function push() on null in /***/bot/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/GuildCreate.php:99
Stack trace:
#0 /***/bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(673): Discord\WebSockets\Events\GuildCreate->handle(Object(React\Promise\Deferred), Object(stdClass))
#1 /***/bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(564): Discord\Discord->handleDispatch(Object(stdClass))
#2 [internal function]: Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#3 /***/bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#4 /***/bot/vendor/ratchet/pawl/src/WebSocket.php(71): Ratchet\Client\WebSocket->emit('message', Array)
#5 /***/bot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(104): Ratche in /***/bot/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/GuildCreate.php on line 99

**Comment by AlphawolfWMP** [comment]
If you're not listening on the GUILD_CREATE event, just disable it too:

    'disabledEvents' => [
	    'PRESENCE_UPDATE',
            'GUILD_CREATE'
    ]

**Comment by davidcole1340** [comment]
Has been fixed on the developer branch.
