### ISSUE TITLE
Can not send embeds even on develop branch

### ISSUE THREAD

**Issue by duwayy** [teamreflex/DiscordPHP#243]
I tried everything, complex to basics ways to send embeds, with and without develop branch, but it fails everytime... Normal messages are sent with no problem, but embed does not do nothing..

**Comment by marianoarga** [comment]
Try to send it as an array, I have never got it working as an Embed class:

```
$embed = array(
            "color" => 0,
            "author" => [
                "name" => "MAYBE BOT NAME",
            ],
            "title" => "**TITLE**",
            "description" => ""
                . "**BLA**\r\n"
                . "**BLA**\r\n"
            ,
            "thumbnail" => [
                "url" => "THUMBNAIL_url"
            ]
        );
```

$message->channel->sendMessage("", false, $embed);

**Comment by duwayy** [comment]
Perfect, thank you !
