### ISSUE TITLE
php cli

### ISSUE THREAD

**Issue by clonalejandro** [teamreflex/DiscordPHP#244]
<h2>Hi!</h2>
I did tested in three Different host,
 
for example:  http://clonalejandro.hol.es/bot/source/Main.php & 
[https://clonalejandro.me/bot/MinleyBot/source/Main.php](https://clonalejandro.me/bot/MinleyBot/source/Main.php)

<h3>My source</h3>

 
```php
include __DIR__.'/lib/vendor/autoload.php';
include __DIR__.'/assets/config.php';

use Discord\Discord;


/** SMALL CONSTRUCTORS **/

$discord = new Discord([
    'token' => $token,
]);


$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    $discord->on('message', function ($message, $discord) {
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
    });
});

$discord->run();
```

<h3>Directory</h3>

![tree](http://i.imgur.com/IWOrDYo.png)

**Comment by sirhypernova** [comment]
clonalejandro, you must  run the command through SSH: php main.php
