### ISSUE TITLE
addMember event

### ISSUE THREAD

**Issue by ambanane** [teamreflex/DiscordPHP#246]
How can I get the addMember event to work?

for the message event i do: 
`
$discord->on('message', function ($message) {
    echo $message->content;
});
`

But what can i do for the addMember event?

**Comment by marianoarga** [comment]
@ambanane whta do you want to acomplish? I dont really understand it, could you give some more details?

**Comment by ambanane** [comment]
Sure. Basically I want to replicate the welcome message that every other bot have. While I can very well use another bot for this task, I want to implement it into my own bot because I want to learn.
So, everytime a member joins or leaves, I want to trigger an event.

**Comment by marianoarga** [comment]
I see, you should use this instead:

> $discord->on('member_join_guild', function($member) {...
> $discord->on('member_left_guild', function($member) {...

**Comment by ambanane** [comment]
Oh there's this event huh? Nice, I will use it instead. Thank you for helping!

**Comment by sirhypernova** [comment]
Question though, how would you select a channel to send the message in?

**Comment by sirhypernova** [comment]
$message->channel->sendMessage() is selecting the channel the current message is in. If there is a way to get the list of channels (I know there is a way) then that could be used

**Comment by ambanane** [comment]
$message->guild->channels perhaps

**Comment by sirhypernova** [comment]
Perhaps, that could work

**Comment by marianoarga** [comment]
> $channels = $message->channel->guild->channels->getAll('type', 1);

I don't remember the types values, but I'm sure type 2 is **voice** channel, so type 1 must be **text**
From there you can select the text channel to send the message

**Comment by marianoarga** [comment]
Updated comment in order to use **member_join_guild**

**Comment by sirhypernova** [comment]
Alright, thanks. I'll try it out.

**Comment by sirhypernova** [comment]
Input: 

$channels = $message->channel->guild->channels->getAll('type', 1); echo var_dump($channels);

Output: 

object(Discord\Helpers\Collection)#12640 (0) {
}

**Comment by marianoarga** [comment]
discord/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Channel.php
@49

> class Channel extends Part
> {
>     const TYPE_TEXT  = 0;
>     const TYPE_DM    = 1;
>     const TYPE_VOICE = 2;
>     const TYPE_GROUP = 3;

My mistake, text is 0, 1 is Direct Message

**Comment by sirhypernova** [comment]
Ahh, ok

**Comment by sirhypernova** [comment]
Yep, worked perfectly

**Comment by sirhypernova** [comment]
member_join_guild does not appear to work at all. I set it up to echo when someone joins, and no output

**Comment by marianoarga** [comment]
Paste the code you are using

**Comment by VincentTeresa** [comment]
Hello,

I want to catch the event when the any user comes into the server for the first time and print a welcome message, i was looking for any doc to know the event who handles it but... i did't find it, 

i try with this : 

 ```
$this->discord->on('GuildMemberAdd', function ($member) {
                echo "joined";
            });
```

and

 ```
$this->discord->on('guild_member_add', function ($member) {
                echo "joined";
            });

```
and also 
```
 $this->discord->on('member_join_guild', function ($member) {
                echo "joined";
            });

```
but anything works... do you have any idea?

**Comment by billsmith37** [comment]
Sorry, its GUILD_MEMBER_ADD. You have to capitalize for some reason

**Comment by sirhypernova** [comment]
^^ yup, I don't know why. I did figure that out awhile ago

**Comment by VincentTeresa** [comment]
Thanks!!! It works so fine. 

Do you know how to retrieve the user id to name it on a channel i try this but... doesn't work...
```

 $this->discord->factory(Channel::class,[
                    'id' => 'XXXXXXXXXXXX'
                ])->sendMessage('Welcome <!@'.$member->user->id.'>');
                echo "joined";
```

**Comment by sirhypernova** [comment]
When you do on("blah", function ($member) {
Member is the member object

**Comment by sirhypernova** [comment]
To get the channel is slightly more annoying. When I'm on PC I can find what I did

**Comment by VincentTeresa** [comment]
Yep, i know @sirhypernova  but i ask to mention tthat user on the welcome message, something like "welcome @me"

**Comment by VincentTeresa** [comment]
i tried with this but... doesn't works ...

```
$this->discord->factory(Channel::class,[
                    'id' => 'XXXXXXXXX'
                ])->sendMessage('Welcome <!@'.$member->user->id.'>');
                echo "joined";
```

**Comment by sirhypernova** [comment]
Personally,  I used a foreach loop to get the correct channel
I think I did:
$channels = $member->guild->channels->getIterator();
foreach ($channels as $channel)  {
    if ($channel->id == $member->guild->id) {
        $channel->send("Welcome ".$member." to this amazing guild!");
    }
}

**Comment by sirhypernova** [comment]
And $this is for inside a class, not for using factory. Just do $discord->factory

**Comment by davidcole1340** [comment]
```php
$discord->on(\Discord\WebSockets\Event::GUILD_MEMBER_ADD, function ($member) {
...
});
```
I assume this still works.
