### ISSUE TITLE
Check new users and status

### ISSUE THREAD

**Issue by newQuery** [teamreflex/DiscordPHP#248]
Hi, I'm trying to check whevener a new user arrives on the server to echo out a message, and create logs.

Also, I want the bot to run a script every time a user gets "*Online*", is it even possible ?

Thanks

**Comment by marianoarga** [comment]
Continuously checking for every user status would be an overkill.
For "a new user arrives" into the server you shoul use **member_join_guild**

**Comment by ScrummerLP** [comment]
You can listen on the "GuildMemberAdd" Event. It's triggered when a new member joins on the server.
To run a script when a player comes online, you can listen on the "PresenceUpdate" Event. From the callback you can resolve the new presence-status (online, idle, dnd, invisible)

**Comment by davidcole1340** [comment]
#246
