### ISSUE TITLE
Can't edit newly created or renamed roles.

### ISSUE THREAD

**Issue by proxikal** [teamreflex/DiscordPHP#25]
Attempted to change role color after role creation.
tried it immediately to no success in finding the role.
Waited about 10-15 minutes and had the same issue..role was null.
About 30-45 minutes or so, the roll was found and edited correctly.
Not sure if this is just discord? but I figured you'd want to know about it.

Also if you edit the role name, it appears to do the same thing.
you have to wait the same amount of time before it's available to edit.

**Comment by uniquoooo** [comment]
Sorry, was this sorted in the Discord chat? Not sure

**Comment by proxikal** [comment]
I posted it in the chat, voltana moved it here. still not solved, have to wait up to an hour sometimes 2.

**Comment by uniquoooo** [comment]
Will take a look when I have some time 
On Mar 16, 2016 2:53 AM, Joshua Cleland <notifications@github.com> wrote:I posted it in the chat, voltana moved it here. still not solved, have to wait up to an hour sometimes 2.

**Comment by proxikal** [comment]
Just an update: I think it has something to do with the cache system in the roles? If i create a role it won't detect it, Restart the bot. and it works right away.

**Comment by uniquoooo** [comment]
Might be fixed in `bot-api`.

**Comment by uniquoooo** [comment]
@proxikal were you able to get this working? Pretty sure we resolved it, just wanted to make sure.
