### ISSUE TITLE
Adding role permissions to channel

### ISSUE THREAD

**Issue by antotor** [teamreflex/DiscordPHP#250]
Hello! I need to add read and write permission for role on channel, but i dont understand how make this.

I found method setPermissions(Part $part, $allow, $deny) but how create $allow and $deny variables?

**Comment by davidcole1340** [comment]
See the [API documentation](http://teamreflex.github.io/DiscordPHP/Discord/Parts/Permissions/RolePermission.html) for an idea on how to create a `RolePermission` object. You can then give the role permissions with `$role->permissions = $rolePermission`.
