### ISSUE TITLE
Listen to Channel that I joined?

### ISSUE THREAD

**Issue by magentoman2009** [teamreflex/DiscordPHP#251]
Can I use this to listen to a channel that I joined to receive updates? I don't own this server and only joined through an invite link.

https://discordapp.com/channels/301247799499030529/327874917372526613

**Comment by davidcole1340** [comment]
Compare the channel ID with the one you want. See the [API documentation](http://teamreflex.github.io/DiscordPHP/Discord/Parts/Channel/Message.html).
