### ISSUE TITLE
Library seems impossible to understand (unusable)?

### ISSUE THREAD

**Issue by frickenate** [teamreflex/DiscordPHP#258]
I'm either missing something, or this library is essentially impossible to learn or use efficiently. After connecting with the ready event, how is one to even begin accessing guilds and their channels? Had to look at source code just find out that the guild repository is assigned as `$this->guilds = new GuildRepository(...)` on the `Discord` class, with the `$guilds` property not even having been defined (let alone type-cast with phpdoc) on the class. So just to access a guild, one is having to use undocumented class properties defined at runtime.

This seems shocking to me, as the properties that *are* set on the class are well-typed and everything. As in, the library seems fairly well-written, but then falls apart as soon as you try to access the most basic functionality.

In this day and age where people use "real IDEs" that autocomplete everything for you, it *really* sucks that simply accessing `$discord->guilds` results in having to dig through source code. Have I missed something, or is user-friendliness of this lib that poor? :(

**Comment by frickenate** [comment]
Added the `$guilds` property myself with the proper type, but that just results in a never-ending hell of not being able to have the IDE autocomplete anything. Can't pick out a guild or channel by name without writing unacceptably complicated code to iterate manually, and takes adding `/** @var SomeClass $someObject **/` every couple lines of code.

I'm not trying to be an ass, but this is not how to write modern PHP. Moving on to the library.

**Comment by sirhypernova** [comment]
It's really quite simple. See the example..To respond to messages,  use the $discord->on() function. So on message,  do something.

**Comment by sirhypernova** [comment]
The ready event is not meant to interact with individual guilds and react to messages
