### ISSUE TITLE
Which Forks are the most developed?

### ISSUE THREAD

**Issue by baskettcase** [teamreflex/DiscordPHP#259]
Is there a form that has been developed further? Fixed aliases? etc? It seems like this one is dead, but if there is a fork that is still being developed I would like to know about it! :) Thanks!

**Comment by pazuzu156** [comment]
I haven't touched aliases (though for my bot I don't even use the aliases thing, I built my own alias system). I have made changes to permissions since new ones were added to discord. I'm thinking of just writing a new lib from the scratch as this one is very hard to understand.

**Comment by baskettcase** [comment]
Better documentation and examples with this library would be really helpful and fixing bugs like aliases etc, but yeah if you do write one.. I'd be happy to give it a go :)

**Comment by sciencefyll** [comment]
Please write it in php7.1 using typehinting as that would improve readability in the code af.

**Comment by sciencefyll** [comment]
Any progress on this btw?

**Comment by baskettcase** [comment]
Yeah I would still like to find a nice fork of this project. I did fix the alias thing, but that's basically a bandaid compared to a good fork :(

**Comment by sciencefyll** [comment]
Why don't we just create a new one from scratch?
Where we add typehinting, and keep the source code readable.

**Comment by garrettw** [comment]
I'm making one from scratch, and I've already forked it but I'm not targeting 7.1 yet. Plus I have no idea how fast I can work on it.

**Comment by r7l** [comment]
Thanks allot! It would be great if you could get your fork to be included in front page description and maybe you even get a couple more people to help you. I would like to join in as well as i don't want to see DiscordPHP dying. I am not sure how much i can add but i would try to help.

You mind linking your fork here?

**Comment by garrettw** [comment]
[garrettw/wiscord](https://github.com/garrettw/wiscord)
I call it that because W is for WebSockets, and the REST-only library is called restcord. And because the original name was lame and it sounded too official.

**Comment by sciencefyll** [comment]
Tbh I think constructor should be allowed to do work, as long as its for the object. like precalculations, potential caching. just not anything heavy, or complex.

**Comment by garrettw** [comment]
@sciencefyll Read [this article](http://misko.hevery.com/code-reviewers-guide/flaw-constructor-does-real-work/) and if you disagree with it, tell me what you disagree with and why -- because I'm always open to evolving my understanding.

**Comment by r7l** [comment]
I do applaud all your efforts but renaming it will likely cause issues. I don't see any problem with having this library called DiscordPHP as it displays it as a library for Discord using PHP. Most of the other languages have similar structured names, like DiscordJS, DiscordRB, DiscordGO, DiscordCR and so on. 

Why name it Wiscord? Even with your description, i don't see a relation.

When i was looking for the fork on your Github profile i already failed to find it because of that change. It should be a drop in replacement for current DiscordPHP.

**Comment by baskettcase** [comment]
I have to agree since I am now getting notifications from your fork and when I got the email I had to go see what project it was since I had no recollection of using something called wiscord. Once I looked at the project page I recognized it of course, but yeah I don't think it's a good idea renaming it.

**Comment by sciencefyll** [comment]
If you guys look at his code, you will see he is basicly rewriting this.
Its not DiscordPHP as DiscordPHP is a dead project. So seperating oneself
from a dead project is a good idea.
Ofc you don't recognize the name, it's new. It shouldn't be difficult to
learn it tho. Like come on.

There are other details that are much more important. Like how to rebuild
it. I'm sure he would love people to submit PR.

**Comment by garrettw** [comment]
@r7l Making it a drop-in replacement for DiscordPHP would require me to keep the old API intact, which I want the freedom to change. And keeping the old name would imply that I'm merely continuing the old project. What I'm doing is writing a completely new library with the old code at my side for reference (and copying, if useful).

**Comment by baskettcase** [comment]
Ah I see, ok, so not really a fork then, but a new project just referencing this project.

**Comment by r7l** [comment]
From the description i would assume the same thing. If your new project is gaining some more support and you're done with rewriting it, i'll review it and maybe i'll use it. For now i am not really looking for a rewrite but for a drop-in replacement with a couple fixes or additions to most recent changes of Discord API. 

To me DiscordPHP is not really dead apart of main developer dropped it. It is still working pretty good and i am using it 24/7 with my bot since a little more then a year now. I've seen other open source projects being abandoned before. Most of them got picked up at some point and survived.

**Comment by garrettw** [comment]
@r7l I understand what you would assume from the description. I just haven't cleared it all out yet as I haven't gotten around to writing a new one.

**Comment by luceos** [comment]
I've also been using this package to hook it into botman.io. But sadly with this project being dead I saw no other solution than creating a complete new bot toolkit inspired by this package.

It's not done yet, but feel free to start tracking progress at https://github.com/discodian !

It's meant for PHP 7.1+ and uses a lot of the Laravel components 5.5 (long term support). I plan on creating a simple extension system and an easier event listening system.

**Comment by oliverschloebe** [comment]
https://github.com/rocketmates/discord-php

**Comment by davidcole1340** [comment]
#241. All changes are on the `develop` branch.
