### ISSUE TITLE
How to read DM / PM (Direct Message / Private Message) ?

### ISSUE THREAD

**Issue by xmillies** [teamreflex/DiscordPHP#261]
Hi,

How to read DM / PM (Direct Message / Private Message) ?
No problem for guild & channel but impossible for DM/PM ?

How to do it ?

Regards.

**Comment by r7l** [comment]
To check if a message is DM, i use this:

`if($message->channel->guild_id === NULL)`

To send messages, i use this:

`$user->sendMessage($text);`

**Comment by xmillies** [comment]
Thanks.
I have no issue to send message to channel.
In fact I don't get notification or message from DM/PM using README exemple.
I have done : https://discordapp.com/oauth2/authorize?client_id=<CLIENT ID>&scope=bot (with my bot client ID).
With this I get message from channel but not DM/PM.
The url gives option to add guild / server to the bot.
I didn't find it for DM/PM.

**Comment by r7l** [comment]
Ok, i can't help you much with that actually. I do get messages on DM like every other message and i did setup the Bot the same way. Is there anything showing anywhere?

I use the common message event for it:

`$this->discord->on('message', function ($message) { /* CODE GOES HERE */ });`

**Comment by xmillies** [comment]
In logs I get : 

[2017-08-13 21:08:51] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
**[2017-08-13 21:08:52] DiscordPHP.INFO: did not parse private channels [] []**
[2017-08-13 21:08:52] DiscordPHP.INFO: stored guilds {"count":0} []
[2017-08-13 21:08:52] DiscordPHP.INFO: all guilds are now available {"count":3} []
[2017-08-13 21:08:52] DiscordPHP.INFO: loadAllMembers option is disabled, not setting chunking up [] []
[2017-08-13 21:08:52] DiscordPHP.INFO: client is ready [] []

I think the second line show my issue.

**Comment by xmillies** [comment]
With the option : 

`$discord = new Discord([
    'token' => 'my_token....',
    'pmChannels' => true,
]);
`
I get 

[2017-08-13 21:18:32] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250} []
**[2017-08-13 21:18:33] DiscordPHP.INFO: stored private channels {"count":0} []**
[2017-08-13 21:18:33] DiscordPHP.INFO: stored guilds {"count":0} []

one step further ...

**Comment by r7l** [comment]
Does it work? You have any other options? I haven't had this set any my bot can read and write PM messages fine. I only use the *token* option.

`did not parse private channels [] []`

**Comment by xmillies** [comment]
No it still doesn't works.

**Comment by xmillies** [comment]
My test code :  

<?php

include __DIR__.'/../vendor/autoload.php';
ini_set('memory_limit', '2048M');

use Discord\Discord;

$discord = new Discord([
    'token' => 'my_code',
    'pmChannels' => true,
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
    });
});

$discord->run();

**Comment by r7l** [comment]
Your code should run perfectly fine. Are your PM users members of the same Guild? Not sure if that is needed. Never tried.

**Comment by r7l** [comment]
The only difference i can see from my code would be that i've wrapped $discord into a class not giving it into the anonymous functions but instead using `$this->discord`. But i don't think this is the problem. You've tried to put a var_dump on $message?

**Comment by xmillies** [comment]
PM users are not necessary members of same Guild.
Yes, I tried var_dump in my code by I didn't go through.

**Comment by xmillies** [comment]
Maybe on the creation of the bot.

1° Make new app.
App Name : my bot
Clik on **Create App**

2° Click on **Create a Bot User**
Unchecked **Public Bot** and save
> **Require OAuth2 Code Grant** is unchecked

3° Copy my client Id 
open  https://discordapp.com/oauth2/authorize?client_id=&scope=bot (replace CLIENT ID with copied ID)
=> add a guild 
=> this works ... for a guild

Maybe I miss on another step

**Comment by key2peace** [comment]
See https://discordapp.com/developers/docs/resources/channel#channel-object-channel-types
and
\Discord\Parts\Channel\Channel::getChannelType() checking for Channel::TYPE_TEXT
