### ISSUE TITLE
Allowed memory size of xxx bytes exhausted

### ISSUE THREAD

**Issue by Daijobou** [teamreflex/DiscordPHP#265]
I get a memory error with line
`$discord` = new Discord(['token' => 'bot-token',]);

Have anybody a hint was going wrong?

**Comment by SpeedyCraftah** [comment]
Opoo

**Comment by davidcole1340** [comment]
There is a memory leak somewhere in the code. I will look into it eventually, for now if you need it to work you can increase the memory limit as said in the readme.
