### ISSUE TITLE
UPDATE_PRESENCE Always returns the same user

### ISSUE THREAD

**Issue by VincentTeresa** [teamreflex/DiscordPHP#266]
Hello, 

I want to know when somebody change his status as offline or something, but the presence update event always returns the same user. 
```

$this->discord->on('ready', function ($discord) {
           echo "Bot ready".PHP_EOL;
           $discord->on('PRESENCE_UPDATE', function ($presence) {
                var_dump($presence);
                echo "PRESENCE_UPDATE".PHP_EOL;
            });
});
```

**Comment by Toan** [comment]
https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/WebSockets/PresenceUpdate.php#L47

Replace by 
`return $this->discord->users->get('id',$this->attributes['user']->id);`

**Comment by davidcole1340** [comment]
Fixed in latest commit. Thank you.
