### ISSUE TITLE
EVENT doesn't working

### ISSUE THREAD

**Issue by w0ktit** [teamreflex/DiscordPHP#271]
Hello, i've tried to use these event but i can't:
```
$discord->on(EVENT::GUILD_MEMBER_ADD, function ($member) {
   echo "joined";
});

$discord->on(EVENT::GUILD_MEMBER_REMOVE, function () {
   echo "quit";
});

```
It's telling me
Fatal error: Uncaught Error: Class 'EVENT' not found
but i've already set
`use Discord\WebSockets;
use Discord\WebSockets\Events;`

Can you help me ? Thanks a lot

**Comment by r7l** [comment]
use Discord\Discord;
use Discord\Parts\User\Game;
use Discord\WebSockets\Event;

I am using the same thing with these namespaces. You probably don't need Game but Discord/Discord should be needed. You have $discord running?

**Comment by garrettw** [comment]
PHP class names are not case-sensitive, if I'm not mistaken.
However, your `use` statement has a typo: it uses "Events" while your code uses "Event".

**Comment by w0ktit** [comment]
Oh thank's it was 
`use Discord\WebSockets\Event;`

and note
`use Discord\WebSockets\Event;`

Thank you so much
