### ISSUE TITLE
syntax error, unexpected 'use'

### ISSUE THREAD

**Issue by Bluscream** [teamreflex/DiscordPHP#278]
```
[Wed Jun 27 11:01:29.432245 2018] [php7:crit] [pid 5996:tid 1952] [client ::1:1376] PHP Parse error:  syntax error, unexpected 'use' (T_USE) in S:\\XAMPP\\htdocs\\bs\\index.php on line 103, referer:
```

i installed it through composer btw.

**Comment by garrettw** [comment]
If you installed it through Composer, `S:\XAMPP\htdocs\bs\index.php` is not a file that belongs to this library; it's your code that has the error.

**Comment by Bluscream** [comment]
https://github.com/BlackSquadGame/rank-sync/blob/master/index.php#L13

**Comment by garrettw** [comment]
have you tried moving that line to the top of the file?

**Comment by aequasi** [comment]
use should be near the top of your file:

1. requires/includes
2. namespace declaration
3. use statements
4. rest of logic.
