### ISSUE TITLE
Start DM by Discord name

### ISSUE THREAD

**Issue by bobdabiulder** [teamreflex/DiscordPHP#282]
I want to use a string representing a Discord user, and send a DM to that user.  How do I do this?

**Comment by FrostingBita** [comment]
This library is already dead. No updates

**Comment by r7l** [comment]
Use this one: https://github.com/CharlotteDunois/Yasmin

**Comment by davidcole1340** [comment]
Assuming you want to search by username:

```php
$user = $discord->users->get('username', 'username to message');
// ... check that user is not null
$user->sendMessage('my message')->then(...);
```

Note you will need to set the load all members option when creating the discord client. See the documentation for more information.
