### ISSUE TITLE
Website Channel->getMessageHistory->Collection dead link

### ISSUE THREAD

**Issue by bjorno43** [teamreflex/DiscordPHP#283]
The website states:

Returns a Promise with a Collection

Where Collection is a dead link. Please fix this as it'll be useful to know what kind of data will be returned so you know how to handle it.

Dead link: [https://discordphp.readme.io/v4.0.0/docs/collection](https://discordphp.readme.io/v4.0.0/docs/collection)

**Comment by SpeedyCraftah** [comment]
He gave up on it apparently

**Comment by davidcole1340** [comment]
Documentation is not a high priority at the moment sorry. See the [API reference](http://teamreflex.github.io/DiscordPHP/Discord/Helpers/Collection.html) for more information.
