### ISSUE TITLE
Websocket error (op 0)

### ISSUE THREAD

**Issue by NobDod** [teamreflex/DiscordPHP#284]
Hi, when I run the bot, gives an error `discordPHP.WARNING: websocket closed {"op":0,"reason":"websocket error"} []`

I use php 5.6, Windows 10.
How to fix?

**Comment by Adrriii** [comment]
I am also getting this error on Debian 10

**Comment by NobDod** [comment]
No one wants to upgrade, most likely DiscordPHP died...

**Comment by Adrriii** [comment]
Yup, time to rewrite code. Can't be too bad on the long run anyway

**Comment by garrettw** [comment]
> No one wants to upgrade, most likely DiscordPHP died...

The [README](https://github.com/teamreflex/DiscordPHP) clearly says this.

**Comment by Adrriii** [comment]
I might be interested in this, thanks you !

**Comment by davidcole1340** [comment]
Closing due to age. If this error is still happening please create a new issue with steps to reproduce. I have no issues.
