### ISSUE TITLE
Undefined index: nick

### ISSUE THREAD

**Issue by oasfuyou** [teamreflex/DiscordPHP#287]
PHP Notice:  Undefined index: nick in /Users/fuyou/Documents/workspace/discord/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/PresenceUpdate.php on line 52
PHP Stack trace:
PHP   1. {main}() /Users/fuyou/Documents/workspace/discord/test.php:0
PHP   2. Discord\Discord->run() /Users/fuyou/Documents/workspace/discord/test.php:21
PHP   3. React\EventLoop\StreamSelectLoop->run() /Users/fuyou/Documents/workspace/discord/vendor/team-reflex/discord-php/src/Discord/Discord.php:1229
PHP   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /Users/fuyou/Documents/workspace/discord/vendor/react/event-loop/src/StreamSelectLoop.php:205
PHP   5. call_user_func:{/Users/fuyou/Documents/workspace/discord/vendor/react/event-loop/src/StreamSelectLoop.php:236}() /Users/fuyou/Documents/workspace/discord/vendor/react/event-loop/src/StreamSelectLoop.php:236
PHP   6. React\Stream\Stream->handleData() /Users/fuyou/Documents/workspace/discord/vendor/react/event-loop/src/StreamSelectLoop.php:236
PHP   7. React\Stream\Stream->emit() /Users/fuyou/Documents/workspace/discord/vendor/react/stream/src/Stream.php:173
PHP   8. Ratchet\RFC6455\Messaging\MessageBuffer->onData() /Users/fuyou/Documents/workspace/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:70
PHP   9. Ratchet\RFC6455\Messaging\MessageBuffer->processData() /Users/fuyou/Documents/workspace/discord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:60
PHP  10. Ratchet\Client\WebSocket->Ratchet\Client\{closure:/Users/fuyou/Documents/workspace/discord/vendor/ratchet/pawl/src/WebSocket.php:70-72}() /Users/fuyou/Documents/workspace/discord/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php:108
PHP  11. Ratchet\Client\WebSocket->emit() /Users/fuyou/Documents/workspace/discord/vendor/ratchet/pawl/src/WebSocket.php:71
PHP  12. Discord\Discord->handleWsMessage() /Users/fuyou/Documents/workspace/discord/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:70
PHP  13. Discord\Discord->handleDispatch() /Users/fuyou/Documents/workspace/discord/vendor/team-reflex/discord-php/src/Discord/Discord.php:564
PHP  14. Discord\WebSockets\Events\PresenceUpdate->handle() /Users/fuyou/Documents/workspace/discord/vendor/team-reflex/discord-php/src/Discord/Discord.php:673

**Comment by davidcole1340** [comment]
Has been fixed in the develop branch.
