### ISSUE TITLE
Cant install to laravel project

### ISSUE THREAD

**Issue by OzanKurt** [teamreflex/DiscordPHP#293]
Please update the laravel requirement in composer.json

**Comment by davidcole1340** [comment]
What are you trying to do with Laravel? This library shouldn't be used in a web app. Have a look at [restcord](https://github.com/restcord/restcord).

**Comment by OzanKurt** [comment]
I was hoping to run it as a command. Same thing as running in cli.

**Comment by davidcole1340** [comment]
Will have a look today and update illuminate/support to 7.25, just need to see what has changed.

**Comment by davidcole1340** [comment]
Try the `develop` branch for me.

**Comment by OzanKurt** [comment]
I would rather learning this and contribute. It looks a lot more promising. Thanks for the update!
