### ISSUE TITLE
The bot presence is not set.

### ISSUE THREAD

**Issue by GTEXNIK** [teamreflex/DiscordPHP#301]
I write everything as in the documentation. As a result, it returns a fattal error: 
![image](https://user-images.githubusercontent.com/65672058/91194487-dd7a0880-e700-11ea-927e-25e2d54ebd07.png)
![image](https://user-images.githubusercontent.com/65672058/91194553-eec31500-e700-11ea-8794-db13b32d2b94.png)

**Comment by davidcole1340** [comment]
Can you install the develop branch by running `composer require team-reflex/discord-php dev-develop`? Then try:

```php
$activity = $discord->factory(\Discord\Parts\User\Activity::class, ['name' => 'i am playing a game!']);
$discord->updatePresence($activity);
```

**Comment by GTEXNIK** [comment]
A token is used to install dev-development. What's it?

**Comment by davidcole1340** [comment]
Not sure what you mean? I had no issues installing it to a test project. Are you typing it in correctly?

```
composer require team-reflex/discord-php dev-develop
```

**Comment by mvaessen** [comment]
Any ETA when develop changes will be released?

**Comment by davidcole1340** [comment]
> Any ETA when develop changes will be released?

Not sure yet sorry, I would still consider `develop` the most stable branch at the moment.

**Comment by mvaessen** [comment]
I'm really struggling to get this working. Do you perhaps have any pointers for me?

```php
$this->setup();

        
$this->discord->on('ready', function($discord) {
   var_dump('update presence');
   $activity = $discord->factory(\Discord\Parts\User\Activity::class, ['name' => 'i am playing a game!']);
   $discord->updatePresence($activity);
});
```

The `setup` initiates an extended `Discord` instance. Responds to messages and all, so that seems to work fine and initiate at the right moment. However, the updatePresence bit doesn't seem to do anything.

After `ready` was triggered I can see `update presence` popping up, but nothing changes on the bot.
Are you aware of any limitations to test-bots? Or is there something else going on.

Thanks!

**Comment by oliverschloebe** [comment]
Try providing a `type` in addition to the `name`.

**Comment by mvaessen** [comment]
Awesome, thanks!

**For people who come across this in the future:**
When running the latest `develop` branch, use:
```php
$discord->on('ready', function($discord) {
   $activity = $discord->factory(\Discord\Parts\User\Activity::class, [
       'name' => '!help',
       'type' => Activity::TYPE_LISTENING
   ]);
   $discord->updatePresence($activity);
});

```
