### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by KomAuras** [teamreflex/DiscordPHP#303]
Are there any plans to add event handling MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE & MESSAGE_REACTION_REMOVE_ALL 

Thanks

**Comment by oliverschloebe** [comment]
Check the `develop` branch: https://github.com/teamreflex/DiscordPHP/tree/develop

**Comment by KomAuras** [comment]
Thanks!

**Comment by KomAuras** [comment]
I'm sorry. I'm not very good at it 
I tried to install the developer version using `composer require team-reflex/discord-php dev-develop`
But still something old is downloaded

**Comment by davidcole1340** [comment]
@KomAuras does it give any errors when you run that command?

**Comment by KomAuras** [comment]
Run
`composer clearcache`
`composer require team-reflex/discord-php dev-develop`
No errors.
In composer.json correctly added 
```
"require": {                                 
    ...             
    "team-reflex/discord-php": "dev-develop" 
},                                           
```
But in `vendor\team-reflex\discord-php\src\Discord\WebSockets\Events\MessageReactionAdd.php` still old code
```
    public function handle(Deferred $deferred, $data)
    {
        // todo
        $deferred->resolve($data);
    }
```
I look in composer repo `C:\Users\...\AppData\Local\Composer\repo\https---repo.packagist.org\provider-team-reflex$discord-php.json` file
composer get old version from this url https://codeload.github.com/teamreflex/DiscordPHP/legacy.zip/407f85ae0f36c00bfde4cc3cd13820843afb0757

**Comment by davidcole1340** [comment]
Interesting, happens for me as well. Might be something to do with packagist. Can you cd into `vendor/team-reflex/discord-php` and run `git pull`? I will look into the composer issue.

**Comment by davidcole1340** [comment]
Seems the packagist auto-update webhook stopped working at some point over the past couple years, I've fixed it so should be working now. IIRC packagist takes a while to refresh so I will check again in 15 mintues.

**Comment by KomAuras** [comment]
`git pull` work.
Thanks

**Comment by davidcole1340** [comment]
Composer seems to be working now, thanks for reporting!
