### ISSUE TITLE
Issues with large guilds

### ISSUE THREAD

**Issue by Thorrdu** [teamreflex/DiscordPHP#306]
Hello,

Since my bot got accepted on the top.gg, server, I can't keep it alive. (I'm on develop branch)
It loop through  "did not receive heartbeat ACK within heartbeat interval, closing connection" :

![image](https://user-images.githubusercontent.com/15250935/91783622-15051b00-ec01-11ea-8e2c-89ec9722a1e1.png)

I tried to disable "loadAllMembers" but then I can't get users with $discord->users->get('id', USER_ID);

It's currently on 68 server with 22k users. 
Should I activate sharding ?
If I should, could you point me an exemple to do that with this lib ?

Also strange thing, it sometimes work for a while but only after reconnecting once : 
![image](https://user-images.githubusercontent.com/15250935/91785242-32d47f00-ec05-11ea-927b-3d0e3ad3b23f.png)

Resources allocation should not be a problem as it uses +- 700M when fully loaded and I have 8Go on my VPS.

**Comment by davidcole1340** [comment]
When was the last time you updated DiscordPHP? I pushed some changes recently that optimise user loading. Try run `composer update`

**Comment by Thorrdu** [comment]
Yesterday evening, as I couldn't make it start with the fork we had with rocket-mates after the bot joined the super large guild ( 15-20k users ), so I switched to the develop branch of the main lib.

I just had to rewrite a few part of the bot, implementing your new messageReactionCollector ( btw, good job on that one ! ) 

I tested it with the same code but with a bot who is only on 2 server and it's super fluid.
But when I try on the main bot, I get the "did not receive heartbeat ACK within heartbeat interval" problem most of the time or the second screen but it's not alive for long (+- 2 minutes before beeing forced to reconnect).

I'll try a few tweak but I'm no expert in load balancing and webstocket ^^

**Comment by davidcole1340** [comment]
Could you run `composer show` and find `team-reflex/discord-php` and paste the output? I'm running my bot with approx 130 guilds and some over 65k members and its running fine at the moment.

**Comment by Thorrdu** [comment]
![image](https://user-images.githubusercontent.com/15250935/91832192-646d3a80-ec45-11ea-9572-b871cf8b03ea.png)

*crossing fingers* it has not 70 servers for 136k users and since the last reboot, it's running fine for 21 minutes straight.
I adapted the chunk size for large guilds from 50 to 500.
It might have affected the load balancing.

But if you can run 65k users I don't see any reason I could not with the same lib version.
I unfortunately haven't time to fully test tweats during the day but I'll test changes this evening.

Again, thanks for your quick answers and reactivity !

**Comment by Thorrdu** [comment]
It's been online for 3h straight without any problem...
It's even the chunk or the evening population that made it loop crash.

**Comment by Thorrdu** [comment]
And a little bug connected to this:

When some guilds add:
![image](https://user-images.githubusercontent.com/15250935/91866328-af517700-ec72-11ea-9bbc-5c375fc7e1ec.png)

**Comment by davidcole1340** [comment]
Sweet, let me know how it runs. Thanks for reporting the guild update problem, not sure how that snuch through...

**Comment by Thorrdu** [comment]
The problem appeared again in early evening.
But I tested it from local and I had no problem.
The problem does not come from the lib. I'll close the ticket and search from the server side ^^

Thanks again for your answers
