### ISSUE TITLE
Shards makes guilds redundancy

### ISSUE THREAD

**Issue by Thorrdu** [teamreflex/DiscordPHP#307]
Hello,

I tested the Shards functionnality today ( escencialy to isolate a large guild from most servers ) but I have an issue:
As there is no Sharding Manager Tool (like https://anidiots.guide/understanding/sharding ) I setted up numerous instance through PM2.
Unfortunatly, as it's not managed by a single page/tool, if an instance reloads and guilds count has changed, there is a chance for this instance to have missing guilds or worst,, having guilds that are on 2 differents shards.

It's not a common bug, but I think it would be great to have something to centralize sharding.

**Comment by mvaessen** [comment]
To prevent a guild from being active on 2 shards I've added this to my code, which calculates if the executing shard should really execute or ignore:

`($message->channel->guild_id >> 22) % $discordOptions['shardCount'] != $discordOptions['shardId']`

You may need to update the `$discordOptions` according to your code.

**Comment by Thorrdu** [comment]
Thank you, I'll try it !

**Comment by davidcole1340** [comment]
Going to close for now.
