### ISSUE TITLE
Cant assign roles

### ISSUE THREAD

**Issue by CrazyBloo** [teamreflex/DiscordPHP#310]
Also is there a discord->on('join') or something similar for when they join the guild?

**Comment by CrazyBloo** [comment]
Im trying to assign a role on a user join, Ive got this so far 

```
$discord->on(\Discord\WebSockets\Event::GUILD_MEMBER_ADD, function ($member) {
        echo "Test", PHP_EOL;
        $member->addRole('751347593031712788');
        $discord->members->save($member);
        });
```

It echos the users join, but doesnt assign the role

**Comment by davidcole1340** [comment]
assuming you got this working?
