### ISSUE TITLE
How to check if a channels is not save for work(NSFW)?

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#311]
I think it isn't implemented yet.

**Comment by oliverschloebe** [comment]
Well it is, see [here](https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Channel.php#L51). ✌🏻

**Comment by davidcole1340** [comment]
Yup just check the boolean `nsfw` in the channel object e.g. `$message->channel->nsfw`. This value can either be `true` if it is NSFW or `null`/`false` if it is not.

**Comment by xxAROX** [comment]
thanks
