### ISSUE TITLE
Cant set status to TYPE_CUSTOM

### ISSUE THREAD

**Issue by CrazyBloo** [teamreflex/DiscordPHP#312]
I've been able to set the status with TYPE_LISTENING, but i just cant get custom to work, this is what I have.

```
$activity = $discord->factory(\Discord\Parts\User\Activity::class, [
        'emoji' => 'white_check_mark',
        'name' => 'Online!',
        'type' => Activity::TYPE_CUSTOM
    ]);
$discord->updatePresence($activity);
```

**Comment by davidcole1340** [comment]
From what I know you can only send `name`, `type` and `url` when you update presence as a bot. The `url` field is only for streaming as well: https://discord.com/developers/docs/topics/gateway#activity-object-activity-structure

**Comment by CrazyBloo** [comment]
I only added the emoji when I switched to custom, worked fine on listen with just `name` , and `type` , but when i changed it to custom it stopped working

**Comment by davidcole1340** [comment]
Yep so the `emoji` field isn't valid and you cant send it unfourtunately. Discord doesn't let us.

**Comment by oliverschloebe** [comment]
Can't seem to set a custom status, too. My code:

```php
$activity = $discord->factory(Activity::class, [
	'name' => 'watching you',
	'type' => Activity::TYPE_CUSTOM
]);
$discord->updatePresence($activity);
```

`TYPE_LISTENING` and `TYPE_PLAYING` do work fine, though.

**Comment by davidcole1340** [comment]
Just asked on the Discord API server and `TYPE_CUSTOM` is not allowed for bots. The constant will remain because presence updates may have the value.

**Comment by xxAROX** [comment]
maybe deprecate that?

**Comment by davidcole1340** [comment]
I'm planning to change the `updatePresence` function to throw an exception but the constant will remain because incoming presence updates may have the value.
