### ISSUE TITLE
Looping within the bot.

### ISSUE THREAD

**Issue by SamKTaylor** [teamreflex/DiscordPHP#313]
I've tried a number of ways of looping within the bot but nothing seems to work.

I've tried adding a react event loop within a $discord->on('ready', function ($discord) { but this seem to stop the bot working., ive also tried a simple while(true) loop but this also stops the bot working.

any thoughts? or should I just be looping outside the bot and launching a new instance of the bot each loop to interact with discord.

**Comment by davidcole1340** [comment]
Could you try explaining more on what you are trying to do? Using the `while (true)` loop blocks the event loop so the websocket disconnects. If you want jump on our discord server and I can help you.

**Comment by xxAROX** [comment]
Same Problem:
Here is an example in javascript, what i mean:
```js
setInverval(() => {
     console.log("This comes all 12 seconds.");
}, 1000 * 12);
```

**Comment by davidcole1340** [comment]
If you want to add a timer, use the [react event loop timers](https://github.com/reactphp/event-loop#addperiodictimer). You can get the event loop using `$discord->getLoop()`, so e.g. `$discord->getLoop()->addPeriodicTimer(...)`.

**Comment by xxAROX** [comment]
kk

**Comment by xxAROX** [comment]
@davidcole1340 maybe pthreads?

**Comment by davidcole1340** [comment]
Pthreads only works for PHP 7.2< so I don't think it would work

**Comment by xxAROX** [comment]
maybe make a version of DiscordPHP that uses pthreads?

**Comment by davidcole1340** [comment]
No point of developing for a library that isn't maintained anymore, have a look at [parallel](https://www.php.net/manual/en/book.parallel.php)

**Comment by xxAROX** [comment]
Hmm idk
