### ISSUE TITLE
Field error

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#315]
![grafik](https://user-images.githubusercontent.com/57589973/93596999-9a871a00-f9ba-11ea-9f0b-24d21c3620e2.png)

**Comment by davidcole1340** [comment]
Can you update from the `develop` branch and then try:
```php
$embed->fields = [
    $field_VERSION,
    $field_...
];
```

**Comment by xxAROX** [comment]
> Discord\Exceptions\DiscordRequestFailedException: "Error code 400: We sent a bad request. Bad Request - {"embed": ["fields"]} - channels/755101509284266044/messages" (EXCEPTION) in "DiscordPHP/src/Discord/Http/Http" at line 262

```php
	$embed->fields = [
			$field_VERSION,
			$field_GUILDS,
			$field_MEMBERS,
			$field_MEMORY,
			$field_UPTIME,
			$field_CHANNELS,
		];

		/** @var Footer $footer */
		$footer = $this->getClient()->factory(Footer::class);
		$footer->text = VersionInfo::$NAME . " | DiscordPHP: " . Discord::VERSION . " | PID: " . Process::getPID();
		$footer->icon_url = $this->getClient()->user->getAvatarAttribute();
		$embed->footer = $footer;

		$message->channel->sendMessage("", false, $embed)->otherwise(
			function (DiscordRequestFailedException $exception){
				crashDump($exception);
			}
		);
```

**Comment by davidcole1340** [comment]
Can you check if you updated? Seems to work for me.

**Comment by xxAROX** [comment]
*i update my libary by myself.*
i added a ugly typo :|

**Comment by xxAROX** [comment]
thanks*
