### ISSUE TITLE
\Discord\WebSockets\Event::READY

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#316]
```php
\Discord\Discord::on(\Discord\WebSockets\Event::READY, callable)
```
doesn't work, but
```php
\Discord\Discord::on("ready", callable)
```
works.

**Comment by davidcole1340** [comment]
The `Event::READY` event is for the ready event that is received from Discord, while the `'ready'` event is is for when the client is ready, so it is kinda intented. You shouldn't need to listen for the `Event::READY` as this is handled automatically.

**Comment by xxAROX** [comment]
maybe change that to
```
\Discord\WebSockets\Event::READY -> \Discord\WebSockets\Event::READY_DISCORD
"ready" ->\Discord\WebSockets\Event::READY
```
??

**Comment by davidcole1340** [comment]
`ready` is a client event and the `Event` class is `Discord\WebSockets\Event`, meaning events relating to websockets, so I'm just going to leave it out.

**Comment by xxAROX** [comment]
kk
