### ISSUE TITLE
Collection::exists

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#320]
Collection::exists("key", new Value());

**Comment by xxAROX** [comment]
```php
public function isset($key): bool{
     return isset($this[$key]);
}
```
@davidcole1340

**Comment by xxAROX** [comment]
for the lazy developers[me, lol] :)

**Comment by davidcole1340** [comment]
Can use `$collection->offsetExists('key')` as it does the same thing as `isset` but I will add an alias.

**Comment by xxAROX** [comment]
thanks
