### ISSUE TITLE
Member::$user->bot

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#323]
![grafik](https://user-images.githubusercontent.com/57589973/93816466-dc80bc00-fc57-11ea-8f26-2653c75c446e.png)

**Comment by davidcole1340** [comment]
`$message->mentions` is a collection of `User` objects, so you should do `if ($target->bot)`.
Change the first line as well: `$message->author->user`. You should also check if it is a PM, as `$message->author` will be a `User` object already if it is a PM.

**Comment by xxAROX** [comment]
Works, thanks!
