### ISSUE TITLE
How to send Embed-Videos??

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#332]
```php
					$longVideo = "https://cdn.discordapp.com/attachments/758078168904237277/758348382828888104/github_-_Discord_2020-09-23_17-24-57.mp4";
					$shortVideo = "https://cdn.discordapp.com/attachments/758078168904237277/758348561364025394/Minecraft_2020-09-15_17-31-10.mp4";
					$embed = createEmbed(); //returns Embed
					$embed->type = Embed::TYPE_VIDEO;
					$embed->video = createVideo($shortVideo); //returns Video
					$embed->type = Embed::TYPE_IMAGE;
					$embed->color = 0x0000ff;

					$message->channel->sendEmbed($embed);
```

**Comment by AiScots** [comment]
AFAIK, bots can't set type

`For the embed object, you can set every field except type (it will be rich regardless of if you try to set it), provider, video, and any height, width, or proxy_url values for images.`

Source: [https://discord.com/developers/docs/resources/channel#create-message](https://discord.com/developers/docs/resources/channel#create-message)

**Comment by xxAROX** [comment]
try it, at my tests it doesn't work

**Comment by xxAROX** [comment]
send the video link into the channel
