### ISSUE TITLE
Collection get by name does not work

### ISSUE THREAD

**Issue by Ravisdo** [teamreflex/DiscordPHP#334]
Maybe im a bit silly :D
I try to get a guild role by name
`$guild->roles->get('name', 'Role-Name');`
but this returns NULL

Is there a easy way to get a collection part item by name? Otherwise i would suggest to create a `getByName()` method on the repositories :)

**Comment by xxAROX** [comment]
```php
foreach ($guild->roles as $role) {
     if ($role->name == "string") {
          return true;
     }
}
```

**Comment by Kanuuu** [comment]
Yeah, that code works
But that code will not fork for user or other collections.
For user its "username" ie.

It would be great if the collection support that feature otherwise i must include a helper function to not duplicate code :D

**Comment by xxAROX** [comment]
the username is not unique

**Comment by xxAROX** [comment]
@Kanuuu, you mean like https://github.com/discordjs/collection/blob/master/src/index.ts#L283 right?

**Comment by Kanuuu** [comment]
I think so. I'm not so good at nodejs code.

On a fork i added to the RoleRepository following code
```
public function getByName(string $name): Role
    {
        foreach ($this->collection as $part) {
            if ($part->name === $name) {
                return $part;
            }
        }
    }
```

**Comment by xxAROX** [comment]
function getKey($key, $value) {
        foreach ($this->collection as $part) {
            if ($part->$key === $value) {
                return $part;
            }
        }
}

maybe change it to

**Comment by xxAROX** [comment]
idk

**Comment by Kanuuu** [comment]
I think that code could work on all repositories than.

I work local also with php 7.4 so do not mind :D

**Comment by xxAROX** [comment]
same with 7.3.21

**Comment by xxAROX** [comment]
@ windows 10 pro

**Comment by xxAROX** [comment]
> @Kanuuu, you mean like https://github.com/discordjs/collection/blob/master/src/index.ts#L283 right?

this method is great
@davidcole1340 it's exciting if you add this
xd

**Comment by Kanuuu** [comment]
In my first bot with node i had this methods
` const roleMaline = message.guild.roles.find(role => role.name === "Maline");
    const emoteMaline = client.emojis.find(emoji => emoji.name === "Maline");
let perms = client.guilds.find(guild => guild.id === member.guild.id).members.find(member => member.id === client.user.id).permissions;`
That was easy and nice to implement

**Comment by davidcole1340** [comment]
Can you try on the latest version of the master branch?

**Comment by Ravisdo** [comment]
Now its working <3

```
   $this->client->on('ready', function () {
            echo "Bot is ready." . PHP_EOL;
            echo $this->client->guilds->get('id', 536562056543993870)->roles->get('name', 'Flusseln')->name . PHP_EOL;
        });
```
Bot is ready.
Flusseln
