### ISSUE TITLE
Allow Custom logger class.

### ISSUE THREAD

**Issue by xxAROX** [teamreflex/DiscordPHP#336]
`Fatal error: Uncaught TypeError: Argument 1 passed to Discord\Wrapper\LoggerWrapper::__construct() must be an instance of Monolog\Logger, instance of xxAROX\utils\Logger given, called in /home/travis/build/xxAROX/Elozym/vendor/team-reflex/discord-php/src/Discord/Discord.php on line 294 and defined in /home/travis/build/xxAROX/Elozym/vendor/team-reflex/discord-php/src/Discord/Wrapper/LoggerWrapper.php on line 41`

**Comment by Kanuuu** [comment]
You can extend from Monolog\Logger.
Did the same.

I wrote an MySqlLogHandler and that writes the log into a database with Laravel Eloquent ORM

**Comment by xxAROX** [comment]
*its for travis-ci*

**Comment by xxAROX** [comment]
but thanks

**Comment by davidcole1340** [comment]
Try the lastest on `master` branch, de7b85c22240d004261d1daf395d3af4fad84a0a

**Comment by Ravisdo** [comment]
thats a pretty cool change to use psr logger :)
