### ISSUE TITLE
Add illuminate/support: ^8.0

### ISSUE THREAD

**Issue by PunyFlash** [teamreflex/DiscordPHP#339]
Can't use the library in Laravel 8 due to package version conflict

**Comment by Caffe1neAdd1ct** [comment]
Surely we only need to require a minimum needed version for this package to
include the methods we are currently using?

I'd suggest to steer clear of a hard requirement if possible as so many
other packages / frameworks use this dependency.

**Comment by PunyFlash** [comment]
So why is this a problem to add a newer package version support?
