### ISSUE TITLE
nesbot/carbon 2.38 requires php 7.1.8 and higher

### ISSUE THREAD

**Issue by key2peace** [teamreflex/DiscordPHP#341]
https://github.com/teamreflex/DiscordPHP/blob/3dc34ecefc0010116e24845369e5df98a3181f23/composer.json#L19

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nesbot/carbon 2.40.1 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - nesbot/carbon 2.40.0 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - nesbot/carbon 2.39.2 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - nesbot/carbon 2.39.1 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - nesbot/carbon 2.39.0 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - nesbot/carbon 2.38.0 requires php ^7.1.8 || ^8.0 -> your PHP version (7.0.33) does not satisfy that requirement.
    - Installation request for nesbot/carbon ^2.38 -> satisfiable by nesbot/carbon[2.38.0, 2.39.0, 2.39.1, 2.39.2, 2.40.0, 2.40.1].

Looks like you need to change:
https://github.com/teamreflex/DiscordPHP/blob/3dc34ecefc0010116e24845369e5df98a3181f23/composer.json#L16

**Comment by xxAROX** [comment]
*use php 7.3.21*

**Comment by davidcole1340** [comment]
Thanks, I will update the readme.
