### ISSUE TITLE
Why not use the Event constant

### ISSUE THREAD

**Issue by GIT-RickVH** [teamreflex/DiscordPHP#35]
Just wanted to ask a quick question about the line at:

https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/WebSockets/WebSocket.php#L210

Why isn't the Event::READY being emitted there? Took me a while to figure out the ready event was never fired because I was checking on that constant. 

If you change this it would break a lot of peoples implementations ... I would think

**Comment by uniquoooo** [comment]
It's been like that ever since the library has been released and it's been recommended, however I may add an alternative as well.
