### ISSUE TITLE
Extend Parts to allow to attach scriptdata to it

### ISSUE THREAD

**Issue by key2peace** [teamreflex/DiscordPHP#350]
```diff
diff -burNx .git a/src/Discord/Parts/Part.php b/src/Discord/Parts/Part.php
--- a/discord-php/src/Discord/Parts/Part.php       2020-10-03 14:13:52.000000000 +0200
+++ b/src/Discord/Parts/Part.php   2020-10-01 09:04:08.124265466 +0200
@@ -104,6 +104,13 @@
     protected $fillAfterSave = true;

     /**
+     * An array for script usage.
+     *
+     * @var array
+     */
+    public $scriptData = [];
+
+   /**
      * Create a new part instance.
      *
      * @param Factory $factory    The factory.
```

**Comment by davidcole1340** [comment]
What does this do?

**Comment by key2peace** [comment]
since everything else in the Part struct is tailored to be used by the api only, this public would allow for attaching data to be used for scripting purposes, if you remember eggdrop (irc bot), that one had setudef to add custom channel settings.

See it as a container for custom data someone might want to add to a channel/guild/member/whatever.
Using this myself and it is quite handy. Yes, ,everything has a __set/__get method, but using this on for example Channel etc causes it to complain about overloading.

**Comment by davidcole1340** [comment]
I've added it but it will probably be best to use an array of some sorts to do this, as if you update a part in one place it won't nessacarily update in the repositories.
