### ISSUE TITLE
Suppressed Exceptions?

### ISSUE THREAD

**Issue by jsisson** [teamreflex/DiscordPHP#358]
When I run the example script, the code runs fine, however any exceptions within the event handlers are suppressed for some reason.

This throws an exception as expected (and halts execution):
```
include __DIR__.'/vendor/autoload.php';
use Discord\Discord;
$discord = new Discord(['token' => '*TOKEN*']);

throw(new \Exception('test exception'));

$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
    });
});

$discord->run();
```

However this does not:
```
include __DIR__.'/vendor/autoload.php';
use Discord\Discord;
$discord = new Discord(['token' => '*TOKEN*']);

$discord->on('ready', function ($discord) {
    throw(new \Exception('test exception'));

    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        echo "{$message->author->username}: {$message->content}",PHP_EOL;
    });
});

$discord->run();
```

The exception is completely ignored, as are any exceptions on code that run within the $discord event handler.  This makes it difficult to debug.

There is a previous issue that mentions this, but it was closed (without explanation): #260

**Comment by davidcole1340** [comment]
Unfortunately due to the fact that the `ready` callback is called within a react PHP timer, the exception is supressed as any exceptions thrown in a timer will not be caught. I'm going to implement a try/catch statement around the ready statement to emit and log any exception.

If you want to handle the exception yourself, the best way would be to use your own try/catch or listen for the `exception` event on the `Discord` class.

**Comment by jsisson** [comment]
@davidcole1340 Is this something reactphp does?

I found [an old issue](https://github.com/reactphp/event-loop/issues/50) where they discussed it removing that suppression a few years ago, so I'm curious if this is a feature or a regression or something?

**Comment by davidcole1340** [comment]
Yeah, comes from the [react timers](https://github.com/reactphp/event-loop#addtimer): "The timer callback function MUST NOT throw an Exception."

I'm not sure on the reasoning for this or if it can be changed but could be something to look into.

**Comment by jsisson** [comment]
Thanks for the quick reply, I see the issue now.

If you are able to work something out I'd love to see an example!

Thanks!

**Comment by davidcole1340** [comment]
Looking at the issue from react, seems like it was fixed only for the `ExtEventLoop`. I might have a play around and see what happens with other loops.

**Comment by davidcole1340** [comment]
Could you see what loop you are using?

```php
$loop = \React\EventLoop\Factory::create();
echo get_class($loop).PHP_EOL;
die;
```

**Comment by jsisson** [comment]
React\EventLoop\StreamSelectLoop

**Comment by davidcole1340** [comment]
Seems like it is an issue with `react/promise`, as when a promise is rejected and not handled it does not print the exception. I've tested on one of the pull requests related to the issue and it seems to work as expected, however it seems that the fixex will only be coming with `react/promise@^3.0.0`.
