### ISSUE TITLE
composer require team-reflex/discord-php

### ISSUE THREAD

**Issue by sobhanso** [teamreflex/DiscordPHP#366]
Hi, I want to activate the robot, but I get an error
root@sv1:~/DastyarAparat# composer require team-reflex/discord-php
Using version ^5.0 for team-reflex/discord-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
----------
then >>
root@sv1:~/DastyarAparat# php run.php
PHP Warning:  include(/root/DastyarAparat/vendor/autoload.php): failed to open s                                                                                                                     tream: No such file or directory in /root/DastyarAparat/run.php on line 3
PHP Warning:  include(): Failed opening '/root/DastyarAparat/vendor/autoload.php                                                                                                                     ' for inclusion (include_path='.:/usr/share/php') in /root/DastyarAparat/run.php                                                                                                                      on line 3
PHP Fatal error:  Uncaught Error: Class 'Discord\Discord' not found in /root/Das                                                                                                                     tyarAparat/run.php:5
Stack trace:
#0 {main}
  thrown in /root/DastyarAparat/run.php on line 5
----------
Please help

**Comment by davidcole1340** [comment]
Your file can't find the autoload file. It seems that when you ran `composer require team-reflex/discord-php` it hasn't installed. Did you intentionally kill the process?

**Comment by sobhanso** [comment]
Done, please give examples to use. Thank you, can you tell me how to use embeds messages?

**Comment by Ravisdo** [comment]
```php
$discordRestClient->channel->createMessage(
    [
        'channel.id' => intval(539055911600259076),
        'content' => '',
        'embed' => [
            'title' => '~ title maybe ~',
            'description' => 'some description',
            'timestamp' => $now->format('Y-m-d\TH:i:sO'),
            'footer' => [
                'text' => $foot,
            ],
        ],
    ]
);
```

**Comment by key2peace** [comment]
```php
$embed = $this->client->factory(Embed::class, [
    'color' => 15105570,
    'description' => 'description',
    'timestamp' => '',
], true);
$receivedMessage->channel->sendMessage('', false, $embed);

See [`the api docs about embed fields``](https://discord.com/developers/docs/resources/channel#embed-limits)

**Comment by sobhanso** [comment]
Thank you, how can I use emojis in the title or description?

**Comment by sobhanso** [comment]
Thank you, how can I use emojis in the title or description?

**Comment by key2peace** [comment]
https://discord.com/developers/docs/resources/channel#embed-object

**Comment by davidcole1340** [comment]
Join our Discord server and we can give you more help.

**Comment by sobhanso** [comment]
Thanks, please send the invitation link

**Comment by oliverschloebe** [comment]
> Thanks, please send the invitation link

The links are on top of the repo description over here: https://github.com/teamreflex/DiscordPHP ✌🏻

**Comment by sobhanso** [comment]
> > Thanks, please send the invitation link
> 
> The links are on top of the repo description over here: https://github.com/teamreflex/DiscordPHP ✌🏻

I know it is, but the link does not work!

**Comment by Ravisdo** [comment]
> 
> 
> > > Thanks, please send the invitation link
> > 
> > 
> > The links are on top of the repo description over here: https://github.com/teamreflex/DiscordPHP ✌🏻
> 
> I know it is, but the link does not work!

The link work if you use the correct one. You must use the [PHP Discorders](https://discord.gg/0duG4FF1ElFGUFVq) link

**Comment by sobhanso** [comment]
> > > > Thanks, please send the invitation link
> > > 
> > > 
> > > The links are on top of the repo description over here: https://github.com/teamreflex/DiscordPHP ✌🏻
> > 
> > 
> > I know it is, but the link does not work!
> 
> The link work if you use the correct one. You must use the [PHP Discorders](https://discord.gg/0duG4FF1ElFGUFVq) link

https://gofile.io/d/9Xew0G yo can see

**Comment by Ravisdo** [comment]
https://discord.gg/Hg78wT

**Comment by sobhanso** [comment]
> https://discord.gg/Hg78wT

It does not work properly, thank you very much
