### ISSUE TITLE
[bot-api]Opcode 4006 Invalid Session

### ISSUE THREAD

**Issue by proxikal** [teamreflex/DiscordPHP#37]
websocket has been dropping every 10 minutes.
After about 4-5x of restarting. i'll start getting an Opcode 4006 (Invalid Session)
This is only happening on the bot with 230 servers
The other bot is on about 20 servers. websocket closes about 1 time an hour.
No invalid session on the other bot.

**Comment by uniquoooo** [comment]
I'll need to fully redo the connection including re-updating the cache which will take a while. Will implement it soon.

**Comment by proxikal** [comment]
ok :) on a semi-related topic.. I added
`$user = \Discord\Parts\User\User::find($message->author->id);
$user->sendMessage("msg..");`
on my small bot. he threw his first Websocket close. Opcode 1000
first time out of 2 days

**Comment by uniquoooo** [comment]
I've fixed this by fully reconnecting when 4006 is received. Let me know how it goes.

With the `sendMessage` issue, it's likely something that I can't fix.
