### ISSUE TITLE
invalid session reconnecting reason " " , no reason 

### ISSUE THREAD

**Issue by Kronos2308** [teamreflex/DiscordPHP#372]
![IMG_20201021_083945](https://user-images.githubusercontent.com/36446521/96688547-34a2ff00-1379-11eb-8367-868cd3612e8b.jpg)
I am using this library but I even have to add  bigger count becouse after a while star reconnecting with no reason and then discord restart the token for posible abuse 
How can I fix that ?

### Other things
* The docentation to send embeds and update presence is deprecated 
* Where I can find the new doc ?

**Comment by oliverschloebe** [comment]
Hi, what version of DiscordPHP are you running? Try `composer require team-reflex/discord-php dev-master` to get the latest changes which fixed the reconnect issue for me.

**Comment by Kronos2308** [comment]
> Hi, what version of DiscordPHP are you running? Try `composer require team-reflex/discord-php dev-master` to get the latest changes which fixed the reconnect issue for me.

Thanks I will try that .
did you know how to send embeds I try with a
array but I get a error

**Comment by oliverschloebe** [comment]
> did you know how to send embeds I try with a
> array but I get a error
Depends on the error. May you please post the error message?

**Comment by Kronos2308** [comment]
> > did you know how to send embeds I try with a
> > array but I get a error
> 
> Depends on the error. May you please post the error message?

Nop no error message just die with no print 

Type the command the code is executed then stop in the send message and start listening command message again

**Comment by UtterUseless** [comment]
I think this relates to the issue with heartbeat timer not restarting after a reconnect.
As mentioned previously, make sure you are on the latest master which should fix this issue

**Comment by Kronos2308** [comment]
> I think this relates to the issue with heartbeat timer not restarting after a reconnect.
> As mentioned previously, make sure you are on the latest master which should fix this issue

I put the dev-master no error at the moment

I found something else I don't know if is a error but send a embed to the user for md it requires a Embed object 
And crash if you send a array var

**Comment by key2peace** [comment]
send the basic code you are using in order to create the embed, otherwise, since you upgraded to dev-master, look at src/Discord/Discord.php, the new default help uses embeds, so you got some examples in there that way

**Comment by Kronos2308** [comment]
> 
> 
> send the basic code you are using in order to create the embed, otherwise, since you upgraded to dev-master, look at src/Discord/Discord.php, the new default help uses embeds, so you got some examples in there that way
```php

$embed = array(
'title' => 'NOOOO',
 'color' => 13553358,
'description' => 'Escribe en <#blabla>  de [link](link/link)' 
);
$message->author->user->sendMessage('',false,$embed );
```
this not work
in 
"discord-php\src\Discord\Parts\User\User.php"
line 98
```php

     * @param Embed|null $embed   An embed to send.
     *
     * @return PromiseInterface
     * @throws \Exception
     */
    public function sendMessage(string $message, bool $tts = false, ?Embed $embed = null): PromiseInterface
    {
        $deferred = new Deferred();

```
is specting a ?Embed $embed object

only work if you use
```php
$embed = array(
'title' => 'NOOOO',
 'color' => 13553358,
'description' => 'Escribe en <#blabla>  de [link](link/link)' 
);
$emb = $discord->factory(Embed::class, $embed);
$message->author->user->sendMessage('',false,$emb );

```
no array are accepted

**Comment by key2peace** [comment]
that's right, everything needs to be in the correct class before it can be used

**Comment by Kronos2308** [comment]
> 
> 
> that's right, everything needs to be in the correct class before it can be used

o ok
