### ISSUE TITLE
Dynamic prefix

### ISSUE THREAD

**Issue by baskettcase** [teamreflex/DiscordPHP#379]
Is there a way to have a dynamic prefix? for example when added to a server for the server to be able to set which prefix they want the bot to answer to?  Im not seeing a way since it's set on load.. but maybe there is? :) If not.. feature request? :)

Thanks!

**Comment by key2peace** [comment]
not using DiscordCommandClient, you will need to create your own wrapper for this

**Comment by baskettcase** [comment]
Ok thank you! Would be great to have this possibility...
