### ISSUE TITLE
[bot-api] Rest\NoPermissionsException Uncatchable!

### ISSUE THREAD

**Issue by proxikal** [teamreflex/DiscordPHP#38]
I've tried Everything
NoPermissionsException, DiscordRequestFailedException, PartRequestFailedException, \Exceptions, Exceptions.. I even went as far as adding the usefor NoPermissionsException and than repeating all steps above.

Instead of it throwing a DiscordRequestFailedException I've noticed at times It throws the NoPermissions exception..which you can't catch..

**Comment by uniquoooo** [comment]
Could you please provide some test code? Works fine for me.

**Comment by proxikal** [comment]
```php
$channel = $guild->channels->get('name', $greetchannel);
if(!isset($channel))
{
$channel = $guild->channels->getAll('type', 'text')->first();
}
$greetmsg = $dD[$newguild]['GreetMsg'];
$greetmsg=str_replace("{user}", "<@".$new_member->id.">", $greetmsg);
$greetmsg=str_replace("{guild}", $guild->name, $greetmsg);
try
{
$channel->sendMessage($greetmsg);
} catch (DiscordRequestFailedException $e) { 
 $user = \Discord\Parts\User\User::find($guild->owner_id);
 $user->sendMessage("You have me setup to greet people. yet my permissions won't allow me to talk in your server. If you want me to work, fix this.");
}
```
it's the $channel->sendMessage(); line.
I'm assuming the bot doesn't have perms to talk on that channel.
Also this happens if people try to add emoji's to their $greetmsg or my byemsg.

**Comment by uniquoooo** [comment]
I removed the send permissions for my bot and it works fine for me by doing:
```
try {
    dump($text->sendMessage('test'));
} catch (NoPermissionsException $e) {
    echo "Error: {$e->getMessage()}\r\n";
}
```

Also tested it with `DiscordRequestFailedException` and it works fine.
