### ISSUE TITLE
Errors are never displayed

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#381]
DiscordPHP silences all the errors, making it impossible to know what is failing in the program.

Code to reproduce:
```php
$discord = new Discord(...);
$discord->on("message", function($message){
    throw new \Exception("Test exception"); 
});
```

**Comment by oliverschloebe** [comment]
This is a known issue, see https://github.com/teamreflex/DiscordPHP/issues/358

**Comment by kenygamer** [comment]
> This is a known issue, see #358

It was closed. Is there any fix?

**Comment by key2peace** [comment]
Did you update to the recent version and tried?

**Comment by kenygamer** [comment]
> Did you update to the recent version and tried? (See [8410c57](https://github.com/teamreflex/DiscordPHP/commit/8410c57a23b8a7cb230d9730b893106c8f2b4f27))

Yes, I did.

**Comment by key2peace** [comment]
I think you need to look at vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php after install and wrap the call_user_func's in function emit around a try/catch to see if that does what you want.

**Comment by kenygamer** [comment]
> I think you need to look at vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php after install and wrap the call_user_func's in function emit around a try/catch to see if that does what you want.
> 
> Consider this a workaround for testing. I have an idea...

Thanks, but your PR is still not working.

**Comment by key2peace** [comment]
well, I won't mess in external libraries itself, this is as close as I can get to it

**Comment by kenygamer** [comment]
> well, I won't mess in external libraries itself, this is as close as I can get to it

Does anybody know why this happens?

**Comment by davidcole1340** [comment]
It's an 'issue' with ReactPHP promises (issue in quotations because technically it's not really an issue) where any exceptions that are not handled are swallowed. In promises v2.0 any unhandled exceptions will be thrown like normal exceptions, but we will have to wait a while for that.

For now, I've fixed @key2peace's PR so it should emit the exception and log it in the console: 1ad7758c050a733511cb023a4780647b7c255ee1

Could you try update with `composer update`?

**Comment by kenygamer** [comment]
> It's an 'issue' with ReactPHP promises (issue in quotations because technically it's not really an issue) where any exceptions that are not handled are swallowed. In promises v2.0 any unhandled exceptions will be thrown like normal exceptions, but we will have to wait a while for that.
> 
> For now, I've fixed @key2peace's PR so it should emit the exception and log it in the console: [1ad7758](https://github.com/teamreflex/DiscordPHP/commit/1ad7758c050a733511cb023a4780647b7c255ee1)
> 
> Could you try update with `composer update`?

@davidcole1340 I did update, and it still doesn't work.

**Comment by kenygamer** [comment]
After b063fe9 
```
call_user_func_array() expects parameter 1 to be a valid callback
, class 'Discord\Parts\User\Client' does not have a method 'parentEmit' in
 /home/bot/vendor/team-reflex/discord-php/src/Discord/Discord.php on line
1459
```

**Comment by davidcole1340** [comment]
Should be changed on the `master` branch. I will push a new version soon. Exceptions are now thrown like normal exceptions and will cause the script to exit, so make sure you handle them.

**Comment by kenygamer** [comment]
b063fe9 fixes it, thank you.

**Comment by kenygamer** [comment]
Reopening because the errors are now displaying in events and timers but not in `ExtendedPromiseInterface->done()`, etc.
