### ISSUE TITLE
Different types of quotes

### ISSUE THREAD

**Issue by baskettcase** [teamreflex/DiscordPHP#385]
I ran into an issue today. Apparently iOS devices use a different type of quote than the regular " it's a slanted quote, and they point the same direction unlike smart quotes. I use the google keyboard for iOS so I didn't notice it until someone was not able to get the bot to recognize quoted information and that's when we figured out the problem, so I switched to the default iOS keyboard and sure enough.. there's an issue. What can be done to recognize both types of quotes?

So something like this:

!color "red and blue"

Would of course return "red and blue" normally, but with the weird double quotes.. it returns 3 variables 1. "red 2. and 3. blue" Ill try replying with my phone so that you can see what the quotes look like.

**Comment by baskettcase** [comment]
Here you go “these are the default iOS quotes”

**Comment by key2peace** [comment]
roughly something like:
```php
preg_match('/[<list of chars to start a quote>]([^<list of chars to end a quote>]+)/u', $source, $match);
```
$match[1] should contain the quoted stuff

**Comment by baskettcase** [comment]
so is this to replace core code? or within the command itself?

**Comment by davidcole1340** [comment]
Probably best to handle this on your side if you need to use quotes. Even on my phone my quotation marks are different from the ones you have given.

**Comment by baskettcase** [comment]
@davidcole1340 on iPhone?

**Comment by davidcole1340** [comment]
> @davidcole1340 on iPhone?

Yep, looking on this table there are plenty of types of quotation marks: https://en.wikipedia.org/wiki/Quotation_mark#Unicode_code_point_table

If you are doing something like that maybe even look at converting unicode to ASCII to make it easier, assuming you won't need to handle other characters.

**Comment by baskettcase** [comment]
sorry I edited my reply above.. I didn't expect you to reply so quickly! :) From the article it looks like these new quotes were as of iOS 11 and you have to turn them off.. which I can do.. and I can tell people to do.. just seems good to work with it as part of core :)  But if not.. no worries, Ill work at doing what the person said above in all my projects.
