### ISSUE TITLE
Sending private message without intent

### ISSUE THREAD

**Issue by Thorrdu** [teamreflex/DiscordPHP#390]
I might not be the only one but I was wandering is there a way to send a private message to someone without the "loadAllMember" option ( wich doen't work with the new intents ).

I have a table with reminders to send at some times but without the list, I don't know how to do it anymore.

So more simply: Is there a way to load a user with the ID (without beeing in the all member list) to send him a message ?

Thanks by advance

**Comment by Thorrdu** [comment]
Nevermind, I found by myself.
If someone needed the solution:

    $user = $discord->factory(\Discord\Parts\User\User::class, [
        'id' => THE_USER_ID,
    ]);
    $user->sendMessage('THE_MESSAGE');

**Comment by valzargaming** [comment]
#392 may also be related as a possible fix without needing to use factory
