### ISSUE TITLE
Cannot fetch messages from channel

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#395]
The error is something like:
`channel_id` is not a valid snowflake

Code to reproduce:
`$discord` is `\Discord\Discord`
```php
$discord->on("message", static function(\Discord\Parts\Channel\Message $message) : void{
    $message->channel->messages->fetch($message->id)->done(static function(\Discord\Parts\Channel\Message $message) : void{
        \print_r($message);
    }, static function($e){
        echo $e->getMessage() . PHP_EOL; //Error
    });
});
```

**Comment by key2peace** [comment]
as far as I see, the problem is, the code uses id instead of channel_id (as discord sends it) for the channel id... 
https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Channel.php#L41

**Comment by kenygamer** [comment]
> as far as I see, the problem is, the code uses id instead of channel_id (as discord sends it) for the channel id...
> https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Channel.php#L41
> 
> try this:
> 
> ```diff
> diff -urNx .git a/src/Discord/Parts/Channel/Channel.php b/src/Discord/Parts/Channel/Channel.php
> --- a/src/Discord/Parts/Channel/Channel.php     2020-10-25 10:08:48.873043298 +0100
> +++ b/src/Discord/Parts/Channel/Channel.php     2020-11-01 01:41:10.000000000 +0100
> @@ -39,6 +39,7 @@
>   * A Channel can be either a text or voice channel on a Discord guild.
>   *
>   * @property string $id              The unique identifier of the Channel.
> + * @property string $channel_id      The same id as above, just under a different name.
>   * @property string $name            The name of the channel.
>   * @property int $type            The type of the channel.
>   * @property string $topic           The topic of the channel.
> @@ -78,6 +79,7 @@
>       */
>      protected $fillable = [
>          'id',
> +        'channel_id',
>          'name',
>          'type',
>          'topic',
> @@ -116,6 +118,7 @@
>          if (! array_key_exists('bitrate', $this->attributes) && $this->type != self::TYPE_TEXT) {
>              $this->bitrate = 64000;
>          }
> +        $this->channel_id = $this->id;
>      }
> 
>      /**
> ```

That doesn't fix it.

**Comment by davidcole1340** [comment]
Could you post the full error? I can't seem to reproduce it. You shouldn't need to fetch a message after receiving one as the message object should be complete.

**Comment by kenygamer** [comment]
> Could you post the full error? I can't seem to reproduce it. You shouldn't need to fetch a message after receiving one as the message object should be complete.
It's the error I sent earlier: channel_id is not a valid snowflake.

I try to fetch it because the embeds are not in the message object.

**Comment by kenygamer** [comment]
@davidcole1340 It's the error i sent earlier: channel id is not a valid snowflake. 

I try to fetch it because the message object is actually incomplete, l Embeds are not in it.  To make a step-by-step for reproducibility, you add an embed to a message, restart the bot and react to the message, The message doesn't have the embeds anymore.

**Comment by key2peace** [comment]
is your $message->embeds empty? because discord only allows ONE embed for user created channel messages, webhooks may contain more, there may be the issue. 

maybe we need to take that into account in https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Message.php#L286-L301

**Comment by kenygamer** [comment]
> is your $message->embeds empty? because discord only allows ONE embed for user created channel messages, webhooks may contain more, there may be the issue.
> 
> maybe we need to take that into account in https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Message.php#L286-L301

Yes, `$message->embeds` is always empty. No, there is just one embed in the message.

**Comment by kenygamer** [comment]
I think there is a double issue in consideration of that. Also let's not forget that fetch (message) is still not working.

**Comment by davidcole1340** [comment]
Can you try on the lastest master version?

**Comment by kenygamer** [comment]
@davidcole1340 Yes. https://github.com/teamreflex/DiscordPHP/issues/413#issuecomment-725595842
