### ISSUE TITLE
Roles attribute not being populated

### ISSUE THREAD

**Issue by slushpuppy** [teamreflex/DiscordPHP#396]
For the onmessage event, it appears
$message->author->roles where $message is of type  Discord\Parts\Channel\Message 

isn't being populated and instead returns null

**Comment by davidcole1340** [comment]
Could you explain more? Seems to work fine for me:
```php
$discord->on('message', function (Message $message) {
  dump($message->author->roles);
});
```

**Comment by sudofox** [comment]
Also running into this issue. $message->author->roles turns up as null.

**Comment by sudofox** [comment]
I figured it out @slushpuppy @davidcole1340 

For some reason getting a user's roles from a message requires enabling a certain privileged intent.

> **Presence Intent**
> If your bot tracks presence data, you may need the presence intent to receive presence event data.
> NOTE: Once your bot reaches 100 or more servers, this will require Verification and whitelisting. Read more here

You need to enable the Presence Intent under Developer Settings > (select your bot) > Bot > Privileged Gateway Intents
