### ISSUE TITLE
X-RateLimit-Bucket headers?

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#400]
**Requested Rework:**
API calls should be handled and sent to Discord on a per-endpoint basis. Hitting a ratelimit should only halt calls that are associated to the relevant endpoint and method, not for every call that the bot would make. IE. DiscordPHP should attempt to send all queued messages first, _then_ attempt to delete any queued message deletion requests, _then_ attempt to react to a message in a channel, etc...

**Implementation:**
1) Listen to every response received with any API call and store the headers somewhere.
2) (optional) Store all of the that info into SQL or redis so all bots are using the same ratelimit info
3) Any time you execute on a given endpoint and using the same method (get/post/delete/etc) check if a bucket header for it has been logged and apply any relevant ratelimit to it. (Note that some endpoints share ratelimits _and_ can have multiple buckets, so it's important to check all possible buckets)

**Possible issues:**
1) _Race Conditions Everywhere_... Comparing ctime in microtime(true) with time actually passed because discord doesn't (I don't think) pass internal server times with them, so it can be "aight wait until ctime > this time" and then you do and discord be like "nah wait 7 more seconds" and 429 you anyway.
2) I don't believe DiscordPHP is set up to execute per endpoint, only per individual request. This would require a restructure of the current systems for sending requests **_before_** attempting to implement anything else. This would also require grouping requests by bucket and checking the bucket limits both before and after every call. In the best possible case a 429 should only be triggered _maybe_ 2 or 3 times if there are multiple related buckets. It would probably still be worthwhile to keep track of the number of 429s we hit in a short period of time and introduce a temporary slowdown to all requests if that number gets too high to avoid getting banned from the API.
3) There will probably be some weird behaviors with anything that runs in the loop with - >addTimer
4) Some of this implies that we can guess when we may have hit a rate limit, but you can never be sure without actually sending a request and Discord verifying it by a 429. This is like trying to guess what's in a box before trying to open it. We should _usually_ assume that no bucket seen means there is no ratelimit, but can also lead to cases where we hit a remaining of 0 and a microsecond time for when to try again but the request never gets sent to Discord because the client thinks there is still an ongoing ratelimit, or we end up sending the request multiple times when we should have waited because of a recent 429.
5) 429 on gateway (login) will not return this header

**Comment by kenygamer** [comment]
#412. This needs urgent fix because actually anyone can try spam bot actions and cause you getting banned of the API.

**Comment by valzargaming** [comment]
@kenygamer DiscordPHP already has what I consider to be acceptable internal ratelimit handling for this and I am unable to replicate the condition you are referencing. If you are able to find a replicable instance of this occurring please create a separate issue for it.
![image](https://user-images.githubusercontent.com/7202504/98863138-ec39a700-2435-11eb-8898-fa7db614d274.png)

**Comment by kenygamer** [comment]
> @kenygamer DiscordPHP already has what I consider to be acceptable internal ratelimit handling for this and I am unable to replicate the condition you are referencing. If you are able to find a replicable instance of this occurring please create a separate issue for it.
> ![image](https://user-images.githubusercontent.com/7202504/98863138-ec39a700-2435-11eb-8898-fa7db614d274.png)
i've been able to replicate this issue again. Discord is blocking me for about one hour after sending a lot of embeds. Also embeds are not the only API requests.

I've already created an issue to address it (#412). It could be though still related to this for the coincidence of facts.

**Comment by davidcole1340** [comment]
Implemented in latest `master` branch.
