### ISSUE TITLE
is_private returning true when not a direct message

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#403]
![image](https://user-images.githubusercontent.com/7202504/98433738-c6a84880-2097-11eb-8bfd-33cf194ab969.png)
Not really sure why this doesn't seem to be working.

![image](https://user-images.githubusercontent.com/7202504/98433687-3e29a800-2097-11eb-94dd-157faf1cff21.png)
```php
$is_dm = false;
if ($message->channel->is_private){ //True if direct message
	echo '[DM]' . PHP_EOL;
	$is_dm = true;
	return true; //Don't try and process direct messages
}
```
![image](https://user-images.githubusercontent.com/7202504/98433698-57caef80-2097-11eb-9435-efe456677360.png)

And yet I'm having trouble replicating this reliably... Same code on a message in a different channel does not have the same issue.
![image](https://user-images.githubusercontent.com/7202504/98433951-4d115a00-2099-11eb-934a-a6dd34e8eeb1.png)

Another possibility is that the message that is being reacted to in the first instance was not sent while the bot was running and the second one was, meaning that some information could be missing from the library repositories.

**Comment by leolee3914** [comment]
When someone boost the server, is_private will return true.

**Comment by kenygamer** [comment]
> ![image](https://user-images.githubusercontent.com/7202504/98433738-c6a84880-2097-11eb-8bfd-33cf194ab969.png)
> Not really sure why this doesn't seem to be working.
> 
> ![image](https://user-images.githubusercontent.com/7202504/98433687-3e29a800-2097-11eb-94dd-157faf1cff21.png)
> 
> ```
> $is_dm = false;
> if ($message->channel->is_private){ //True if direct message
> 	echo '[DM]' . PHP_EOL;
> 	$is_dm = true;
> 	return true; //Don't try and process direct messages
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/7202504/98433698-57caef80-2097-11eb-9435-efe456677360.png)
> 
> And yet I'm having trouble replicating this reliably... Same code on a message in a different channel does not have the same issue.
> ![image](https://user-images.githubusercontent.com/7202504/98433951-4d115a00-2099-11eb-934a-a6dd34e8eeb1.png)
> 
> Another possibility is that the message that is being reacted to in the first instance was not sent while the bot was running and the second one was, meaning that some information could be missing from the library repositories.

I do it this way: if `message->author` is a `User`, then it is DM context.

**Comment by valzargaming** [comment]
That worked, however the event itself is still not being handled correctly. I've created issue #413 as the root cause is different.
