### ISSUE TITLE
Guild part is missing ->leave()

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#404]
As the title suggest, it should be possible to do `$guild->leave()` or `$discord->guilds->get('id',  $id)->leave()`

It is currently possible to leave by passing $guild back into the repository using `$discord->guilds->leave($guild);`

**Comment by key2peace** [comment]
https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Repository/GuildRepository.php#L42-L63

is this what you where looking for?
