### ISSUE TITLE
Missing channel->bulkDelete() function

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#408]
The $channel part should have a ->bulkDelete() function that takes an integer number and tries to fetch and deletes the last number of messages in a channel.

There is currently no equivalent function that currently exists with the MessageRepository or Channel part. We currently must either already have the $message object, know the message ID, or have a ->messages collection to pass. The best usage that currently exists is the channel part ->getMessageHistory() which accepts an array of options with limit => integer number of messages to fetch, then passing that collection object back to the repository to delete them.

**Comment by valzargaming** [comment]
This should work, but could do with review and consideration for a return.

**Comment by davidcole1340** [comment]
All done #410
