### ISSUE TITLE
Possibly a member chunking issue?

### ISSUE THREAD

**Issue by proxikal** [teamreflex/DiscordPHP#41]
Just updated my composer when i woke up, @uniquoooo I moved all my events into the ready event, without any login errors this time. However this occurs >
![untitled](https://cloud.githubusercontent.com/assets/13383709/14045115/9bc7f9ce-f26d-11e5-99bb-bc3153dbc8ff.png)

**Comment by uniquoooo** [comment]
Seems to be working fine for me:

![membercount](https://cloud.githubusercontent.com/assets/991872/14055402/87547aba-f346-11e5-878a-27cbc29a438c.png)

I'll look into it soon.
