### ISSUE TITLE
Race condition/MessageReaction events (And probably others)

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#413]
I'm pretty sure this is a race condition. This is a reaction to a message that existed in a channel before the bot was started. Reacting to a message does not appear to attempt to fetch the message if it does not already exist. This occurs regardless of whether the storeMessages option is true or false. This also affects other events such as MESSAGE_UPDATE. This was also replicated in my attempts to resolve #403 

```php
$discord->on('MESSAGE_REACTION_ADD', function($reaction) use ($discord) {
    $message = $reaction->message;
    if ( ($message->content == NULL) || ($message->content == "") ){
        echo '[REACT TO EMPTY MESSAGE]' . __DIR__ . ':' . __LINE__ . PHP_EOL;
        return true;
    }
}
```
https://cdn.discordapp.com/attachments/234582138740146176/775908059099824198/unknown.png
![image](https://user-images.githubusercontent.com/7202504/98758029-c4960080-239b-11eb-9f46-aae8d8df86fb.png)

https://cdn.discordapp.com/attachments/234582138740146176/775908021431304232/unknown.png
![image](https://user-images.githubusercontent.com/7202504/98758032-c790f100-239b-11eb-9891-e382c34cbb57.png)

The same issue occurs when a message gets updated. The same issue could probably be resolved by changing L29 of WebSockets/Events/MessageUpdate.php to call ->fetch instead of ->get. This (and other) update functions do not have a return, so there is no issue with scope.
```php
if ($oldMessage = $channel->messages->get('id', $messagePart->id)) {
    $messagePart = $this->factory->create(Message::class, array_merge($oldMessage->getRawAttributes(), $messagePart->getRawAttributes()), true);
}
```
```php
$that = $this;
$channel->messages->fetch($messagePart->id)->then(function ($oldMessage) use ($that)
{
    $messagePart = $that->factory->create(Message::class, array_merge($oldMessage->getRawAttributes(), $messagePart->getRawAttributes()), true);
    //Other stuff
});
```

**Comment by kenygamer** [comment]
@valzargaming I wasted hours in this. Maybe #395? since starting from a root much lower now as you say, `MessageRepository::fetch()` isn't even working. It makes sense that nothing that needs fetching messages can work.

**Comment by valzargaming** [comment]
I can confirm that MessageRepository's fetch is not working, even with getMessageHistory in a channel with only one message in it.

```php
<?php
if ( ($reaction->message->content == NULL) || ($reaction->message->content == "") ){
	echo '[REACT TO EMPTY MESSAGE]' . __FILE__ . ':' . __LINE__ . PHP_EOL;
	echo '[MessageID] ' . $reaction->message->id . PHP_EOL;
	//$reaction->message->channel->messages->fetch($reaction->message->id)->then(function($message) use ($reaction, $discord){
	$reaction->message->channel->getMessageHistory(['limit' => 100])->then(function($message_collection) use ($reaction, $discord){
		//attempt to get the message
		foreach($message_collection as $message){
			if($message->id == $reaction->message->id){
				include 'messagereactionadd2-include.php';
				return true;
			}
		}
	});
	return true; //Don't process blank messages, bots, webhooks, or rich embeds
}
include 'messagereactionadd2-include.php';
return true;
```
messagereactionadd2-include.php:
```php
$message = $message ?? $reaction->message;
$message->channel->sendMessage($message->content); //Never triggers inside the promise scope
```

**Comment by valzargaming** [comment]
Commit 4509920 resolved this by adding the channel endpoint so fetch will work.
