### ISSUE TITLE
Please add more documentation texts

### ISSUE THREAD

**Issue by crustamet** [teamreflex/DiscordPHP#419]
1. How to get users from guild
2. How to send message to a user from the guild

more other stuff, so hard to try find all the commands..

Where are all the events how to use them.

Only documentation is for on(message)

Where the F is the rest ?

**Comment by key2peace** [comment]
do you want some F'ing pie with that and a botgenerator so you don't need to think about anything anymore?

**Comment by crustamet** [comment]
Lol just the basic stuff..

**Comment by key2peace** [comment]
http://teamreflex.github.io/DiscordPHP/

**Comment by crustamet** [comment]
Ok now which is the event for user joining a voice channel ? i cannot find this one

**Comment by key2peace** [comment]
https://discord.com/developers/docs/topics/gateway#voice-state-update

**Comment by crustamet** [comment]
This is nice, it works nice what you gave me i have already implemented it.
but i cannot figure out when the user is leaving the channel.

**Comment by crustamet** [comment]
Its good i figured it out thanks bro.

**Comment by crustamet** [comment]
Ok i have another problem where is the guild repository documentation 

https://discordphp.readme.io/v4.0.0/docs/member

This page is missing

I get this link from here 

https://discordphp.readme.io/docs/guild#repositories

**Comment by crustamet** [comment]
Very annoying can you help me ? with these repository i cannot get all my members from my guild

**Comment by key2peace** [comment]
v4.0.0 is ancient and those docs are old, to get ALL members from your guild, you NEED to have the intents enabled in your botpanel on discord.dev, and you need loadAllnembers to be true in your config, then $guild->members should contain them

**Comment by crustamet** [comment]
i have already done this but the problem is i cannot have access to my GUILD variable how i do that ?



	$discord->on('ready', function ($discord) 
	{
		// Listen for messages.
		$discord->on('message', function ($message, $discord) 
		{
			if($message->content == 'test')
			{
				
				// $MembersRep = new MembersRep();
				
				print_r($discord);
				print_r($discord->guild);
			}
		});
	});

**Comment by key2peace** [comment]
$guild = $message->channel->guild;
damit will ich also sagen, alles was du wissen willst über wo das commando herkomt, findest du in $message

https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Message.php#L28-L59

**Comment by crustamet** [comment]
Thanks bro this is what i was talking about, the basic stuff, now everything is very easy ! 👍 
Im gonna close the issue. and in future if i have some other bugs im gonna write them
