### ISSUE TITLE
Bot activity is not working

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#420]
The custom bot activity is not sent back. Setting the bot presence does nothing.

**Comment by kenygamer** [comment]
Code to reproduce:
```php
$activity = $client->factory(\Discord\Parts\User\Activity::class);
$activity->type = \Discord\Parts\User\Activity::TYPE_PLAYING;
$activity->name = "Custom Activity";
$client->updatePresence($activity, false, "online", false);
```

**Comment by davidcole1340** [comment]
Unfourtunately you can only update the presence with type as `Activity::TYPE_PLAYING`, `Activity::TYPE_STREAMING` and `Activity::TYPE_LISTENING`, It's a Discord limitation for now.

**Comment by davidcole1340** [comment]
Ignore my previous comment, misread. Has the bot recently been stopped? Your code works for me so possibly the bot closed and restarted but the Discord session wasn't cancelled.

**Comment by kenygamer** [comment]
I had this issue before display errors patch, here's the error now. For `Activity::TYPE_WACHING` 

```
Fatal error: Uncaught Exception: The given activity type (3) is invalid.
```

**Comment by oliverschloebe** [comment]
> `Activity::TYPE_WACHING`

Typo? Should be `Activity::TYPE_WATCHING`

**Comment by davidcole1340** [comment]
Only playing, streaming and listening are able to be sent as the activity type, Discord doesn't accept any others for bots.

**Comment by kenygamer** [comment]
@davidcole1340 is it not possible to document that others don't work then?

**Comment by davidcole1340** [comment]
> @davidcole1340 is it not possible to document that others don't work then?

Yup I am working on the documentation so that will come eventually.

**Comment by davidcole1340** [comment]
Did you get this working?

**Comment by kenygamer** [comment]
Yes, I use `Activity::TYPE_PLAYING`! Thank you! @davidcole1340
