### ISSUE TITLE
$guild->members returning only the bot user

### ISSUE THREAD

**Issue by shadowdevfr** [teamreflex/DiscordPHP#421]
Hi

When i'm trying to run this:
`$guild = $message->channel->guild;`
`$member = $guild->members;`
`echo PHP_EOL . "Detected: " . count($member);`
I get only the bot user detected. 
![image](https://user-images.githubusercontent.com/33694505/99291197-b6cef800-283f-11eb-918e-40e0d3dfca51.png)

**Comment by CodiiiDev** [comment]
Use $discord->members

**Comment by thenexxuz** [comment]
(I recently ran into this too) If I recall properly, it's because you, as the owner of the guild, are technically not a member.

If you do `$guild->members->fetch("YOUR-MEMBER-ID")->done(function($member) { print_r($member);});` then you will find your member.

**Comment by davidcole1340** [comment]
Make sure the guild member priviliged intents are enabled in your Discord developer settings:

![image](https://user-images.githubusercontent.com/991872/99366403-6e860780-291d-11eb-9196-eef8a3ee5dd9.png)

**Comment by shadowdevfr** [comment]
Thanks everyone ! Looks like davidcole1340 was right!
![image](https://user-images.githubusercontent.com/33694505/99522482-00315b80-2996-11eb-9ecc-98611ae60fa2.png)
