### ISSUE TITLE
sendEmbed does not take a content parameter

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#423]
The function is currently defined as `public function sendEmbed(Embed $embed): ExtendedPromiseInterface` but the docs indicate that we can add content (message text) to the message itself.
![image](https://user-images.githubusercontent.com/7202504/99312049-78c7d900-282b-11eb-8313-01489f05f747.png)

**Comment by davidcole1340** [comment]
Can use `$channel->sendMessage($content, $tts, $embed);`
