### ISSUE TITLE
Bot sends reply in wrong order

### ISSUE THREAD

**Issue by MikkM** [teamreflex/DiscordPHP#424]
Hi, guys first thanks for amazing work, i am not pro php developer, more like an hobby and enjoy playing around with discordphp.

I want to send some data, to channel, due to discord message length limits i split it to two and put it in array but
i have an weird issue where sometimes it sends seccond message first?!

$discord->on('message', function ($message, $discord) {
	$members = list_members();  //gets some data from mysql database and returns them in array.
	$message->reply($members[0]);
	$message->reply($members[1]); //sometimes this will be sent first.
});

Anyone had similar problem ?

**Comment by valzargaming** [comment]
This sounds like something that will be fixed with #400

**Comment by oliverschloebe** [comment]
Using promises should be the way to go.

```php
$message->reply($members[0])->done(function ($sentmessage) {
     $message->reply($members[1]);
});
```

**Comment by thenexxuz** [comment]
In my case I really cannot use the "done" method.
Mine is for a multi-part poll with the numbers added like this:
`
switch (intval($pollNum[0])) {
    case 10:
        $message->react('🔟');
    case 9:
        $message->react('9️⃣');
    case 8:
        $message->react('8️⃣');
    case 7:
        $message->react('7️⃣');
    case 6:
        $message->react('6️⃣');
    case 5:
        $message->react('5️⃣');
    case 4:
        $message->react('4️⃣');
    case 3:
        $message->react('3️⃣');
    case 2:
        $message->react('2️⃣');
    case 1:
        $message->react('1️⃣');
    default:
        break;
}
`

**Comment by davidcole1340** [comment]
As said above it's because both requests are sent at the exact same time, which should be 'fixed' in a future update. To ensure that the first happens before the second:

```php
$message->reply($members[0])->then(function () use ($message, $members) {
    // message has been sent
    return $message->reply($members[1]);
})->done(function () {
    // both messages have been sent
});
```

**Comment by davidcole1340** [comment]
This should also change on the latest `master` branch, as requests are now placed in a queue and executed in order.
