### ISSUE TITLE
addRole() not working

### ISSUE THREAD

**Issue by shadowdevfr** [teamreflex/DiscordPHP#425]
Hello,

Now I have a new issue, I can't add any roles with this code. 
Maybe I've done something wrong?

![image](https://user-images.githubusercontent.com/33694505/99524509-ce6dc400-2998-11eb-9704-be0244a843e9.png)

**Comment by kenygamer** [comment]
> Hello,
> 
> Now I have a new issue, I can't add any roles with this code.
> Maybe I've done something wrong?
> 
> ![image](https://user-images.githubusercontent.com/33694505/99524509-ce6dc400-2998-11eb-9704-be0244a843e9.png)

The role either does not exist or you do not have sufficient permissions.

**Comment by davidcole1340** [comment]
Are there any errors? You should handle promise errors:

```php
$member->addRole($role)->done(function () {
    // adding role succeeded
}, function ($e) {
    // error
    var_dump($e->getMessage());
});
```

**Comment by shadowdevfr** [comment]
Nope, not any errors.

**Comment by davidcole1340** [comment]
Can you join our Discord server (link in the README) and we can help you some more, feel free to send me more code since this is rather hard to debug with only a small snippet.
