### ISSUE TITLE
Reaction->count remains at zero

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#429]
**Bug report:** `Reaction->count` remains ar zero regardless the message has multiple reactions.

**Feature suggestion:** Reaction could have a list of users that have reacted apart of a number of reactions. This is already possible.

**Comment by davidcole1340** [comment]
`$message->reactions` should now update when any of the reaction events come through, will need to work on the feature suggestion another day.

**Comment by davidcole1340** [comment]
Can you try the `feature/reaction_repository` branch please.

**Comment by kenygamer** [comment]
> Can you try the `feature/reaction_repository` branch please.

I will try it in a few more days.
