### ISSUE TITLE
Sending embeds to a private message not working

### ISSUE THREAD

**Issue by codeinfused** [teamreflex/DiscordPHP#430]
From command client, I can respond to a user via direct message with just text, and this works correctly:
`$message->author->user->sendMessage( $info );`

However, sending an embed does nothing and throws no error (that I saw). I can send an embed to the channel instead to verify it works, but sending to DM fails:
`$message->author->user->sendMessage('Notice', false, $embed_body);`

This functioned in 4.x, is there a different approach now?

**Comment by kenygamer** [comment]
@codeinfused But what is the error? Errors can be many.

**Comment by davidcole1340** [comment]
Seems to be working for me. Is your `$embed_body` an instance of `Discord\Parts\Embed\Embed`? If not:

```php
$embed = new \Discord\Parts\Embed\Embed($discord, $embed_body);
$message->author->user->sendMessage('Notice', false, $embed);
```

**Comment by codeinfused** [comment]
@davidcole1340 Yep that was the difference, user->sendMessage just not automatically parsing embed attributes. If you pass embed attributes to channel->sendMessage, it does auto-detect it. Your suggestion above using the class directly worked. Thanks, I'll switch all my embeds!

**Comment by kenygamer** [comment]
> Seems to be working for me. Is your `$embed_body` an instance of `Discord\Parts\Embed\Embed`? If not:
> 
> ```
> $embed = new \Discord\Parts\Embed\Embed($discord, $embed_body);
> $message->author->user->sendMessage('Notice', false, $embed)->done(); // adding done at the end forces any exceptions to be thrown
> ```

@davidcole1340 If a `Message` can have `Embed`s, is it not more appropriate to remove the third parameter that just lets you specify (one) embed? That way `Channel::sendMessage()` can (also) send more than one embed?

**Comment by davidcole1340** [comment]
Unfourtunately you can only specify one embed when creating and updating a message: https://discord.com/developers/docs/resources/channel#create-message
