### ISSUE TITLE
Cannot ban a Member

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#431]
When you try to ban a member, DiscordPHP uses the `POST` method instead of the `PUT` method documented at the official API. You can't ban the user.

Dising this would most likely need changing how `AbstractRepository::save()` because at the moment it only relies on if the `Part` was created to send a `PATCH` request (to update) or `POST` request (to create); in the latter case, it is **not always** `POST` like in `guilds/:guild_id/bans/:user_id`. 

Also, `:user_id` is back to having issues, and not being replaced in the endpoint URL.

I tried to implement my own fix but I'm now getting a Bad Request. I have no more time to keep looking for a fix.

**Comment by davidcole1340** [comment]
For now you can use `$member->ban()` but I will fix this, didn't realize it wouldn't work through the repository.

**Comment by kenygamer** [comment]
> For now you can use `$member->ban()` but I will fix this, didn't realize it wouldn't work through the repository.

Thank you.
