### ISSUE TITLE
user->sendMessage() is to long.

### ISSUE THREAD

**Issue by crustamet** [teamreflex/DiscordPHP#434]
How can i make to send a text file instead of the long message when it reached the maximum length ?

im using this method to send message

$msg = 'Too long message';
$message->author->user->sendMessage();

In the discord docs says when you send a long msg it will convert it automatically into text, but it doesnt work for the bot like this.
Can someone help me ?

**Comment by key2peace** [comment]
the same way discord client does, check if length > limit, if true, sendFile instead of sendMessage

**Comment by crustamet** [comment]
This does not work bro

**Comment by key2peace** [comment]
I am not your bro, and this does indeed not work out of the box, YOU need to code that....
