### ISSUE TITLE
Cannot get the embeds of a message in Event::MESSAGE_REACTION_ADD

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#435]
Error:
```
Undefined index: embeds in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 296 
```

The embeds attribute is not set when you try to get the embeds of a `Message` in `MESSAGE_REACTION_ADD` event.

It occurs when the `Message` was sent before the bot restarted.

**Comment by davidcole1340** [comment]
Have to fetch the message from Discord:
```php
$discord->on(Event::MESSAGE_REACTION_ADD, function (MessageReaction $reaction) {
    $reaction->channel->messages->fetch($reaction->message_id)->done(function (Message $message) {
        // ...
    });
});
```

**Comment by kenygamer** [comment]
> Have to fetch the message from Discord:
> 
> ```
> $discord->on(Event::MESSAGE_REACTION_ADD, function (MessageReaction $reaction) {
>     $reaction->channel->messages->fetch($reaction->message_id)->done(function (Message $message) {
>         // ...
>     });
> });
> ```

Cannlt the embeds just not be available instantly, such as automatically feching the Message before the event is called?

**Comment by kenygamer** [comment]
@davidcole1340 A similar error is hapenning with 'Message`, these logs can't be tolerated...

'``Notice: Undefined index: mention_roles in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 235
Warning: array_search() expects parameter 2 to be array, null given in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php
on line 235
```

**Comment by valzargaming** [comment]
First of all, what build are you using? Line 235 of the current Master is `} else {` so it is impossible for your error message to be relevant in the current branch.

**Comment by kenygamer** [comment]
@valzargaming My dude, line 235 of `Message` is this
https://github.com/teamreflex/DiscordPHP/blob/master/src/Discord/Parts/Channel/Message.php#L235

I updated just to confirm and it gives the same error. It also happens when trying to fetch the message history.

**Comment by kenygamer** [comment]
@davidcole1340 Feching the message history still gives you errors.

```
Notice: Undefined index: mentions in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 258
Warning: Invalid argument supplied for foreach() in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 258
Notice: Undefined index: timestamp in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 315
Notice: Undefined index: edited_timestamp in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 326
Notice: Undefined index: embeds in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 300
Warning: Invalid argument supplied for foreach() in /home/bot/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php on line 30
``` 

**The base problem is that you can have `Messages` with unfilled attributes. That should not happen.*** We shouldn't have to fetch messages because that makes us write more code, DiscordPHP should do that. There is no purpose in having a message with `channel_id`, `author_id`.  I am not interested in who wrote or where the message was sent, I am interested in seeing what was sent in the message.

**Comment by kenygamer** [comment]
@davidcole1340 Issue still happens, only when you fetch one message.  Fetching message history works fine.

**Comment by davidcole1340** [comment]
What version are you running? Can't seem to reproduce it, should have been fixed a couple days ago
```php
$channel = $discord->getChannel('');
$channel->messages->fetch('')->done(function (Message $message) {
    var_dump($message);
});
```
