### ISSUE TITLE
Using VoiceClient::playFile causes PHP warnings in the loop

### ISSUE THREAD

**Issue by rederrik** [teamreflex/DiscordPHP#438]
**Versions affected**: 5.0.12, dev-master

**Description**  
After invoking `VoiceClient::playFile()` an endless stream of repeated warnings is produced by the current loop.
```
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, cannot access private method Discord\Helpers\ReadableResourceStream::handleData() in /home/vagrant/discord-bot/vendor/react/event-loop/src/ExtEvLoop.php on line 95
PHP Stack trace:
PHP   1. {main}() /home/vagrant/discord-bot/clean.php:0
PHP   2. Discord\DiscordCommandClient->run() /home/vagrant/discord-bot/clean.php:39
PHP   3. React\EventLoop\ExtEvLoop->run() /home/vagrant/discord-bot/vendor/team-reflex/discord-php/src/Discord/Discord.php:1333
PHP   4. EvLoop->run(*uninitialized*) /home/vagrant/discord-bot/vendor/react/event-loop/src/ExtEvLoop.php:207
PHP   5. React\EventLoop\ExtEvLoop->React\EventLoop\{closure:/home/vagrant/discord-bot/vendor/react/event-loop/src/ExtEvLoop.php:94-96}() /home/vagrant/discord-bot/vendor/react/event-loop/src/ExtEvLoop.php:207
```
The bot itself works fine and plays sound correctly.

**How to reproduce**  
Here is the code I used to reproduce this issue (excluding the token and `murloc.wav` file, of course):
```PHP
<?php

use Discord\DiscordCommandClient;
use Discord\Parts\Channel\Message;
use Discord\Voice\VoiceClient;

include __DIR__.'/vendor/autoload.php';

$discord = new DiscordCommandClient([
        'token' => 'ValidBotToken',
        'prefix' => '!!',
]);

$discord->registerCommand('playtest',
    function (Message $message) use ($discord) {
        $voiceStates = $message->channel->guild->voice_states;
        $userId = $message->author->id;

        foreach ($voiceStates as $voiceState) { //Find a voice channel the user is in
            if ($voiceState->user_id === $userId) {
                $channel = $discord->getChannel($voiceState->channel_id);
            }
        }

        if (empty($channel)) { //Channel not found
            return $message->reply("Can't join your current voice channel");
        }

        $discord->joinVoiceChannel($channel)->then(
            function (VoiceClient $voice) {
                $voice->playFile(__DIR__.'/sounds/murloc.wav')->then([$voice, 'close']);
            }
        );
    }
);

$discord->run();
```
After adding bot to your server join some voice channel and send `!!playtest`.

**Possible Solution**  
Unfortunately, I was unable to pinpoint the exact origin of the callable causing this issue. I hope someone familiar with the code of `VoiceClient` can explain me why is this happening. 
Changing the visibility `Discord\Helpers\ReadableResourceStream::handleData()` from private to public obviously resolves the issue, but I assume that's not the way.

**Comment by davidcole1340** [comment]
`ReadableResourceStream::handleData()` was always meant to be public, seems it was accidentally changed at some point. I've fixed this and recompiled DCA, cheers!

**Comment by davidcole1340** [comment]
Also going to take this opportunity to change `Discord::getVoiceClient()` to *not* return a promise as it seems no one is using the voice client.

**Comment by xxAROX** [comment]
@davidcole1340 maybe its possible voice support for windows?

**Comment by davidcole1340** [comment]
@xxAROX not really, since ReactPHP's Child Process module doesn't work on windows, it blocks the event loop: https://github.com/reactphp/child-process#windows-compatibilityz

**Comment by davidcole1340** [comment]
You could try something:

1. I can compile DCA for Windows for you
2. Convert a file to DCA format
3. Open the file with [react/stream](https://github.com/reactphp/stream) and `fopen()`
4. Play with `$vc->playDCAStream()`

But this means you will have to pre-encode your files. You'll also have to comment out the line in `VoiceClient` where the error is thrown (345-349)

**Comment by xxAROX** [comment]
okay, i try soon as i can

**Comment by davidcole1340** [comment]
DCA for Windows is available on our Discord server in the announcements. Usage:

Convert the file (run this in command prompt - NOT powershell, I had issues with powershell inserting a byte order mask which confused DiscordPHP): `.\dca-v0.1.0-windows-4.0-amd64.exe -ac 2 -aa audio -ab 64 -as 960 -vol 256 -i .\song.mp3 > song.dca`

Play the file (not the 5th parameter false - skip checks to see if requirements are installed):
```php
$discord->joinVoiceChannel($channel, false, true, null, false)->done(function (VoiceClient $vc) use ($discord) {
    $streamRes = fopen('C:\\path\\to\\song', 'r');
    $vc->playDCAStream($streamRes)->done();
});
```
