### ISSUE TITLE
Author is me

### ISSUE THREAD

**Issue by MincoMK** [teamreflex/DiscordPHP#441]
How to Check msg author is bot?
ex) if($msg->author == $bot) { return; }
What's for `$bot`?
`$this`? Or `$discordClient`?
I think it's user object.
How to get usr obj from my bot?

**Comment by Ravisdo** [comment]
$discordClient
And better check would be to use 
`$msg->author->id == $bot->id`

**Comment by MincoMK** [comment]
> $discordClient
> 
> And better check would be to use 
> 
> `$msg->author->id == $bot->id`

Oh THX

**Comment by Ravisdo** [comment]
I guess. Dont know hour your code looks like

**Comment by MincoMK** [comment]
> I guess. Dont know how your code looks like

Nothing like "id" in Discord\Discord obj

**Comment by davidcole1340** [comment]
> > I guess. Dont know how your code looks like
> 
> Nothing like "id" in Discord\Discord obj

The `Discord\Discord` class passes get calls to the `Client` object which has an `id` object, so you can call `$discord->id` on the Discord client. See the properties in the phpdoc: http://teamreflex.github.io/DiscordPHP/reference/classes/Discord-Discord.html#property_id
