### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#445]
https://github.com/teamreflex/DiscordPHP/blob/8e9db5cff2fa17034ff57fa5e1b0bfcded8e1d52/src/Discord/WebSockets/Events/MessageReactionAdd.php#L34

**Comment by davidcole1340** [comment]
Merged the reaction repository branch which will change the way these events are handled, will leave open until confirmed fixed

**Comment by Thorrdu** [comment]
I has the same issue. it seems fixed with the update.
Thank you ;)
