### ISSUE TITLE
Get help for SubCommand does not work

### ISSUE THREAD

**Issue by crustamet** [teamreflex/DiscordPHP#449]
i have set up !admin commands

!admin announce
!admin kill

all good and dandy
but when i type !help admin kill
does not give me help for this command

i receive this msg : **BOT: The command admin kill does not exist.**
The command exists and it works when i type !admin kill, it kills the bot.

what i am doing wrong ?

**Comment by davidcole1340** [comment]
`!help admin`

**Comment by crustamet** [comment]
My prefix is !

because i have other commands without !admin permissions
like !movies

**Comment by key2peace** [comment]
are you using discord or discordcommandclient? if using commandclient, are you using registersubcommand? could you show some code?

**Comment by crustamet** [comment]
$adminCommands = $discordCommands->registerCommand('admin', function ($message) use ($db, $discord)
	{
		return 'More info on how to use Admin tools **!help admin**';
	}, [
		'description' => 'Admin only tools.',
		'usage'	=> '!admin <command>'
	]);

	$adminCommands->registerSubCommand('announce', function ($message) use ($db)
	{
		$guild = $message->channel->guild;
		$members = $guild->members;
		
		return 'Announce written.';
	}, [
	  'description' => 'Send a private message with the upcoming movies to all users registered for movie nights.',
	  'usage' => '!admin announce',
	]);

**Comment by crustamet** [comment]
It is easy how can i get help information about subcommands. this is what i am trying to figure it out.

!help admin announce

**Comment by key2peace** [comment]
this is not how DiscordCommandClient works,, ,it is a WRAPPER around the normal Discord cl;ass,, $discordCommands == $discord.

**Comment by crustamet** [comment]
At least can i get your discord so you can see what is the problem ?
Everything works as aspected but the !help command for subcommands does not return the information. 
Ofcourse its a wrapper around the Discord Class, this is what i have in the **$options** variable.

Im gonna post some some images so you can see exactly the problems.

This is when i type **!help**

![image](https://user-images.githubusercontent.com/36475250/101279877-234d6f00-37ce-11eb-9739-6595afe937fa.png)

This is when i type **!help admin**

![image](https://user-images.githubusercontent.com/36475250/101279887-4a0ba580-37ce-11eb-86b4-8d4360928a23.png)

And this is when i type **!help admin announce**

![image](https://user-images.githubusercontent.com/36475250/101279899-5e4fa280-37ce-11eb-8619-2e1a4326e774.png)

**Comment by crustamet** [comment]
Well this works now, but the problem now is you show every command
when you type !help
it should show only Commands and not subCommands

It must show the subcommands when you type !help **command**
