### ISSUE TITLE
Update psr7

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#455]
`reactphp/http`'s composer's require section is outdated, referencing ringcentral/psr7. The newest version of this is guzzle/psr7. An previous issue on the reactphp stated that they used the ringcentral fork because of php5 support, but since we use php7+ we should not be using it.

**Comment by davidcole1340** [comment]
Can't update since it's on ReactPHP's side and they still support PHP 5.3. What's the difference anyway?
