### ISSUE TITLE
FetchAll Invites

### ISSUE THREAD

**Issue by crustamet** [teamreflex/DiscordPHP#456]
I am having trouble fetching the invites when a new member joins the guild

This only works if the bot was online at the moment when the invites were created.

But something happened maybe bot crash and i have to restart again. This is making me loosing the invites repository.

There is no way to fetch all invites from the endpoint.

**Comment by davidcole1340** [comment]
You can "freshen" the invite repository which goes to the Discord servers and fetches all the content:

```php
$guild = ...;
$guild->invites->freshen()->done(function (\Discord\Repository\Guild\InviteRepository $invites) {
    // do something
});
```

**Comment by crustamet** [comment]
this is nice never thought you can do that...
