### ISSUE TITLE
Call to a member function has() on null

### ISSUE THREAD

**Issue by valzargaming** [teamreflex/DiscordPHP#459]
https://github.com/teamreflex/DiscordPHP/blob/21a59c59c00e8e06d90860fb4d80d3365c250dd7/src/Discord/WebSockets/Events/GuildCreate.php#L58

In certain circumstances (so far replicated during reconnect/session resume where Discord may think the bot still has data when it does not) the user repository will not yet exist and the bot will throw an error. This is a difficult issue to replicate because it may be caused by Discord API issues. A good fix to this would be to instantiate the repositories before attempting to connect to the gateway for the first time.

**Comment by davidcole1340** [comment]
Closing for now - reopen if issue reappears.
