### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by uniquoooo** [teamreflex/DiscordPHP#46]
This is an issue post to gather all information about Version 4.0.0.

Current changes:
- New caching system
- Dependency injection
- Part factories
- REST client will be passed around instead of using static methods

**Comment by uniquoooo** [comment]
@aequasi since everything will be non-static, what do you think about having drivers for the REST client so that we can use the ReactPHP HTTP Client for async requests and use Guzzle when not using the WebSocket?

**Comment by aequasi** [comment]
I think that's a really good idea.

**Comment by uniquoooo** [comment]
@aequasi what do you think about having promises everywhere? There are some things that don't need promises but should we still use promises so that it is consistent?

**Comment by uniquoooo** [comment]
I haven't converted these methods yet as they don't use HTTP requests:

```
- Channel::getOverwritesAttribute()
- Guild::getRolesAttribute()
```

**Comment by aequasi** [comment]
being consistent is generally a good idea, i'd say lets put them everywhere

**Comment by uniquoooo** [comment]
Version 4 being released.
