### ISSUE TITLE
Cannot create a category

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#462]
**Environment**
- PHP Version:
    8.0.0 (CLI)
- DiscordPHP Version: 3892e9c

**Describe the bug**
Cannot create a category.  When you try to make one, with `Channel->type = Channel::TYPE_CATEGORY`, a text channel is created instead.

**To Reproduce**

```php
use Discord\Parts\Channel\Channel;

$discord->on("ready", function () {
    $channel = $discord->factory(Channel::class);
    $channel->type = Channel::TYPE_CATEGORY;
    $guild = $discord->guilds->first();
    $guild->channels->save($channel)->done();
});
```

See the text channel that is created.

**Expected behavior**
You should be able to create a category channel instead of a text channel.

**Additional context**
Untested with other channel types.

**Comment by davidcole1340** [comment]
Try on master please
