### ISSUE TITLE
Cannot create category channels

### ISSUE THREAD

**Issue by kenygamer** [teamreflex/DiscordPHP#466]
I can't create category channels. The error is:

```
Not Found
```

Seems like an unexisting endpoint. The correct endpoint is: `POST guilds/{guild.id}/roles`

**Comment by davidcole1340** [comment]
Can you post an example? I can't reproduce.

**Comment by kenygamer** [comment]
> Can you post an example? I can't reproduce.

```
$channel = $client->factory(Channel::class);
$channel->type = Channel::TYPE_CATEGORY;
$channel->name = "Test Category";
$guild->channels->save($channel)->done();
```
