### ISSUE TITLE
Associate User to Role

### ISSUE THREAD

**Issue by rupertjeff** [teamreflex/DiscordPHP#61]
Is there a way to associate a Guild Member to a Role within the guild? I'm having significant issues trying to determine whether or not a specific user is in one or more roles.

I am starting with a `Discord\Parts\Channel\Message` and an array of pre-existing Role names. I'm finding that `$message->fullChannel->guild` does not have a `->members` property, and `$message->author` does not seem to have any sort of guild/role association.

Thanks!

**Comment by proxikal** [comment]
I did something like this when i needed to find user roles.
```php
$guild = $discord->guilds->get('name', 'Paradox Lounge');
$member = $guild->members->get('id', $message->author->id);
// dump ($member);
 foreach($member->roles as $dat)
 {
 	$test = $dat->name; // grabs the last role name. this is only for testing purposes.
 	$cnr++;
 }
```
The above code will grab every role from a specific user and display the last role in the variable $test.
You can manipulate it to search for multiple roles, members etc..

**Comment by rupertjeff** [comment]
Interesting, thanks! That seems to give me what I need.
