### ISSUE TITLE
[dev-develop]Fatal error: Call to a member function pack()

### ISSUE THREAD

**Issue by sanson222** [teamreflex/DiscordPHP#96]
I had this error in my code.
I checked the source code(WebSockets/WebSocket.php) and note that the variable $useEtf is set true, changing the variable to false the code work

The error:
`Fatal error: Call to a member function pack() on null in D:\Kouku\vendor\team-reflex\discord-php\src\Discord\WebSockets
WebSocket.php on line 950 `

PD: Sorry for my bad English

**Comment by uniquoooo** [comment]
Should be fixed in the latest update, can you confirm?
