### ISSUE TITLE
Issue with Server Count and Memory Leak

### ISSUE THREAD

**Issue by zigithebanana** [teamreflex/DiscordPHP#97]
The server count duplicates after 1 hour of running which also increases memory usage. Which could be a issue for large bots

> Library: DiscordPHP v3.2.0-beta
> Library Revision: b76c8c6
> Library Branch: master
> PHP Version: 7.0.5-1~dotdeb+8.1
> Uptime: 0 day(s), 0 hour(s), 0 minute(s), 9 second(s)
> Memory Usage: 41.94mb
> OS Info: Linux uk-01.zigibot.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
> Server Count: 107
> Joined at: 05/04/2016 01:04:55
> Guild Region: US East
> Guild Users: 4328
> Guild Owner: Voltana#8252

after a hour or so

> Library: DiscordPHP v3.2.0-beta
> Library Revision: b76c8c6
> Library Branch: master
> PHP Version: 7.0.5-1~dotdeb+8.1
> Uptime: 0 day(s), 1 hour(s), 34 minute(s), 58 second(s)
> Memory Usage: 71.3mb
> OS Info: Linux uk-01.zigibot.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
> Server Count: 220
> Joined at: 05/04/2016 01:04:55
> Guild Region: US East
> Guild Users: 4337
> Guild Owner: Voltana#8252`

had this issue on master branch and bot-api branch.

**Comment by zigithebanana** [comment]
> Library: DiscordPHP v3.2.0-beta
> Library Revision: b76c8c6
> Library Branch: master
> PHP Version: 7.0.5-1~dotdeb+8.1
> Uptime: 0 day(s), 0 hour(s), 46 minute(s), 21 second(s)
> Memory Usage: 54.53mb
> OS Info: Linux uk-01.zigibot.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
> Server Count: 312
> Joined at: 05/04/2016 12:04:23
> Guild Region: Amsterdam
> Guild Users: 1280
> Guild Owner: meew0#9811

My bot crashed overnight due to this and now after 46 minutes my server count has gone insane again..

**Comment by aequasi** [comment]
Assuming resolved, not having issues with memory or counts on my bots
